openstack/config.go, openstack/provider.go
Rename existing uses of `osClient` to `OsClient`.
This is a rework of hashicorp/terraform@f3c52416a56d7772bd633f08cab48c10696bcf3d
Required for https://github.com/hashicorp/terraform/pull/13871
=> Expose Config.LoadAndValidate func and Config.OsClient type field.

openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go, openstack/util.go
For #4 
This PR waits until the load balancer is in an "ACTIVE" state before trying to create a pool or monitor that depends on the load balancer. Note that if the load balancer ID is not used in the resource's definition in the Terraform configuration file, this check will not happen.
Also of note is that the underlying issue is [seemingly] in OpenStack, where it will return a `409`, yet still create the resource (possibly due to a race condition of getting hammered several times in a few milliseconds with create requests). Even the fix in this PR cannot completely prevent that race condition:
Consider: 
1. a resource is waiting on a load balancer to become "ACTIVE".
2. a different resource is simultaneously waiting on that load balancer to become "ACTIVE".
3. the load balancer goes to …
=> wait for lb active state before trying to create pool or monitor

openstack/resource_openstack_blockstorage_volume_attach_v2.go
Removing a deprecated argument
=> BlockStorage v2: Remove instance_id from volume attach

openstack/resource_openstack_compute_instance_v2.go
In some providers, OpenStack can't found the right network uuid. In this case, the content of old values of networks are stored and throw an error at the creation. For example, if we create an instance with a private and a public network. OpenStack doesn't provide the right uuid of private network. In this case, Terraform keep the old value, the public uuid and try to assign a private address to a public network, what is not possible to happen.
=> fix(builtin/provider): OpenStack

openstack/compute_instance_v2_networking.go, openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2_test.go
This commit does a large refactor of how networking is handled in
the openstack_compute_instance_v2 resource.
Two features were added:
1. The ability to attach an instance to the same network multiple
times.
2. The ability to use the Networking API and fall-back to the
legacy Nova Network API if required.
The network code was refactored and placed into a dedicated file
due to the number of functions required to determine an instance's
network configuration.
It is important to note that no changes were made to the Terraform
schema. Further, existing users should notice no difference in
the original functionality of the resource.
Fixes #28 
Fixes #5
=> Compute v2: Instance Networking Refactor

openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_listener_v2_test.go, website/docs/r/lb_listener_v2.html.markdown
The existing `HTTPS` protocol on a `openstack_lb_listener_v2` resource does not function properly if it's passing to an A10 backed loadbalancer.  This LB needs to have the protocol defined in neutron as "TERMINATED_HTTPS".
=> Adding support for 'TERMINATED_HTTPS' for lb_listeners backed by A10 networks LBs

website/docs/r/lb_listener_v2.html.markdown
Modify the attribute descriptions for `protocol` and `protocol_port` to match the description style used on the terraform.io website.
=> Update attribute description style

openstack/resource_openstack_lb_pool_v2.go, website/docs/r/lb_pool_v2.html.markdown
Need to work on validation, as 'ValidateFunc' can\'t access other schema values...
Fixes #57
=> openstack_lb_pool_v2 - Make 'cookie_name' optional. 

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go
In most cases it is is sufficient to just wait for the LB to become
ACTIVE again. In areas where the lbID wasn't readilt available
retrive it through the pool object and wait on LB.
=> Lbaa s v2 timeouts

openstack/resource_openstack_lb_loadbalancer_v2.go, website/docs/r/lb_loadbalancer_v2.html.markdown
Deprecation was added in https://github.com/hashicorp/terraform/pull/12239 (in February 2017).
That said the user wouldn't ever see the deprecation message because the whole field (along with some other reserved fields) is removed before CRUD even gets chance to process it.
https://github.com/hashicorp/terraform/blob/5bcc1bae5925f44208a83279b6d4d250da01597b/config/loader_hcl.go#L673-L676
This is first step towards bumping `hashicorp/terraform` to `v0.10.0` which has validation for these kinds of things (see https://github.com/hashicorp/terraform/pull/15562).
=> r/lb_loadbalancer_v2: Remove 'provider' field

openstack/resource_openstack_fw_firewall_v1.go, openstack/types.go
This commit fixes a bug where `value_specs` was not being sent
in the body of the create request.
Fixes #66
=> Firewall v1: Fix value_specs during create

openstack/data_source_openstack_images_image_v2.go
This commit fixes the behavior of the `most_recent` argument
in the `openstack_images_image_v2` data resource. Rather than
sorting images by the `UpdatedAt` field, it now sorts images by
`CreatedAt`.
Fixes #75
=> Images v2: Fix Most Recent Behavior in Image Data Source

openstack/resource_openstack_networking_secgroup_v2.go
Creating a security group with the attribute delete_default_rules set did not remove the default rules.
This addition makes the provider reread the security group before looping over the rules inside.
=> Added reread of security group before deleting default rules

openstack/compute_instance_v2_networking.go
This commit fixes a bug and a typo with determining the access_ip_*
attributes and the mac address of a virtual NIC.
Fixes #84
=> Compute v2: Fix Access IP and MAC Addresses

openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_listener_v2_test.go
This commit changes the behavior of the `openstack_lb_listener_v2`
resource so that the `connection_limit` argument is not sent
unless it has been explicitly defined in the configuration.
Fixes #87
=> LBaaS v2: Don't send connection_limit unless it has been set

openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go
Terraform core recently made the `id` field reserved. This commit
removes the redundant id field from the LBaaS v2 resources.
=> LBaaS v2: Remove ID fields

openstack/data_source_openstack_networking_network_v2.go, website/docs/d/networking_network_v2.html.markdown
Hi all,
my openstack provider for some reasons does not allow to filter the external network by status. So the default filter "&status=ACTIVE" will not show the external network when searching for it. 
I created a new attribute called **only_active**, which can be set to false to remove the ACTIVE filter. If this attribute is not used, it defaults to the ACTIVE filter, so it shouldn't breaking existing terraform scripts.
I am **NOT** a Go programmer, so if this can be done in a more elegant way, just mention it and I will change it accordingly.
Cheers,
Christian
=> make it possible to search for non active networks

openstack/import_openstack_networking_router_interface_v2_test.go, openstack/resource_openstack_networking_router_interface_v2.go
This commit amends the router interface import feature
by setting the subnet_id when the subnet_id can be
confidently determined.
For #108
=> Networking v2: Import router interface subnet

openstack/import_openstack_networking_router_route_v2_test.go, openstack/resource_openstack_networking_router_route_v2.go, openstack/resource_openstack_networking_router_route_v2_test.go, website/docs/r/networking_router_route_v2.html.markdown
Added support for import of router routes (#108)
TestAcc passed: 
```shell
$ make testacc TEST=./openstack TESTARGS="-run TestAccNetworkingV2RouterRoute_importBasic"
=== RUN   TestAccNetworkingV2RouterRoute_importBasic
--- PASS: TestAccNetworkingV2RouterRoute_importBasic (73.31s)
PASS
ok      github.com/terraform-providers/terraform-provider-openstack/openstack   73.400s
```
=> Added support for import of router routes

openstack/resource_openstack_networking_router_v2.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go, vendor/vendor.json, website/docs/r/networking_router_v2.html.markdown
Hi!
This is for #134
This PR adds the `enable_snat` property to the networking_router_v2 resource to enable/disable snat for neutron routers.
I've testet this against my openstack provider and it works fine! But again, I don't really know GO, so if this can be done more elegant, I'm open for suggestions :)
I am also not sure if it is the right thing to raise an error if `external_gateway` is not set, or if I should just ignore the parameter in that case.
Cheers,
Christian
=> openstack_networking_router: enable/disable snat

openstack/data_source_openstack_dns_zone_v2_test.go
The OpenStack environment used for testing doesn't support Designate yet.
=> DNS v2: Skip Zone data source acceptance test

openstack/resource_openstack_networking_subnet_v2.go
This commit adds a schema ConflictsWith for the subnet gateway
options allowing the error to be caught earlier in the
plan/apply phase instead of when resources began to be created.
Saw the opportunity to do this while making the subnet data source.
=> Networking v2: ConflictsWith for Subnet Gateway

openstack/provider_test.go, openstack/resource_openstack_db_instance_v1_test.go, openstack/resource_openstack_objectstorage_object_v1_test.go
This commit cleans up some of the acceptance test conditionals,
including adding a conditional for environments which do not support
the OpenStack database service.
=> Acc Tests: Update Acceptance Tests

openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_router_v2_test.go, website/docs/r/networking_router_v2.html.markdown
This commit makes two changes to the openstack_networking_router_v2
resource:
1. Deprecates external_gateway in favor of external_network_id. The
new name provides a better indication of what value should be set.
2. Adds support for external_fixed_ips. These can be specified by
the user as well as are set by the API when not specified.
=> Networking v2: Updates to openstack_networking_router_v2

examples/app-with-networking/README.md, examples/app-with-networking/main.tf
Fixes #191
app-with-networking example is out-of-date, can't work, update it.
* Using "external_network_id" attribute instead of "external_gateway"
in resource openstack_networking_router_v2
* Using resource openstack_compute_floatingip_associate_v2 instead of
"floating_ip" attribute of resource openstack_compute_instance_v2
* Update example README to use openstackclient CLI
=> Update app-with-networking example

.zuul.yaml
I'd like to introduce a CI system "Openlab" into
Terraform-provider-openstack. The Openlab CI system is built based on
zuul[1] and nodepool[2] tools and some other components, it is for
running tests of OpenStack SDKs (e.g.Gophercloud, Terraform) based on a
devstack[3] environment. For more details about Openlab, please see[4].
We have  done the integration of Openlab CI and Gophercloud in
PR[5]. For now, the CI system can also basically work OK with
Terraform-provider-openstack, see[6]. We will long-term maintain the CI
system and would like to integrate the CI system to
Terraform-provider-openstack official repo.
FYI, the zuul jobs definition is in[7], the zuul jobs status web page is
in [8], the logs of testing jobs is in[9].
[1] https://docs.openstack.org/infra/zuul/
[2] …
=> Request to integrate the Openlab CI to Terraform-provider-openstack

openstack/data_source_openstack_networking_network_v2.go, openstack/resource_openstack_networking_network_v2.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go, vendor/vendor.json, website/docs/d/networking_network_v2.html.markdown
This allows users to associate an availability zone with their network 
* [availability_zone_hints](https://developer.openstack.org/api-ref/network/v2/index.html#networks) (missing in docs but supported by openstack cli and is about to be added to [webui](https://git.openstack.org/cgit/openstack/horizon/commit/?id=b9664a1bf139e6714aa4d507a68ce03d551779aa))
```
resource "openstack_networking_network_v2" "network" {
name               = "terraform-ipv6"
admin_state_up = "true"
shared             = "false"
availability_zone_hints = ["zone1", "zone2"]
}
```
=>  Support for availability_zone_hints for networks

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_router_v2.go, openstack/util.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go, vendor/vendor.json, website/docs/r/networking_network_v2.html.markdown, website/docs/r/networking_router_v2.html.markdown
This allows users to associate an availability zone with their
resources.
```
resource "openstack_networking_router_v2" "testrouter" {
name                      = "testrouter"
availability_zone_hints   = ["zone1", "zone3"]
}
```
When/if #196 is accepted, one improvement would be to break out  resourceNetworkingRouterkAvailabilityZoneHintsV2_ into util.go and 
use it from borth networks and router.
=> Allow setting availability_zone_hints on router.

.zuul.yaml
This change try to add two jobs for Trove and Designate related tests,
which can be run against the Openlab CI. Since the acceptance tests for
database service(Trove) and DNS service(Designate) need some specific
environment configurations, and the tests are time-consuming, we'd better
don't run the tests when every new PR submitted. Insteaded, we use two
separated jobs to run the tests and need to manually triggerred by comment
"recheck trove" or "recheck designate" in PRs.
=> Add two jobs for Trove/Designate related tests

openstack/resource_openstack_compute_floatingip_associate_v2_test.go, openstack/resource_openstack_compute_instance_v2_test.go, openstack/resource_openstack_compute_servergroup_v2_test.go, openstack/resource_openstack_compute_volume_attach_v2_test.go
If there are multiple private networks can be used in current tenant,
that cause booting instance failed, because Nova have no idea about
using which network to create instance. Propose to use OS_NETWORK_ID as
default network to create instance in order to avoiding failing in Acc
tests. Only fix Acc tests, no impact to behavior of booting instance,
keep backward compatibility.
Fixes #213
=> Use OS_NETWORK_ID as default network in Acc tests

openstack/data_source_openstack_compute_flavor_v2.go, openstack/data_source_openstack_compute_flavor_v2_test.go, openstack/provider.go, website/docs/d/compute_flavor_v2.html.markdown, website/openstack.erb
This commit adds the `openstack_compute_flavor_v2` data source
which enables querying of OpenStack flavors.
Attributes such as ephemeral and "extra" fields are not yet
supported as they need to be added upstream.
Fixes #187
=> Compute v2: Flavor Data Source

website/docs/r/compute_flavor_v2.html.markdown
Flavors are properly documented as configuring RAM in megabytes, but the example is not really useful (unless you have an image that can boot with only 8 MB).
I think the intent was to show 8096... but some value of at least 2048 MB should be copy/pasteable for the average user's image.
=> usable examlpe of compute_flavor_v2

openstack/config.go
This commit will set the region name if one is provided
in the clouds.yaml entry and the user did not specify
one in the provider configuration. If the user set one
in the provider, it will override what is set in
clouds.yaml.
Fixes #215
=> Set region if defined in clouds.yaml

openstack/resource_openstack_lb_member_v2.go, website/docs/r/lb_member_v2.html.markdown
Fixes #188 
All signs point to this being correct. It's not required in Gophercloud. In Terraform, we're even checking to see if it's set as if it was an optional parameter:
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_lb_member_v2.go#L111-L114
=> LBaaSv2: Make subnet_id for members optional

openstack/resource_openstack_db_instance_v1.go
This PR marks user's password as sensitive and addresses https://github.com/terraform-providers/terraform-provider-openstack/issues/141
=> set password to sensitive

openstack/data_source_openstack_compute_flavor_v2_test.go
There's more than one flavor being returned in the query results.
=> Compute v2: Fixing flavor data source acceptance test

openstack/resource_openstack_compute_instance_v2.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go, vendor/vendor.json
This pull request updates the Gophercloud schedulerhints extension to the latest version. The latest version includes the ability to specify arbitrary key/value strings for scheduler hints as specified by this pull request [gophercloud/gophercloud#316]. 
This pull request enables the ability to specify such KV pairs in terraform.
=> Arbitrary Key/Value for Schedule Hints

openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_router_v2_test.go, website/docs/r/networking_router_v2.html.markdown
Add a `vendor_options` param to `openstack_networking_router_v2` resource.
This will enable management of 'vendor specific' behaviour in a
sensible, structured manner.
TODO:
=> Add 'vendor_options' to networking_router_v2 resource.

openstack/data_source_openstack_identity_role_v3.go, openstack/data_source_openstack_identity_role_v3_test.go, openstack/import_openstack_identity_role_v3_test.go, openstack/provider.go, openstack/resource_openstack_identity_role_v3.go, openstack/resource_openstack_identity_role_v3_test.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/roles/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/roles/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/roles/results.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/roles/urls.go, vendor/vendor.json, website/docs/d/identity_role_v3.html.markdown, website/docs/r/identity_role_v3.html.markdown, website/openstack.erb
Adds `openstack_identity_role_v3` data source & resource.
See #248 for more information (this PR contains part of the content that was initially proposed there).
Docs are still missing.
=> Add data source and resource for roles

openstack/import_openstack_networking_port_v2_test.go, openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_port_v2_test.go
This commit fixes a regression caused in #168.
This fix should now allow a user to both specify and omit a MAC
address when creating an allowed_address_pair and have the state
not require further changes. It should also allow importing of
ports with allowed_address_pairs to continue working.
Fixes #232
=> Networking v2: Fix allowed_address_pairs

openstack/resource_openstack_compute_flavor_v2.go, openstack/resource_openstack_compute_flavor_v2_test.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/urls.go, vendor/vendor.json, website/docs/r/compute_flavor_v2.html.markdown
This commit adds extra_specs to the openstack_compute_flavor_v2
resource.
Fixes #165
=>  Compute v2: Add extra_specs to flavors 

openstack/resource_openstack_networking_floatingip_v2.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go, vendor/vendor.json, website/docs/r/networking_floatingip_v2.html.markdown
This commit allows the user to specify a subnet_id when creating
a floating IP. This is useful if the floating IP network contains
multiple subnets.
Fixes #229
=>  Networking v2: Add subnet_id to floatingip resource

openstack/data_source_openstack_images_image_v2.go, openstack/resource_openstack_images_image_v2.go, website/docs/d/images_image_v2.html.markdown
To get ID of a shared image we need to filter with member_status = all
Documentation:
https://specs.openstack.org/openstack/glance-specs/specs/api/v2/sharing-image-api-v2.html#list-shared-images
```
visibility=shared&member_status=all: show all images shared with me regardless of my member status
```
It's a mandatory feature if image was shared with your tenant and you only know the name.
=> Filter image with  MemberStatus field

openstack/data_source_openstack_identity_project_v3.go, openstack/data_source_openstack_identity_project_v3_test.go, openstack/provider.go, website/docs/d/identity_project_v3.html.markdown, website/openstack.erb
Adds data source `openstack_identity_project_v3`.
See #248 for more information (this PR contains part of the content that was initially proposed there).
Tests & docs are still missing.
=> Add project data source

openstack/resource_openstack_objectstorage_container_v1.go, website/docs/r/objectstorage_container_v1.html.markdown
Add `force_destroy` support for resource `openstack_objectstorage_container_v1`.
For: #274 
Signed-off-by: Swapnil Mhamane <swapnilgmhamane@gmail.com>
=> Support force destroy of object store container

openstack/data_source_openstack_identity_user_v3.go, openstack/data_source_openstack_identity_user_v3_test.go, openstack/provider.go, website/docs/d/identity_user_v3.html.markdown, website/openstack.erb
Adds data source `openstack_identity_user_v3`.
See #248 for more information (this PR contains part of the content that was initially proposed there).
Tests & docs are still missing.
=> Add user data source

openstack/provider.go, openstack/resource_openstack_identity_role_assignment_v3.go, openstack/resource_openstack_identity_role_assignment_v3_test.go, website/docs/r/identity_role_assignment_v3.html.markdown, website/openstack.erb
Adds resource openstack_identity_role_assignment_v3.
See #248 for more information (this PR contains part of the content that was initially proposed there).
Tests & docs are still missing.
=> Add role assignment resource

openstack/data_source_openstack_images_image_v2.go, openstack/types.go, vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imagedata/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imagedata/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imagedata/results.go, vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go, vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go, vendor/vendor.json
This PR updates the Gophercloud library for handling images. This might help #289, but I'm not sure yet.
If it doesn't, I have modified the debug logger to not print non-JSON requests. This will prevent the binary output from being logged when uploading images which will help with debugging this issue further.
=> Image v2: Vendor Update and Logging Fix

openstack/import_openstack_vpnaas_service_v2_test.go, openstack/provider.go, openstack/resource_openstack_vpnaas_service_v2.go, openstack/resource_openstack_vpnaas_service_v2_test.go, openstack/types.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/services/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/services/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/services/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/services/urls.go, vendor/vendor.json, website/docs/r/vpnaas_service_v2.html.markdown, website/openstack.erb
Part 2 of a series that addresses #2
=> Vpnaas: VPN service resource

openstack/import_openstack_networking_subnet_route_v2_test.go, openstack/provider.go, openstack/resource_openstack_networking_subnet_route_v2.go, openstack/resource_openstack_networking_subnet_route_v2_test.go, openstack/resource_openstack_networking_subnet_v2.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go, vendor/vendor.json, website/docs/r/networking_subnet_route_v2.html.markdown, website/openstack.erb
Currently, it's not easy to manage multiple routes on a single subnet. 
This resource splits the route management out into a separate resource that can easily be iterated over. 
TODO:
=> Add openstack_networking_subnet_route_v2 resource

openstack/resource_openstack_fw_firewall_v1_test.go, openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_router_v2_test.go
This commit fixes the "distributed" argument for the
openstack_networking_router_v2 resource so that the value of
"false" is passed correctly.
"distributed" is removed from all acceptance tests since it is
now being passed correctly in the request body and this setting
is very dependent upon the testing environment configuration.
Fixes #285
=> Networking v2: Fix router distributed argument

openstack/resource_openstack_networking_router_v2.go
This commit fixes the "enable_snat" argument in the
openstack_networking_router_v2 resource so that a value
of "false" is passed correctly.
Depends on #308 
Fixes #280
=> Networking v2: Fix router enable_snat argument

openstack/lb_v2_shared.go
This commit lowers the delays for the load balancer resources
while waiting for a certain state. For the LoadBalancer resource
in particular, the delay is set to 0.
Fixes #295 
I tested setting all delays to 0 and everything worked, but I want to be cautious here. #295 specifically requested the load balancer delay to be set to 0, so I've implemented that. For everything else, I've lowered it to 1 second.
=> LBaaS v2: Lower Delays for Load Balancer Resources

openstack/resource_openstack_networking_router_v2_test.go
`enable_snat` and `external_fixed_ip`
This PR ensures that `set_router_gateway_after_create` (`vendorUpdateGateway`) is handled properly together with `enable_snat` and `external_fixed_ip`.
It prevents a panic described in #317 
Fixes #317
=> Neutron router_v2 add test testAccNetworkingV2Router_vendor_opts_no_snat

openstack/import_openstack_compute_floatingip_associate_v2_test.go, openstack/resource_openstack_compute_floatingip_associate_v2.go, openstack/resource_openstack_compute_floatingip_associate_v2_test.go, website/docs/r/compute_floatingip_associate_v2.html.markdown
This commit adds the wait_until_associated argument to the
openstack_compute_floatingip_associate_v2 resource. This is useful
in environments where the OpenStack environment won't automatically
wait for the floating IP association to finish before returning.
Use this option to instead have Terraform wait until the association
has finished.
Fixes #88
=> Compute v2: Add wait_until_associated to floating IP association

openstack/resource_openstack_images_image_v2.go
This commit allows an explicit value of 0 to be set for the
openstack_images_image_v2 min_disk_gb and min_ram_mb arguments.
Fixes #341
=> Images v2: Allow 0 Values for arguments

openstack/resource_openstack_vpnaas_site_connection.go, website/docs/r/vpnaas_site_connection_v2.html.markdown
Hello,
First a big thanks to @simonre for his work on vpnaas.
I noticed two things : 
- peer_ep_group_id should be optional in order to respect the [Openstack API](https://developer.openstack.org/api-ref/network/v2/index.html#create-ipsec-connection). It's currently impossible to specify only peer_cidrs when you have a VPN service with a subnet 
- a minor nitpick inside documentation (Optional inside the schema but Required in the documentation).
Regards
=> Switch peer_ep_group_id to Optional and documentation fix

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_network_v2_test.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/external/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/external/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/external/results.go, vendor/vendor.json, website/docs/r/networking_network_v2.html.markdown
Add "router:external" OpenStack Networking service attribute to the resource_openstack_networking_network_v2.
Add tests for create and update of network with that attribute.
For #356
=> Networking V2: support external network resource

openstack/compute_instance_v2_networking.go
Currently when an instance has no "network" blocks it's assumed it will
connect to the default network, worked out by inspecting the instance
addresses and taking the network name from that. This doesn't return the
network uuid, but the first refresh will pick the uuid up because the
resource now has a network block (with the default network name).
This commit simply copies some of the logic used in
getAllInstanceNetworks to work out network uuids from network names to
do the same with the default network name. Thus instances have a full
network block returned with name and uuid on create.
=> Return the default network uuid on instance create

openstack/data_source_openstack_networking_network_v2.go, openstack/data_source_openstack_networking_network_v2_test.go, vendor/github.com/gophercloud/gophercloud/results.go, vendor/vendor.json, website/docs/d/networking_network_v2.html.markdown
Add "router:external" OpenStack Networking service attribute to the data_source_openstack_networking_network_v2
Add tests for datasource network with that attribute.
For #356
=> Networking V2: support external network datasource

openstack/resource_openstack_networking_floatingip_v2.go, website/docs/r/networking_floatingip_v2.html.markdown
Since a load balancer is often the entry point to the rest of your infrastructure it's common to use a stable/fixed IP as the VIP of your load balancer. The OpenStack REST API supports this, but the Terraform OpenStack provider currently doesn't. 
This PR adds the ability to obtain a _specific_ networking floating IP from the pool in order to associate it with the VIP of a load balancer. E.g:
```
resource "openstack_networking_floatingip_v2" "https_lb_float_ip" {
pool = "mypool"
address = "192.0.2.0"
}
```
Also credits to @jagter for helping out with this PR.
=> Allow one to obtain a specific floating IP to associate with a loadbalancer

openstack/resource_openstack_lb_pool_v2.go, website/docs/r/lb_pool_v2.html.markdown
Hello,
I want to create lbaas pool with PROXY protocol on Octavia. But terraform output following error message:
Error: openstack_lb_pool_v2.octavia_test: Only 'TCP', 'HTTP', and 'HTTPS' are supported values for 'protocol'
Octavia lbaas pool support PROXY protocol since API 1.0 (Release Pike), so I allow to specify PROXY.
reference:
- https://developer.openstack.org/api-ref/load-balancer/v2/#create-pool
Thanks!
=> Allow proxy procotol on lb pool v2

openstack/data_source_openstack_identity_endpoint_v3.go, openstack/data_source_openstack_identity_endpoint_v3_test.go, openstack/provider.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/endpoints/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/endpoints/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/endpoints/results.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/endpoints/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/services/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/services/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/services/results.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/services/urls.go, vendor/vendor.json, website/docs/d/identity_endpoint_v3.html.markdown, website/openstack.erb
Allow for getting endpoint's data from the catalog. This is useful to
get public URL's that needed for inter-service communication in the
cloud.
/cc @jtopjian
=> Add data openstack_identity_endpoint_v3

openstack/resource_openstack_objectstorage_object_v1.go, vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/results.go, vendor/vendor.json
Gophercloud now allows the etag to be specified and omitted. This caused
the openstack_objecstorage_object_v1 resource to break because it was
sending the old etag with new content. This commit fixes this by
creating a separate Update function and conditionally sending the etag.
This should not break existing deployments.
Related to: #359 
/cc @yanndegat
=> Object Storage v1: ETag Changes

openstack/config.go, openstack/provider.go, website/docs/index.html.markdown
This commit adds support for `default_domain`, similar to the
`--os-default-domain` and `OS_DEFAULT_DOMAIN` arguments with the
OpenStack CLI. If omitted, a default value of `domain` is used,
which also matches the CLI behavior.
=>  Add support for default_domain

openstack/data_source_openstack_networking_network_v2.go, openstack/data_source_openstack_networking_network_v2_test.go
For #382 
#358 added support for querying networks by using the "external"
argument. However, this caused results to either contain only external
networks or only non-external networks.
This fixes the behavior to only query with the "external" argument if
it is explicitly defined in the Terraform configuration.
The introduction of the "external" Gophercloud package extracted the
network results in a new way. This new method did not safely handle
results which did not contain any networks.
=> Networks v2: Network Data Source Fixes

openstack/resource_openstack_compute_floatingip_associate_v2.go
When upgrading to a new version of the OpenStack provider, the new
`wait_until_associated` argument was causing a rebuild due to the
default value of "false" being applied.
This commit reverses that behavior.
Fixes #391 
/cc @xocasdashdash
=> Compute v2: Prevent rebuild of floating IP association during upgrade

openstack/data_source_openstack_fw_policy_v1.go, openstack/data_source_openstack_fw_policy_v1_test.go, openstack/provider.go, website/docs/d/fw_policy_v1.html.markdown, website/openstack.erb
This commit adds a data source for `openstack_fw_policy_v1` resources.
This is useful to refer to a policy ID on creation of a `openstack_fw_firewall_v1 `.
=> Add firewall policy data source

openstack/resource_openstack_compute_floatingip_associate_v2_test.go
This test regularly fails in our CI environment for unknown reasons.
Testing locally has always been successful.
=> Compute v2: Remove Attach to Second Network Test

website/docs/r/compute_volume_attach_v2.html.markdown
Fixes #406
Using "element()" makes all attachments get
destroyed and re-created when the count
is increased. This is fixed by using the "[]"
syntax instead as explained here:
https://github.com/hashicorp/terraform/issues/3449
=> Updated syntax to use "[]" instead of "element()"

openstack/provider.go, openstack/resource_openstack_objectstorage_tempurl_v1.go, openstack/resource_openstack_objectstorage_tempurl_v1_test.go, website/docs/r/objectstorage_tempurl_v1.html.markdown, website/openstack.erb
Arguably, TempUrls could be considered a resource. However, they do not
exist in the server, they cannot be updated, and they cannot be
deleted. This type of resource can only be generated and it has a
limited lifetime. Therefore, this has been implemented as a datasource.
Given a container name and an object name, it'll be possible to create
a tempurl for that object and store it as a data source.
/cc @jtopjian
=> Add resource for creating Swift tempurls

openstack/resource_openstack_objectstorage_tempurl_v1.go, website/docs/r/objectstorage_tempurl_v1.html.markdown
This commit adds the `regenerate` argument to the
`openstack_objectstorage_tempurl_v1` resource. This allows users to
opt-in to having the resource automatically regenerate when the
temporary URL has expired.
=>  Object Storage v1: Add regenerate to temp url resource 

openstack/config.go, openstack/import_openstack_containerinfra_clustertemplate_v1_test.go, openstack/provider.go, openstack/provider_test.go, openstack/resource_openstack_containerinfra_clustertemplate_v1.go, openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go, openstack/util.go, vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/results.go, vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/urls.go, vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go, vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go, vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go, vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go, vendor/github.com/hashicorp/terraform/helper/validation/validation.go, vendor/vendor.json, website/docs/r/containerinfra_clustertemplate_v1.html.markdown, website/openstack.erb
Add resource to manage OpenStack Magnum cluster templates.
Add common resourceLinks() function to unmarhal slice of gophercloud.Links to a slice of maps.
For #402
Some links:
[Constraints for the `apiserver_port`](https://github.com/openstack/magnum/blob/stable/queens/magnum/api/controllers/v1/cluster_template.py#L82)
[Requirement of the `coe`](https://github.com/openstack/magnum/blob/stable/queens/magnum/api/controllers/v1/cluster_template.py#L50)
[Requirement of the `image`](https://github.com/openstack/magnum/blob/stable/queens/magnum/api/controllers/v1/cluster_template.py#L53)
=> ContainerInfraV1: add Cluster template resource

website/docs/r/networking_router_interface_v2.html.markdown
According to the docs: Deprecated - use external_network_id instead
https://www.terraform.io/docs/providers/openstack/r/networking_router_v2.html#external_gateway
=> Replace deprecated external_gateway

openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_networking_router_v2.go, openstack/util.go, website/docs/r/compute_instance_v2.html.markdown
Add "vendor_options" map attribute for instance with the
"ignore_resize_confirmation" option.
New option can be used to ignore manual confirmation of the Compute
instance resizing. Some OpenStack cloud providers automatically confirm
resizing of instances after configured timeout.
For #420
=> ComputeV2: add instance vendor_options

openstack/resource_openstack_compute_instance_v2.go
This commit will allow an instance to cleanly transition into a
status of "error". This will allow users to destroy instances
which have changed into an error state either during creation
or by some event outside of Terraform.
For #404 
Additional comments in #427
=> Compute v2: Allow power_state of error

.zuul.yaml
Input comment "recheck stable/rocky" in pull request comments, that
will trigger acceptance tests against OpenStack Rocky release. OpenLab
will report test result in followint comments automatically.
=> Support acceptance test against OpenStack Rocky release in OpenLab

openstack/compute_instance_v2_networking.go
This change fixes the server network's fixed IP addresses appearing blank in the resource output because the [rackspace servers api](https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#show-server-details) doesn't return the `OS-EXT-IPS:type` field in the `addresses` list items, e.g.:
{
"server": {
"OS-DCF:diskConfig": "AUTO",
"OS-EXT-STS:power_state": 1,
"OS-EXT-STS:task_state": null,
"OS-EXT-STS:vm_state": "active",
"accessIPv4": "198.101.241.238",
"accessIPv6": "2001:4800:780e:0510:d87b:9cbc:ff04:513a",
"addresses": {
"private": [
{
"addr": "10.180.3.171",
"version": 4
}
],
"public": [
{
"addr": "198.101.241.238",
"version": 4
},
{
"addr": "2001:4800:780e:0510:d87b:9cbc:ff04:513a",
"version": 6
}
],
"production": [
{
"addr": "192.168.21.30", …
=> Handle rackspace server addresses without type

openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_port_v2_test.go, website/docs/r/networking_port_v2.html.markdown
This commit adds the `no_fixed_ip` argument to the
openstack_networking_port_v2 resource which will enable a port to
be created without a Fixed IP address set.
For #429
=> Networking v2: Add no_fixed_ip to openstack_networking_port_v2

openstack/resource_openstack_dns_recordset_v2.go, openstack/resource_openstack_dns_recordset_v2_test.go
This commit will format IPv6 records in a way that the DNSaaS /
Designate service expects them to be. Notably, it strips the brackets
from the addresses.
Passing IPv6 records with brackets already removed still works.
For #337
=> DNSv2: Format IPv6 Records

website/docs/r/lb_monitor_v1.html.markdown
expected_codes argument description is missing the 'R' in Required
=> expected_codes argument description typo

openstack/resource_openstack_compute_volume_attach_v2.go, website/docs/r/compute_volume_attach_v2.html.markdown
This commit allows instances to attach multiattach volumes
by adding a new argument called "multiattach". When set, the
compute client will use Microversion 2.60, which enables multiattach
support in the Compute/Nova API.
For #432 
@jamesmmccarthy I'm unable to test multiattach volumes at the moment, so I'm not sure if this works. Would you be able to give it a try? I've updated the documentation to include an example implementation, though I'm not sure if it's correct.
=> Compute v2: Enable Multiattach Volumes

openstack/resource_openstack_identity_project_v3_test.go, openstack/resource_openstack_identity_role_v3_test.go, openstack/resource_openstack_identity_user_v3_test.go
Because OpenLab doesn't run with an admin account, these errors slipped by.
The resources themselves are fine.
=> Identity v3: Acceptance test fixes

openstack/import_openstack_compute_flavor_access_v2_test.go, openstack/provider.go, openstack/resource_openstack_compute_flavor_access_v2.go, openstack/resource_openstack_compute_flavor_access_v2_test.go, website/docs/r/compute_flavor_access_v2.html.markdown, website/openstack.erb
This PR adds `access` attribute to flavor resource. `access` contains list of tenant ids that are allowed to use flavor.
EDIT: create `openstack_compute_flavor_access_v2` instead of access list in flavor resource.
=> Allow to specify flavor access for tenants

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_network_v2.html.markdown, website/docs/r/networking_subnet_v2.html.markdown
This adds support for tags to subnets note this is branched from PR #454 
Subsequent PRs will add support for the other neutron resources which support standard attribute tags as described in Issue #453
Issue #453
=> Add tags support for Neutron Subnets

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_network_v2.html.markdown
This adds support for tags to networks, note this is branched from PR #446 since that already adds initial support for tags for the trunk resource, and a couple of functions are reused here.
Subsequent PRs will add support for the other neutron resources which support standard attribute tags as described in Issue #453 
Issue #453
=> Add tags support for Neutron Networks

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_secgroup_v2.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnetpool_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_network_v2.html.markdown, website/docs/r/networking_port_v2.html.markdown, website/docs/r/networking_secgroup_v2.html.markdown, website/docs/r/networking_subnet_v2.html.markdown, website/docs/r/networking_subnetpool_v2.html.markdown
This adds support for tags to security groups note this is branched from PR #462
Subsequent PRs will add support for the other neutron resources which support standard attribute tags as described in Issue #453
Issue #453
=> Add tags support for Neutron Security Groups

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnetpool_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_network_v2.html.markdown, website/docs/r/networking_subnet_v2.html.markdown, website/docs/r/networking_subnetpool_v2.html.markdown
This adds support for tags to subnetpools note this is branched from PR #459 
Subsequent PRs will add support for the other neutron resources which support standard attribute tags as described in Issue #453
Issue #453
=> Add tags support for Neutron Subnetpools

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnetpool_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_network_v2.html.markdown, website/docs/r/networking_port_v2.html.markdown, website/docs/r/networking_subnet_v2.html.markdown, website/docs/r/networking_subnetpool_v2.html.markdown
This adds support for tags to ports note this is branched from PR #460
Subsequent PRs will add support for the other neutron resources which support standard attribute tags as described in Issue #453
Issue #453
=> Add tags support for Neutron Ports

openstack/resource_openstack_networking_floatingip_v2.go, openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_floatingip_v2.html.markdown, website/docs/r/networking_router_v2.html.markdown
This adds support for tags to routers
Issue #453
=> Add tags support for Neutron Routers

openstack/resource_openstack_networking_floatingip_v2.go, openstack/resource_openstack_networking_tags_v2_test.go, website/docs/r/networking_floatingip_v2.html.markdown
This allows us to set/get tags for floatingips via terraform templates,
and requires the recently added changes to gophercloud that enable
the relevant features of the Neutron APIs to be accessed.
Issue: #453
=> Add tags support for Neutron floatingips

openstack/compute_secgroup_v2.go, openstack/compute_secgroup_v2_test.go, openstack/resource_openstack_compute_secgroup_v2.go, openstack/resource_openstack_compute_secgroup_v2_test.go
For #456 
This one can probably use more refactoring, but I didn't want to make too many changes for fear of breaking something. 
For example, `computeV2SecGroupRulesCheckForErrors` _might_ work as a validation function in the schema. As well, `flattenComputeV2SecGroupRules` might have room for changes.
=> Internal: compute v2 secgroup cleanup

openstack/data_source_openstack_compute_keypair_v2.go, openstack/data_source_openstack_compute_keypair_v2_test.go, website/docs/d/compute_keypair_v2.html.markdown
=> Compute v2: Adding fingerprint to keypair data source

openstack/compute_instance_v2_networking.go
Some OpenStack implementations (for instance, at my company) do not
allow the use of the os-tenant-networks API call. This causes a fatal
error when trying to read from an `openstack_compute_instance_v2`
resource. However, this error is not actually fatal as these properties
are not required for destruction. This PR changes the functionality of
the resource to reflect that.
Most of this code was actually removed during the refactor in #39, but it doesn't appear intentional. Hopefully we can bring this back with minimal impact to others.
Fixes #95
=> Make the tenantnetworks API not required

openstack/resource_openstack_objectstorage_container_v1.go, website/docs/r/objectstorage_container_v1.html.markdown
To enable versioning, we must set a HTTP header `X-History-Location` or `X-Versions-Location` while creating or updating the container (cf: [Openstack documentation](https://docs.openstack.org/swift/latest/overview_object_versioning.html)).
This PR adds support of both headers.
=> Enable object versioning

openstack/compute_servergroup_v2.go, openstack/compute_servergroup_v2_test.go, openstack/resource_openstack_compute_servergroup_v2.go, openstack/resource_openstack_compute_servergroup_v2_test.go, website/docs/r/compute_servergroup_v2.html.markdown
Set "2.15" microversion for servergroup "soft-anti-affinity" and "soft-affinity" policies.
Add tests and documentation notes.
For #118
=> ComputeV2: add soft policies

openstack/resource_openstack_compute_instance_v2.go
When applying changes, we have regularly received the error `Invalid power_state for instance <ID>: MIGRATING` , as live migrations occur on instances, preventing any plan / apply operations.
This change adds "migrating" to the list of acceptable states for an instance to be in. See also #428
=> Allow a VM to be in a state of 'migrating'

openstack/data_source_openstack_blockstorage_snapshot_v2.go, openstack/data_source_openstack_blockstorage_snapshot_v2_test.go, openstack/data_source_openstack_blockstorage_snapshot_v3.go, openstack/data_source_openstack_blockstorage_snapshot_v3_test.go, openstack/provider.go, openstack/provider_test.go, openstack/types.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/results.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/util.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/results.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/util.go, vendor/vendor.json, website/docs/d/blockstorage_snapshot_v2.html.markdown, website/docs/d/blockstorage_snapshot_v3.html.markdown, website/openstack.erb
For #354 
There are two resources here, but they are almost identical - the only difference is v2 / v3.
The acceptance tests are done uniquely from other tests: a volume and snapshot are created outside of Terraform. This is because Terraform doesn't have an `openstack_blockstorage_snapshot_v2/3` resource, which makes sense because creating and managing snapshots is a hard thing for Terraform to do.
=> Block Storage Snapshot Data Sources

openstack/networking_port_v2.go, openstack/networking_port_v2_test.go, openstack/resource_openstack_networking_port_v2.go
Move all Networking port V2 allowed pairs related code into networking_port_v2.go and provide tests to new functions.
Use testify/assert for networking_port_v2_test.go.
For #456, #458
=> Internal: port allowed address pairs cleanup

openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_listener_v2_test.go, openstack/resource_openstack_lb_loadbalancer_v2.go, website/docs/r/lb_listener_v2.html.markdown
=> LBaaS: Allow LB listener default pool update without the listener re-creation

openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_router_v2_test.go, website/docs/r/networking_router_v2.html.markdown
=> Networking V2: add description to the router resource

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go
This PR allows terraform to interrupt the apply process if the LB is in ERROR state.
Part of the #546
=> LBaaSv2: Improve LB objects' checks

openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2_test.go, openstack/resource_openstack_containerinfra_cluster_v1.go
For #548 
It appears that Terraform v0.12 won't use DefaultFunc when the field is
set to computed. While this might be a bug, we only have a few
occurrences of this in the provider, so I'm opting to work around this
instead of reporting it upstream and possibly have a legacy measure put
in place.
This commit will have the flavors still use the correct environment
variables. Detection is just deferred to outside the schema.
In addition, I made an update to the compute instance test fixtures so they work in v0.12.
@ozerovandrei These changes probably conflict with #545, but this PR should take priority. I will resolve any conflicts with #545 afterwards.
=> Provider: Fix flavor detection

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go, vendor/github.com/gophercloud/gophercloud/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/results.go, vendor/vendor.json
Part of #546
@jtopjian, please watch your eyes :) This is the best what I could do to detect proper statuses. With this PR, situation described in #546 won't happen. Terraform will update LB objects independently on the LB overall status.
This PR is based on #547, so take a look on the second commit. It also depends on https://github.com/gophercloud/gophercloud/pull/1367
My gut feeling says that there could be pitfalls, let's wait for tests.
=> LBaaSv2: Detect individual LB object statuses, don't rely on LB status

openstack/containerinfra_shared_v1_test.go
This fix resolves an issue where the actual labels are in a different
order than the expected labels, due to iterating over a map.
The long-term fix might be to sort the keys in
expandContainerInfraV1LabelsString, but this will need some work as it
would be a breaking change.
=> Internal: Fix expandContainerInfraV1LabelsString unit test

openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2_test.go, website/docs/r/compute_instance_v2.html.markdown
Add "device_type" and "disk_bus" fields into the "block_device"
attribute of the Compute V2 Instance resource.
Provide basic acceptance test and documentation.
For #18
=> ComputeV2: add "device_type" and "disk_bus" fields

openstack/import_openstack_sharedfilesystem_share_access_v2_test.go, openstack/import_openstack_sharedfilesystem_share_v2_test.go, openstack/provider.go, openstack/resource_openstack_sharedfilesystem_share_access_v2.go, openstack/resource_openstack_sharedfilesystem_share_access_v2_test.go, openstack/resource_openstack_sharedfilesystem_share_v2.go, openstack/resource_openstack_sharedfilesystem_share_v2_test.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/errors/errors.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/results.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/urls.go, vendor/vendor.json, website/docs/r/sharedfilesystem_share_access_v2.html.markdown, website/docs/r/sharedfilesystem_share_v2.html.markdown, website/openstack.erb
=> Manila: add share acl resource

openstack/data_source_openstack_networking_network_v2.go, openstack/data_source_openstack_networking_network_v2_test.go, vendor/vendor.json, website/docs/d/networking_network_v2.html.markdown
Add the "transparent_vlan" attribute into networking_network_v2 datasource.
For #430
=> NetworkingV2: add transparent_vlan network datasource attribute 

openstack/data_source_openstack_networking_port_v2.go, openstack/data_source_openstack_networking_port_v2_test.go, openstack/lb_v2_shared.go, openstack/provider.go, openstack/util.go, website/docs/d/networking_port_v2.html.markdown, website/openstack.erb
=> Networking: add port data source

openstack/networking_floatingip_v2.go, openstack/resource_openstack_networking_floatingip_associate_v2.go, openstack/resource_openstack_networking_floatingip_associate_v2_test.go
Move Networking V2 floating IP helpers functions outside of
resource_openstack_networking_floatingip_associate_v2.go.
Update debug and error messages.
For #456
=> Internal: Floating IP associate cleanup

openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_port_v2_test.go
If "admin_state_up" is not specified in the API request, then the port
should default to an admin_state_up of "UP".
Currently, this resource will always send a value of "false", even if
the user did not specify it in their resource configuration.
This commit fixes this behavior.
For #588
=> Networking v2: Fix Port admin_state_up behavior

openstack/resource_openstack_compute_flavor_v2.go, openstack/resource_openstack_compute_floatingip_v2.go, openstack/resource_openstack_compute_keypair_v2.go, openstack/resource_openstack_compute_secgroup_v2.go, openstack/resource_openstack_compute_servergroup_v2.go, openstack/resource_openstack_dns_recordset_v2.go, openstack/resource_openstack_dns_zone_v2.go, openstack/util.go
This commit adds the resource ID to all CheckDeleted error messages for
easier detection of what resource the error came from.
It also adds CheckDeleted to the Delete function of missing resources
which have already gone through the cleanup process.
/cc @kayrus
=> Internal: Add ID to CheckDeleted

openstack/resource_openstack_sharedfilesystem_share_access_v2.go, openstack/resource_openstack_sharedfilesystem_share_v2.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/messages/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/messages/results.go, vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/messages/urls.go, vendor/github.com/gophercloud/gophercloud/provider_client.go, vendor/vendor.json
Depends on https://github.com/gophercloud/gophercloud/issues/1400
Resolves #565
@jtopjian please review
an example message returned by `terraform apply`:
> Error: Error applying plan:
> 1 error(s) occurred:
> openstack_sharedfilesystem_share_v2.cifs: 1 error(s) occurred:
> openstack_sharedfilesystem_share_v2.cifs: Error waiting for share 37f7ab0d-6831-4538-ba8a-4ba5ca220e45 to become available: unexpected state 'error', wanted target 'available'. last error: %!s(<nil>): the latest manila message (2019-01-12 14:26:55.608715 +0000 UTC): create: Could not find an existing share server or allocate one on the share network provided. You may use a different share network, or verify the network details in the share network and retry your request. If this doesn't work, contact your administrator …
=> Manila: introduce manila messages for detailed share errors

openstack/compute_instance_v2_networking.go
At the time of the panic, the Compute API did not return any addresses
of the instance. This might have been a transient error, but even if so,
we should ensure proper checks are in place to prevent such panics.
Fixes #506
=> Compute v2: Fix Instance NIC indexing

website/openstack.erb
`openstack_` caption prefix was forgotten. Fortunately the links are ok.
=> Manila: fix doc captions

openstack/data_source_openstack_networking_port_ids_v2.go, openstack/data_source_openstack_networking_port_v2.go, openstack/networking_port_v2.go, openstack/networking_port_v2_test.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_networking_port_v2.go, openstack/util.go
Add StateRefreshFunc(), expandNetworkingPortFixedIpsV2 into the
"networking_port_v2.go".
Change "fixed_ip" argument type to "TypeSet".
Use "expandToStringSlice()" function to retrieve "security_groups"
value. This change also affects "openstack_lb_loadbalancer_v2" resource
code.
Add common "boolPtrArgument()" into "util.go" to work with some special
arguments like "admin_state_up".
Fix debug and error messages.
For #456
=> Internal: cleanup Networking V2 Ports

openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_network_v2_test.go
openstack_networking_network_v2 was originally created with the fields
"admin_state_up" and "shared" as TypeString. This was to work around
Terraform mistaking an omitted boolean argument as "false".
Now that `GetOkExists` is available, we can correctly account for this
case.
This commit changes these two fields to TypeBool while still retaining
the prior behavior that TypeString was working around.
For #548
=> Networking v2: Fix boolean fields of network resource

openstack/resource_openstack_lb_l7policy_v2.go, openstack/resource_openstack_lb_l7rule_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_pool_v2.go, openstack/resource_openstack_sharedfilesystem_share_access_v2.go
Fix unkeyed fields for schema.ResourceImporter of the OpenStack LB and
Shared filesystem resources.
=> Vet: fix unkeyed fields for importers

openstack/networking_trunk_v2.go, openstack/networking_trunk_v2_test.go, openstack/resource_openstack_networking_trunk_v2.go, website/docs/r/networking_trunk_v2.html.markdown
Use extend and flatten functions for work with the trunk "sub_port"
argument/attribute.
Provide a single resource.StateRefreshFunc for the trunk resource.
Update debug messages for the trunk resource.
Fix "openstack_networking_trunk_v2" website documentation.
=> Internal: Networking V2 Trunk resource cleanup

openstack/dns_recordset_v2.go, openstack/dns_recordset_v2_test.go, openstack/resource_openstack_dns_recordset_v2.go, website/docs/r/dns_recordset_v2.html.markdown
For #627 
This commit fixes an issue where the records attribute in the
`openstack_dns_recordset_v2` resource would sometimes be returned in a
different order than what the user specified.
The hardest part about implementing this fix is managing the internal
feature of removing brackets from IPv6 addresses.
In order to successfully continue removing the brackets as well as
retain backwards compatibility, the following changes were made:
1. The `records` field is no longer being set in the Read function. This
is because the `records` field is not computed, so it does not need to
be set during Read.
2. An import function has been created so `records` is set when a user
imports a recordset.
3. `DiffSuppressFunc` has been replaced with a `StateFunc`. Because
`records` is no longer being set …
=> DNS v2: Fix recordset diffs

openstack/import_openstack_networking_addressscope_v2_test.go, openstack/networking_addressscope_v2.go, openstack/provider.go, openstack/resource_openstack_networking_addressscope_v2.go, openstack/resource_openstack_networking_addressscope_v2_test.go, openstack/types.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go, vendor/vendor.json, website/docs/r/networking_addressscope_v2.html.markdown, website/openstack.erb
Add "openstack_networking_addressscope_v2" resource with acceptance and importing test.
Add website documentation for the addressscope_v2 resource.
For #364
=> Networking V2: add Address-scope resource

openstack/identity_user_v3_test.go, openstack/import_openstack_compute_interface_attach_v2_test.go, openstack/resource_openstack_compute_instance_v2.go
=> Compute V2: Don't fail on delete, when compute instance doesn't exist

openstack/resource_openstack_blockstorage_volume_v1.go, openstack/resource_openstack_blockstorage_volume_v2.go, openstack/resource_openstack_blockstorage_volume_v3.go
For #639 
Amending #640, we shouldn't use CheckDeleted for the volume detach
portion since CheckDeleted will remove the resource from state. Instead,
we should just consider a 404 an acceptable error and continue.
Too many Deletes and CheckDelete on my mind.
=> Block Storage v2: Fix volume detachment 404s

openstack/resource_openstack_networking_port_v2.go
This change reverts a previous modification which restricted an allowed
address pair's IP address to be a single IP address rather than a CIDR.
For #659
=> Networking v2: Fix Allowed Address Pairs validation

openstack/data_source_openstack_fw_policy_v1.go, openstack/fw_firewall_v1.go, openstack/fw_policy_v1.go, openstack/fw_rule_v1.go, openstack/fw_rule_v1_test.go, openstack/resource_openstack_fw_firewall_v1.go, openstack/resource_openstack_fw_policy_v1.go, openstack/resource_openstack_fw_policy_v1_test.go, openstack/resource_openstack_fw_rule_v1.go, openstack/types.go
For #456 
The FWaaS v1 API code is flaky since there were some breaking changes introduced in v1. It's also quite difficult to get a working FWaaS v1 service running in newer versions of Neutron. I've run the acceptance tests in two different environments, running two different versions of OpenStack, and tests pass in the version they were targeted for.
It's totally possible to use these resources in production, but I'm sure those who are have workarounds they are doing. This is not a fault of the resources, but of the API code.
FWaaS v1 is not tested in OpenLab.
=> Internal: fwaas resources cleanup

openstack/resource_openstack_networking_subnet_v2.go, website/docs/r/networking_subnet_v2.html.markdown
This commit deprecates the host_routes argument of the
openstack_networking_subnet_v2 resource. Given there is a schema issue
with setting the host_routes attribute and that using both this resource
and the openstack_networking_subnet_route_v2 resource will cause diffs
to occur, it's best to have the supported solution be to use the
dedicated resource.
=> Networking v2: Deprecate openstack_networking_subnet_v2.host_routes

openstack/data_source_openstack_compute_availability_zones_v2.go, openstack/data_source_openstack_compute_availability_zones_v2_test.go, openstack/provider.go, website/docs/d/compute_availability_zones_v2.html.markdown, website/openstack.erb
In working with this provider, I found myself missing the ability to query OpenStack for availability zones like you can in other providers (such as `terraform-provider-aws`).
This PR adds that functionality.
If anything is missing, please let me know! This is my first PR adding a resource/datasource to a provider
=> Add new data source 'openstack_compute_availability_zones_v2'

openstack/lb_v2_shared.go
Resolves #687 
When `/statuses` responses with `null`, `Extract()` method doesn't fail, but returns `nil`. If it is nil, then a successful result is the best we can do.
=> LBaaS V2: Detect null LB statuses result

openstack/networking_port_v2.go, openstack/networking_port_v2_test.go, openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_port_v2_test.go
This improvement will simplify further changes for newer port DNS (597) and port bindings extensions (665). Now port properties and DHCP options can be updated in one call.
I removed `expandNetworkingPortDHCPOptsV2Delete` func and embedded its logic into the `expandNetworkingPortDHCPOptsV2Update`. Using Sets, we can identify which options should be removed, and which options should be added, and combine this data into one `finalUpdateOpts`.
@ozerovandrei, @jtopjian please review.
=> Networking V2: Update port DHCP options in one API call

openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2_test.go, website/docs/r/networking_subnet_v2.html.markdown
Added the ability to define the required `prefix_length` when creating a subnet from a subnet pool.
Fixes #333 and fixes #702 
I have run the `TestAccNetworkingV2Subnet_` tests against my local devstack instance and there ar eno failures:
```bash
$ make testacc TEST=./openstack TESTARGS="-run=TestAccNetworkingV2Subnet_ -count=1"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccNetworkingV2Subnet_ -count=1 -timeout 120m
=== RUN   TestAccNetworkingV2Subnet_importBasic
--- PASS: TestAccNetworkingV2Subnet_importBasic (30.29s)
=== RUN   TestAccNetworkingV2Subnet_basic
--- PASS: TestAccNetworkingV2Subnet_basic (32.04s)
=== RUN   TestAccNetworkingV2Subnet_enableDHCP
--- PASS: TestAccNetworkingV2Subnet_enableDHCP (29.33s)
=== RUN …
```
=> Add `prefix_length` to subnet create

openstack/resource_openstack_containerinfra_cluster_v1.go
Observed an issue when creating the cluster with custom node and master flavors, the master flavor is ignored and set to the node flavor.
=> Correction for the master flavor

website/docs/r/compute_instance_v2.html.markdown
Remove fixed_ip_v6 from the network block in 
As described in #732 `fixed_ip_v6` can't be specified. Is 'read-only'.
Resolves #732
=> Remove fixed_ip_v6 from the network block

openstack/resource_openstack_sharedfilesystem_share_access_v2.go
This commit enforces case sensitivity on access_type and access_level.
Per discussion in #715 
/cc @kayrus
=> SharedFilesystem v2: Fix access validation rules

.zuul.yaml
Input comment "recheck stable/stein" in pull request comments, that
will trigger acceptance tests against OpenStack Stein release. OpenLab
will report test result in followint comments automatically.
Related: theopenlab/openlab#231
=> Support acceptance test against OpenStack Stein release in OpenLab

openstack/networking_subnet_v2.go, openstack/networking_subnet_v2_test.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2_test.go, vendor/github.com/hashicorp/terraform/helper/customdiff/compose.go, vendor/github.com/hashicorp/terraform/helper/customdiff/computed.go, vendor/github.com/hashicorp/terraform/helper/customdiff/condition.go, vendor/github.com/hashicorp/terraform/helper/customdiff/doc.go, vendor/github.com/hashicorp/terraform/helper/customdiff/force_new.go, vendor/github.com/hashicorp/terraform/helper/customdiff/validate.go, vendor/modules.txt, website/docs/r/networking_subnet_v2.html.markdown
This commit deprecates the openstack_networking_subnet_v2
allocation_pools argument in favor of allocation_pool.
allocation_pool is a singular word which makes more sense to use
declaratively.
In addition, allocation_pools was originally a TypeList, but the
OpenStack API will not respect the ordering defined by the user for
multiple pools, which triggered unneeded diffs.
allocation_pool is now a TypeSet which accounts for an unordered
response.
For #729 
/cc @kayrus
=>  Networking v2: Deprecate subnet allocation_pools for allocation_pool

openstack/networking_secgroup_rule_v2.go, openstack/networking_secgroup_rule_v2_test.go, openstack/resource_openstack_networking_secgroup_rule_v2.go
Update loging and error messages to use common format between resources.
Move Secgroup Rule helpers into openstack/networking_secgroup_rule_v2.go
and provide additional tests.
We're not adding validation.ValidateFunc for the "direction",
"ethertype" and "protocol" fields because we're checking and casting
those strings values to Gophercloud constants by ourselves.
For #456
=> Internal: Networking V2 Secgroup Rule cleanup

openstack/resource_openstack_networking_port_v2.go
The OpenStack Compute service will set a port's dns_name to the name of
the instance when the OpenStack environment has the DNS extension
enabled. Because of this behavior, the dns_name needs to be set to
Computed or else the dns_name will be changed to an empty string on the
next apply.
For #742
=> Networking v2: Make port dns_name computed

openstack/resource_openstack_compute_instance_v2.go
Some machines require more time to do graceful shutdown. Timeout is now hardcoded to three minutes, this PR makes this value configurable.
=> Make timeout for stop_before_destroy configurable

go.mod, go.sum, openstack/resource_openstack_dns_recordset_v2.go, openstack/resource_openstack_dns_recordset_v2_test.go, vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/requests.go, vendor/modules.txt
For https://github.com/gophercloud/gophercloud/issues/1562
Before vendor update:
```
--- FAIL: TestAccDNSV2RecordSet_ensureSameTTL (176.83s)
testing.go:538: Step 1 error: Check failed: Check 2/2 error: openstack_dns_recordset_v2.recordset_1: Attribute 'ttl' expected "3000", got "0"
```
After vendor update:
```
--- PASS: TestAccDNSV2RecordSet_ensureSameTTL (166.49s)
PASS
ok      github.com/terraform-providers/terraform-provider-openstack/openstack   166.522s
```
=> DNS v2: Fix issue where TTL was being cleared

openstack/resource_openstack_compute_secgroup_v2_test.go
A recent update to Neutron will cause an ipv6 icmp security group rule
to be returned with a protocol of ipv6-icmp.
We can't update the test to use ipv6-icmp since Nova does not allow this
protocol type.
As a workaround, we change the protocol to tcp.
/cc @kayrus
=> Acc Tests: Update lowercase security group test

go.mod, go.sum, openstack/resource_openstack_compute_instance_v2.go, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/requests.go, vendor/modules.txt, website/docs/r/compute_instance_v2.html.markdown
For #770 
Between the bug fixed in ` openstack/resource_openstack_compute_instance_v2.go` and the required vendor fix, it appears that the scheduler hints query never worked.
These two commits fix this and allow "simple" queries to work -- queries which do not require a sublist of conditionals. IIRC, this was the original design goal since it would be hard to model such syntax in terraform.
=> Compute v2: Fix scheduler hints query

openstack/data_source_openstack_networking_qos_policy_v2.go, openstack/data_source_openstack_networking_qos_policy_v2_test.go, openstack/provider.go, website/docs/d/networking_qos_policy_v2.html.markdown, website/openstack.erb
Implement openstack_networking_qos_policy_v2 datasource with tests and
website documentation.
For #760
=> Networking V2: add QoS Policy datasource

openstack/networking_network_v2.go, openstack/resource_openstack_networking_network_v2.go, openstack/resource_openstack_networking_network_v2_test.go, website/docs/r/networking_network_v2.html.markdown
Add "qos_policy_id" attribute for "openstack_networking_network_v2"
resource.
Update tests and docs.
For #760
=> Networking V2: add QoS policy field for Network

openstack/networking_qos_policy_v2.go, openstack/resource_openstack_networking_qos_policy_v2.go, openstack/resource_openstack_networking_qos_policy_v2_test.go
Groups imports for "openstack_networking_qos_policy" resource the same
way as it done for other resources.
=> Networking V2: group QoS policy imports

openstack/networking_port_v2.go, openstack/resource_openstack_networking_port_v2.go, openstack/resource_openstack_networking_port_v2_test.go, website/docs/r/networking_port_v2.html.markdown
Add "qos_policy_id" attribute for "openstack_networking_port_v2"
resource.
Update tests and docs.
For #760, #246
=> Networking V2: add QoS policy field for Port

openstack/import_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/networking_qos_rule_v2.go, openstack/provider.go, openstack/resource_openstack_networking_qos_dscp_marking_rule_v2.go, openstack/resource_openstack_networking_qos_dscp_marking_rule_v2_test.go, website/docs/r/networking_qos_dscp_marking_rule_v2.html.markdown, website/openstack.erb
Add "openstack_networking_qos_dscp_marking_rule_v2" resource with
tests and website documentation.
For #760
=> Networking V2: add QoS DSCP marking rule resource

openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2.go, openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, website/docs/r/networking_qos_bandwidth_limit_rule_v2.html.markdown
Set default direction of the
"resource_openstack_networking_qos_bandwidth_limit_rule_v2" to "egress".
For #760
=> Networking V2: set QoS bw limit default direction

openstack/data_source_openstack_networking_qos_bandwidth_limit_rule_v2.go, openstack/data_source_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/provider.go, website/docs/d/networking_qos_bandwidth_limit_rule_v2.html.markdown, website/openstack.erb
Implement openstack_networking_qos_bandwidth_limit_rule_v2 datasource
with tests and website documentation.
For #760
=> Networking V2: add QoS bw limit rule datasource

openstack/data_source_networking_qos_dscp_marking_rule_v2.go, openstack/data_source_networking_qos_dscp_marking_rule_v2_test.go, openstack/provider.go, website/docs/d/networking_qos_dscp_marking_rule_v2.html.markdown, website/openstack.erb
Implement openstack_networking_qos_dscp_marking_rule_v2 datasource
with tests and website documentation.
For #760
=> Networking V2: add QoS dscp marking datasource

openstack/resource_openstack_vpnaas_site_connection.go
because false is a bad default.
=> vpnaas_site_connection: Switch admin_state_up default to true

website/docs/r/blockstorage_volume_attach_v3.html.markdown
openstack_compute_volume_attach_v3 doesn't exist as a resource. openstack_compute_volume_attach_v2 only exists which is using underlying nova API.
=> openstack_compute_volume_attach_v3 doesn't exist

openstack/import_openstack_compute_instance_v2_test.go, openstack/resource_openstack_compute_instance_v2.go, website/docs/r/compute_instance_v2.html.markdown
Since openstack does not keep track of NIC ordering, the user
must specify network in the order of the imported state.
=> Enable import instance

go.mod, go.sum, openstack/import_openstack_keymanager_container_v1_test.go, openstack/keymanager_container_v1.go, openstack/provider.go, openstack/resource_openstack_keymanager_container_v1.go, openstack/resource_openstack_keymanager_container_v1_test.go, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go, vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/results.go, vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go, vendor/modules.txt, website/docs/r/keymanager_container_v1.html.markdown, website/openstack.erb
Fixes #352
Depends on https://github.com/gophercloud/gophercloud/pull/1659 and #807
=> Keymanager V1: container resource

openstack/import_openstack_networking_rbac_policy_v2_test.go, openstack/provider.go, openstack/resource_openstack_networking_rbac_policy_v2.go, openstack/resource_openstack_networking_rbac_policy_v2_test.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/urls.go, vendor/modules.txt, website/docs/r/networking_rbac_policy_v2.html.markdown, website/openstack.erb
Resolves #810
@jtopjian, @ozerovandrei acceptance tests require admin permissions, therefore they'll be skipped in OpenLab environment. Please run these tests locally.
/cc @BugRoger I renamed the initial resource name from `openstack_networking_rbacpolicies_v2` to `openstack_networking_rbac_policy_v2`
=> Networking v2: Add neutron rbac policy resource

go.mod, go.sum, openstack/data_source_openstack_identity_endpoint_v3.go, openstack/data_source_openstack_identity_endpoint_v3_test.go, openstack/identity_endpoint_v3.go, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/endpoints/requests.go, vendor/modules.txt, website/docs/d/identity_endpoint_v3.html.markdown
Resolves #816
Depends on https://github.com/gophercloud/gophercloud/pull/1664
In additional, more efficient filtering was added and a new `service_type` attribute, the acceptance test was fixed.
=> Identity V3: Fix endpoint data source filtering

go.mod, go.sum, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go, vendor/modules.txt
Update Gophercloud library to fix the issue with time format for
Networking V2 resources in old OpenStack releases.
For #830
=> Vendor: update Gophercloud for time format fix

openstack/resource_openstack_lb_monitor_v2.go, website/docs/r/lb_monitor_v2.html.markdown
=>  LBaaS V2: Add OpenContrail monitor workaround

openstack/resource_openstack_compute_flavor_access_v2.go
=> Compute V2: Fix not found logic for the flavor access

CHANGELOG.md, openstack/config.go, openstack/provider.go, openstack/types.go, website/docs/index.html.markdown
Added workaround for cases when Openstack API doesn't provide proper HTTP Cache-Control headers [GH-264]
Also see:
- https://github.com/gophercloud/gophercloud/issues/727
- http://specs.openstack.org/openstack/api-sig/guidelines/http/caching.html
=> Add ability to control caching

go.mod, go.sum, openstack/lb_v2_shared.go, openstack/provider_test.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_listener_v2_test.go, vendor/github.com/gophercloud/gophercloud/go.mod, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/results.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/results.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/results.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go, vendor/modules.txt, website/docs/r/lb_listener_v2.html.markdown
Add the following arguments into the "openstack_lb_listener_v2"
resource:
- timeout_client_data
- timeout_member_connect
- timeout_member_data
- timeout_tcp_inspect
Update openstack_lb_listener_v2 tests.
Update openstack_lb_listener_v2 docs.
Cleanup openstack_lb_listener_v2 resource code and log messages.
For #867  #456
=> LoadBalancer V2: add timeout options for listener

go.mod, go.sum, openstack/import_openstack_lb_listener_v2_test.go, openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_listener_v2_test.go, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/go.mod, vendor/modules.txt
Fix "json: Unmarshal(non-pointer listeners.Listener)" by not using any
common interfaces or methods for Get method.
Add len(listener.Loadbalancers) check for setting valid id of the
openstack_lb_listener_v2 resource.
Add TestAccLBV2Listener_importOctavia().
For #867
=> LoadBalancer listener V2: fix Read method

openstack/resource_openstack_sharedfilesystem_securityservice_v2.go, openstack/resource_openstack_sharedfilesystem_share_access_v2.go, openstack/resource_openstack_sharedfilesystem_share_access_v2_test.go, openstack/sharedfilesystem_shared_v2.go
Cleanup openstack_sharedfilesystem_securityservice_v2 resource.
Move basic Manila microversions from
resource_openstack_sharedfilesystem_securityservice_v2.go into
sharedfilesystem_shared_v2.go.
For #456
=> Shared filesystem V2: cleanup securityservice

go.mod, go.sum, openstack/resource_openstack_lb_loadbalancer_v2.go, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go, vendor/modules.txt, website/docs/r/lb_loadbalancer_v2.html.markdown
Fixes #903 
Incorporates upstream gophercloud fix.
https://github.com/gophercloud/gophercloud/issues/1743
The openstack_lb_loadbalancer_v2 flavor attribute is now
`flavor_id` to match the Neutron LBaaSv2 and Octavia
api attribute.
=> Fixed openstack_lb_loadbalancer_v2 flavor selection.

go.mod, go.sum, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/client.go, vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go, vendor/modules.txt
=> Auth: reuse existing token, when scope parameters are not defined

openstack/import_openstack_networking_quotas_v2_test.go, openstack/provider.go, openstack/resource_openstack_networking_quota_v2.go, openstack/resource_openstack_networking_quota_v2_test.go, website/docs/r/networking_quota_v2.html.markdown, website/openstack.erb
Use singular name like all other resources do.
Use schema.RemoveFromState for Delete instead of a custom empty method.
For #657
=> Networking V2: rename "Quotas" resource to "Quota"

openstack/config.go, openstack/provider.go
Follow up for the #918 
It should be possible to use this option in terraform [swift backend](https://github.com/hashicorp/terraform/blob/cd7c3e4231c3730b56812881756ac82a6a569583/backend/remote-state/swift/backend.go#L343)
=> Auth: AllowReauth option should be exported

openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_router_v2_test.go, website/docs/r/networking_router_v2.html.markdown
Resolves #449
Requires https://github.com/gophercloud/gophercloud/issues/1414 to be fixed
=> Networking V2: Omit empty ExternalFixedIP IPAddress for the router

website/docs/r/identity_user_v3.html.markdown
Add missing character to documentation for fixing the error:
`Blocks of type "extra" are not expected here. Did you mean to define argument
"extra"? If so, use the equals sign to assign it a value.`
The example lacks an equal sign, which is the reason for the error. The solution is described in the following article. [https://www.terraform.io/docs/extend/best-practices/detecting-drift.html#error-checking-aggregate-types](https://www.terraform.io/docs/extend/best-practices/detecting-drift.html#error-checking-aggregate-types)
=> Missing character

openstack/data_source_openstack_containerinfra_cluster_v1.go, openstack/resource_openstack_containerinfra_cluster_v1.go
This patch allows users to select a custom network/subnet when creating kubernetes clusters. The API is supported in magnum 9.0.0 (Openstack Train) and above.
=> Magnum - add fixed_network/fixed_subnet support

website/docs/d/containerinfra_cluster_v1.html.markdown, website/docs/r/containerinfra_cluster_v1.html.markdown
Add fixed_network, fixed_subnet arguments and attributes to COE V1
cluster resource and datasource.
=> Docs: update COE V1 cluster fixed net and subnet

website/docs/index.html.markdown
os-client-config is deprecated and has been merged into openstacksdk.
While the existing documentation link is valid, it's bound to be
stale at some point. Update to point to the new location.
=> Update clouds.yaml doc reference to openstacksdk

go.mod, go.sum, openstack/containerinfra_shared_v1.go, openstack/import_openstack_orchestration_stack_v1_test.go, openstack/orchestration_stack_v1.go, openstack/provider.go, openstack/resource_openstack_orchestration_stack_v1.go, openstack/resource_openstack_orchestration_stack_v1_test.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/environment.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/errors.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/fixtures.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/results.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/template.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/utils.go, vendor/github.com/gophercloud/utils/terraform/auth/config.go, website/docs/r/orchestration_stack_v1.html.markdown, website/openstack.erb
Resolves #293 
Depends on gophercloud/utils#104
With stack support, you will be able to create stack and create
any resource types from OpenStack heat if that type is supported with
your Orchestraion service (you can find some example in [2]).
This means if you wish to have auto-scaling support you can use template like in [1], or use whatever your Heat can support (include calling Senlin resource type in heat and to do autoscaling too if that's what you wish for)
More document for heat is under [3] and [6]. If you have anything to report, you can report on gophercloud [4] or heat [5]
[1] https://opendev.org/openstack/heat-templates/src/branch/master/hot/autohealing/autohealing_group.yaml
[2] https://opendev.org/openstack/heat-templates
[3] https://docs.openstack.org/heat
[4] …
=> Add resource openstack_orchestration_stack_v1

website/docs/r/lb_l7policy_v2.html.markdown
tiny typo has been noticed and fixed
=> LBaaS: Typo fixed in lbaas l7 policy documentation

.zuul.yaml
Remove job terraform-provider-openstack-acceptance-test-mitaka, as ubuntu-trusty is EOL.
=> Remove mitaka test job "terraform-provider-openstack-acceptance-test-mitaka" which use ubuntu-trusty

.zuul.yaml
fix-go-sum branch needs to update the zuul configuration
=> Remove mitaka check job as ubuntu-trusty is EOL(fix-go-sum)

.zuul.yaml
There are 4 branch including the original zuul  configuration. I will post PRs one by one.
=> Remove mitaka check job as ubuntu-trusty is EOL(stable-website)

openstack/data_source_openstack_containerinfra_cluster_v1.go, openstack/resource_openstack_containerinfra_cluster_v1.go
Resolves #968
GopherCloud shows these are lists, update provider to suit.
Per ask on [twitter](https://twitter.com/aurynn/status/1241918377276239872)
No test updates, as I could not find any other reference to `master_addresses` or `node_addresses` in the codebase 
Unchecked code, depending on repo's CI to validate (could not run tests locally)
=> Match type on master_addresses and node_addresses on containerinfra_cluster

website/docs/r/objectstorage_container_v1.html.markdown
The old URL was no longer valid; updated to the current URL.
=> Update object verisoning documentation URL

openstack/resource_openstack_networking_secgroup_rule_v2.go
Resolves #879 
This fix could help each user who uses Contrail module instead of neutron. 
In the Contrail model, SG rule is not a separate object, but an entry element inside the security-group object's security-group-entries property.
Very often Juniper provides installation of contrail to a datacenter without some important fixes as this -> which is already implemented [here](https://github.com/Juniper/contrail-controller/blob/32cf7fa1c888e229d37027a9d805d6d40cf2bb28/src/config/vnc_openstack/vnc_openstack/neutron_plugin_db.py#L443). It adjusts a lock mechanism for creation of security group rules.
It makes using of openstack terraform provider to create/delete security group rules totally annoying. (There are two WA described in issue.) 
I added synchronization of calls. 
It will take …
=> Implemented Security Group Rule Mutex 

openstack/import_openstack_objectstorage_container_v1_test.go, openstack/resource_openstack_objectstorage_container_v1.go, openstack/resource_openstack_objectstorage_container_v1_test.go, website/docs/r/objectstorage_container_v1.html.markdown
This PR adds missing fields when reading a `openstack_objectstorage_container_v1`, and allows importing.
`container_sync_to` and `container_sync_key` can't be set because the respective fields are not returned by Gophercloud (see issue https://github.com/gophercloud/gophercloud/issues/1958).
We can either wait for those fields to be available in Gophercloud and then bump Gophecloud dep, or merge as-is ?
NB : I'm a beginner in Golang, so feel free to raise any warning regarding the code style/golang usage
ToDo : better handling for metadata keys
=> Object Storage Container V1: Add reading fields and import

openstack/resource_openstack_lb_pool_v2.go, website/docs/r/lb_pool_v2.html.markdown
The OVN load balancing provider only supports `SOURCE_IP_PORT` as load balancing method for pools.
=> Add SOURCE_IP_PORT load balancing method

openstack/provider.go, website/docs/index.html.markdown
Our tests showed that enabling delayed_auth option reduced an amount of keystone auth calls and helped to avoid nginx request limits in case of running terraform with complex logic.
See #861, when this feature was introduced initially.
In addition it's worth enabling the `allow_reauth` option by default as well.
/cc @ozerovandrei @jtopjian
=> Enable delayed_auth and allow_reauth options by default

openstack/networking_secgroup_v2.go, openstack/resource_openstack_networking_secgroup_v2.go, openstack/resource_openstack_networking_secgroup_v2_test.go
Add helpers into openstack/networking_secgroup_v2.go.
Refactor networking_secgroup_v2 resource code with tests.
For #456
=> Networking V2: cleanup secgroup resource

openstack/data_source_openstack_networking_subnet_v2.go, openstack/networking_subnet_v2.go, openstack/networking_subnet_v2_test.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/util.go
Cleanup openstack_networking_subnet resource and datasource.
Implement tests for networking_subnet_v2 helpers.
Change "dns_nameservers" argument form list to set to remove unnecessary
helper that verified if nameservers are distinct.
For #456
=> Networking: cleanup subnet V2

openstack/data_source_openstack_compute_instance_v2.go, openstack/data_source_openstack_compute_instance_v2_test.go, openstack/provider.go, website/docs/d/compute_instance_v2.html.markdown
Resolves #982 
This is largely copied from `resource.openstack_compute_instance_v2`.
I've checked the data source itself locally, but I have no way to run the full test suite, so relying on project CI.
=> Add compute_instance_v2 data source

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_loadbalancer_v2_test.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/urls.go, vendor/modules.txt, website/docs/r/lb_loadbalancer_v2.html.markdown
Add handling of vip_network_id fields.  Octavia allows creation of a load balancer using the network id (instead of providing the subnet id)
Closes: #683
=> Add vip_network_id for octavia

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, website/docs/r/lb_listener_v2.html.markdown
This adds support for Octavia's "allowed CIDRs" option on load balancer listeners. Gophercloud already supported the API, so this is just wiring up support in the provider side. It accepts a list of CIDR blocks as strings.
Fixes #1029
=> Add "allowed_cidrs" option for Octavia listeners

openstack/resource_openstack_containerinfra_cluster_v1.go
v1.30.0 release breaks backward compatibility by sending merge_labels.
Only add this to createOpts when true.
=> Fix merge labels

openstack/data_source_openstack_identity_auth_scope_v3.go, openstack/data_source_openstack_identity_project_v3.go, openstack/identity_auth_scope_v3.go, openstack/resource_openstack_identity_application_credential_v3.go, openstack/resource_openstack_identity_ec2_credential_v3.go
Followup for the #1033 
Reuse identity client side functions to get the current token scope details without redound requests to identity service.
=> Identity V3: reduce keystone requests amount

website/docs/index.html.markdown
Added information on how to get networks to work on Rackspace in the
Rackspace compatibility section.
=> docs: update Rackspace compatibility notes

website/docs/r/identity_ec2_credential_v3.html.markdown
@ozerovandrei just a doc update, ready for review
=> Keystone v3: fix ec2 credentials typo in docs

openstack/compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2_test.go, website/docs/r/compute_instance_v2.html.markdown
In official OpenStack Compute API documentation,
we can specify the network settings by putting special characters in the network option.
But the current provider does not have a related function.
To satisfy this functionality, add `network_mode` options to resource.
reference
- [Compute API Document](https://docs.openstack.org/api-ref/compute/?expanded=create-server-detail#id11)
=> Update to allow special network option in create server

.zuul.yaml, README.md, go.mod, main.go
Use terraform-provider-openstack/terraform-provider-openstack as Go module name.
Use terraform-provider-openstack/terraform-provider-openstack repo in README.md.
Use terraform-provider-openstack/terraform-provider-openstack name in .zuul.
=> Update repo name in CI, modules and README.md

README.md
Do not use GOPATH since it's not needed anymore.
=> Remove GOPATH from the README.md

openstack/resource_openstack_blockstorage_volume_attach_v2_test.go, openstack/resource_openstack_blockstorage_volume_attach_v3_test.go, website/docs/r/blockstorage_volume_attach_v2.html.markdown, website/docs/r/blockstorage_volume_attach_v3.html.markdown
There were some changes in Cinder code that prevent non-admin user to
retrieve "host_name" for volume attachments:
https://review.opendev.org/#/c/726751/
https://github.com/openstack/cinder/commit/8bf454b0b5c7b77bdde8fe8a98d5225957e9c912
Volume attachment tests should check if user is admin via PreCheck
function.
See https://github.com/theopenlab/openlab/issues/571 for additional details.
=> Run BlockStorage attach tests as admin only

openstack/data_source_openstack_keymanager_container_v1.go, openstack/data_source_openstack_keymanager_secret_v1.go, openstack/identity_user_v3.go, openstack/keymanager_v1.go, openstack/lb_v2_shared.go, openstack/resource_openstack_identity_user_v3.go, openstack/resource_openstack_keymanager_container_v1.go, openstack/resource_openstack_keymanager_secret_v1.go, openstack/resource_openstack_lb_l7policy_v2.go, openstack/resource_openstack_lb_l7rule_v2.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_members_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go
Prepare to enable gochecknoglobals linter for #1063 
Replace global variables with getter functions:
* supported ACL operations and ACL schema
* valid date filters
* user options
* lb statuses
=> Remove global variables

openstack/provider.go, openstack/provider_test.go, openstack/resource_openstack_networking_router_route_v2.go, openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_secgroup_rule_v2.go, openstack/resource_openstack_networking_subnet_route_v2.go
So this global mutex kv struct available everywhere in provider without
being a global variable.
For #1063
=> Moved global mutexKV to Config structure

openstack/internal/mutexkv/mutexkv.go, openstack/internal/mutexkv/mutexkv_test.go, openstack/provider.go, openstack/provider_test.go
Because MutexKV will be removed from terraform-plugin-sdk package copy
it to local internal/mutexkv package.
For #1058
=> Copy MutexKV to internal package

openstack/resource_openstack_networking_rbac_policy_v2.go
Openstack release ussuri added some types for RBAC policies. This allows them to be managed by the provider.
=> add address_scope, security_group and subnetpool to rbac types

openstack/resource_openstack_networking_port_v2.go
Hi,
This is linked to my issue #1082.
I don't know if this is the right fix but this seems to fix my issue (and maybe it would prevent an explicit setting of the host_id in the Terraform file?). It seems to be set as "Computed " as well in openstack/data_source_openstack_networking_port_v2.go but I am really not aware of the difference in purpose between these 2 files.
Thanks for the feedback,
Gregory
----
If the binding section is defined in the ressource definition (e.g.
just with "binding.vnic_type" set), but "binding.host_id" is left empty,
the port is created correctly and "binding.host_id" populated with the
id of the selected hypervisor. However, upon a subsequent plan/apply,
Terraform seems to reset "binding.host_id" to NULL. The port enters
status DOWN and connectivity is lost. …
=> Networking V2: fix 'binding.host_id' reset (#1082)

openstack/compute_instance_v2.go
When you query for the details on a server in OpenStack, you get a list
of addresses assigned to that server which is keyed by pool. This
unfortunately causes problems becauses addresses are actually a JSON
object keyed by their network name. JSON objects are unordered by spec
and Go uses map[string]interface{} for JSON objects which is also
unordered. However this provider keeps the networks in a TypeList which
is order dependent. If you import a server then the networks will come
in a random order and terraform will insist it must rebuild the server.
Unfortunately there's no way to ensure that the ordering matches how it
came back from OpenStack due to this. This is only an issue when there
are two default networks such as for a provider with "public" and
"private" as default networks. …
=> compute_instance_v2: handle special case of 2 default networks

openstack/data_source_openstack_dns_zone_v2.go, openstack/data_source_openstack_dns_zone_v2_test.go, openstack/data_source_openstack_identity_project_v3.go, openstack/dns_zone_v2.go, openstack/resource_openstack_dns_zone_v2.go, website/docs/d/dns_zone_v2.html.markdown, website/docs/r/dns_zone_v2.html.markdown
* Replicates `--all-projects` and `--sudo-project-id` functionality
from openstackclient
* Users can set project_id and create designate dns zones in a
different project
* Resource import support with `<zone_uuid>:<project_id>`
* `project_id` attribute support for data source
* Support for getting a zone id from a unique zone name by listing all
projects
=> Tenant attribute support for openstack_dns_zone_v2

go.mod, go.sum, openstack/resource_openstack_compute_instance_v2.go, vendor/github.com/gophercloud/gophercloud/.zuul.yaml, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go, vendor/modules.txt, website/docs/r/compute_instance_v2.html.markdown
While the code base supported the target_cell scheduler hint to get
instances to build in a specified cell, there was no support to skip
cells if you were attempting to skip a specific cell.
=> compute/instance: add different_cell scheduler hint

website/docs/r/networking_quota_v2.html.markdown
Update openstack_networking_quota_v2 docs:
1. Add note describing consequences of not specifying the optinonal quota arguments
2. Replace openstack_identity_project_v2 with openstack_identity_project_v3 in the examples
=> Update openstack_networking_quota_v2 docs

.github/workflows/golangci-lint.yml
Github deprecated some env things:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
New golangci-lint looks like it fixes this
https://github.com/golangci/golangci-lint-action/issues/127#issuecomment-729139550
=> Upgrade golangci-lint-action for new github actions env changes

openstack/resource_openstack_compute_flavor_v2.go, openstack/resource_openstack_compute_flavor_v2_test.go, website/docs/r/compute_flavor_v2.html.markdown
Openstack and Gopherclioud have ability to set compute flavor UUID while creating flavor.
Replicating this functionality in terraform. Docs and tests also altered.
=> Add flavor_id to openstack_compute_flavor_v2 resource creation options

openstack/resource_openstack_identity_project_v3.go, website/docs/r/identity_project_v3.html.markdown
Hello,
First PR so apologies for any dummy mistakes.
Update identityProjectV3 and docs accordingly for immutable arguments (domain_id, is_domain and parent_id). Openstack api docs:
- https://docs.openstack.org/api-ref/identity/v3/?expanded=create-project-detail#create-project
- https://docs.openstack.org/api-ref/identity/v3/?expanded=create-project-detail,update-project-detail#update-project
The openstack docs provide some more information for constraints when defining domain_id and parent_id etc. Let me know if you want me to add this info in the docs.
Close #958
=> Identity v3: Mark immutable project arguments #958

openstack/resource_openstack_compute_flavor_v2_test.go, website/docs/r/compute_flavor_v2.html.markdown, website/docs/r/compute_instance_v2.html.markdown
- compute_flavor_v2:
`ephemeral` argument was missing from docs while it is [supported](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_flavor_v2.go#L78). Updated the docs and added the argument in one of the tests
- compute_instance_v2
`guest_format` argument was missing from docs while it is [supported](https://github.com/hashicorp/terraform-provider-openstack/blob/5b145a14e27f78440aeaf60f0156f0cd014f7c39/openstack/resource_openstack_compute_instance_v2.go#L1065). Updated the docs with info and added an example with swap.
Close #897
=> Issue/897 update compute_flavor_v2 and compute_instance_v2 docs with missing arguments

openstack/import_openstack_dns_zone_v2_test.go, openstack/resource_openstack_dns_zone_v2.go, openstack/resource_openstack_dns_zone_v2_test.go, website/docs/r/dns_zone_v2.html.markdown
This will allow terraform to tolerate some backend issues in Designate. If zone is created in Designate, and even all the backends are down, Designate will try to recover.
If only one of the backends is down, zone will be in ERROR state, but will be served by other backends. In this case, waiting for ACTIVE state also doesn't make sense.
=> Allow to disable status check in resource_openstack_dns_zone_v2

openstack/resource_openstack_compute_interface_attach_v2.go
Currently if `fixed_ip` is specified idempotence is not respected because the property is not read on refresh.
=> Properly read fixed_ip property for network attachment

openstack/resource_openstack_compute_flavor_v2.go
We set it on Read() call so it should be computed and it shouldn't
create plan changes in case of an empty value.
For #1119
=> Flavor V2: make "flavor_id" computed

openstack/images_image_v2.go, openstack/resource_openstack_images_image_v2.go, website/docs/r/images_image_v2.html.markdown
In newer OpenStack releases (Ussuri) glance adds read-only image propertie _stores_.
It need to be excluded like _direct_url_
=> add: ignore image stores propertie

openstack/resource_openstack_images_image_v2.go, openstack/resource_openstack_images_image_v2_test.go, website/docs/r/images_image_v2.html.markdown
OpenStack and GopherCloud have ability to set Glance image UUID while creating image.
Replicating this functionality in Terraform. Docs and tests also altered.
Regex taken from Glance API response.
This is useful with images dedicated to Ironic when creating bundles of AKI/AMI and QCOW2 and in QCOW2 properties info about _ramdisk_id_ and _kernel_id_ can be filled with AKI and AMI UUID's.
=> Add image_id to openstack_images_image_v2 resource creation options

openstack/compute_volume_attach_v2.go, openstack/resource_openstack_compute_volume_attach_v2.go, openstack/resource_openstack_compute_volume_attach_v2_test.go, website/docs/r/compute_volume_attach_v2.html.markdown
Do not initialize a Block Storage V3 client and do not check volume
status if "ignore_volume_confirmation" is set to true.
Update computeVolumeAttachV2AttachFunc error.
Use Block Storage V3 in old tests of openstack_compute_volume_attach_v2
tests.
Add a new tests to check that "ignore_volume_confirmation" at least do
not create any trouble with manifests.
Update docs.
For #1123
=> ComputeV2: add optional ignore_volume_confirmation

openstack/data_source_openstack_compute_hypervisor_v2.go, openstack/data_source_openstack_compute_hypervisor_v2_test.go, openstack/provider.go, openstack/provider_test.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/results.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/urls.go, vendor/modules.txt, website/docs/d/compute_hypervisor_v2.html.markdown, website/docs/index.html.markdown
Support for Hypervisor data source.
Due to the nature of hypervisors (only LIST is available in the API), it's only possible to make data sources for hypervisors.
This data source aim is to provide information about cpu/memory/disk, so it's possible to auto-calculate quotas by listing every hypervisors in the system.
This backend is, as far as I know, only available for the admin user, so the test is restricted accordingly.
=> Hypervisor data source support

website/docs/index.html.markdown
openstack provider has moved to terraform-provider-openstack namespace,
and we can't use that as the local name directly, instead we define a
local name in the provider configuration block. This is required for newer terraform
version (maybe > 0.13.0).
[1]https://www.terraform.io/docs/configuration/provider-requirements.html#local-names
=> doc: use local provider

go.mod, go.sum, openstack/provider.go, openstack/provider_test.go, openstack/resource_openstack_networking_router_route_v2.go, openstack/resource_openstack_networking_router_v2.go, openstack/resource_openstack_networking_secgroup_rule_v2.go, openstack/resource_openstack_networking_subnet_route_v2.go
Fix copying of the sync.Locker in the Config.
Do not use a separate variable and just use *Config.MutexKV directly in
all places.
Update MutexKV initialization.
=> Update gophercloud/utils to fix MutexKV usage

openstack/resource_openstack_lb_loadbalancer_v2.go
Fixes #1146 
Before:
```
-/+ resource "openstack_lb_loadbalancer_v2" "infrastructure" {
- flavor_id             = "69b842e1-5476-4420-96f7-d8ea826eece0" -> null # forces replacement
...
}
```
After:
```
openstack_lb_loadbalancer_v2.infrastructure: Refreshing state... [id=791dfb94-e634-44ec-b1a5-caeedeb88e20]
No changes. Infrastructure is up-to-date.
```
🎉
=> Fix openstack_lb_loadbalancer_v2 flavor_id

openstack/import_openstack_identity_user_membership_v3_test.go, openstack/provider.go, openstack/resource_openstack_identity_user_membership_v3.go, openstack/resource_openstack_identity_user_membership_v3_test.go, website/docs/r/identity_user_membership_v3.html.markdown, website/openstack.erb
Add support for new resources indentity_user_membership_v3.
The resources is used to add users to groups.
Close #1142 
Related gophercloud resources:
- https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/users/requests.go#L288
- https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/users/requests.go#L298
- https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/users/requests.go#L313
=> Add resource identity_user_membership_v3

openstack/data_source_openstack_networking_network_v2.go, website/docs/d/networking_network_v2.html.markdown
Can be used to solve the #1150 issue. Less efficient way to list and filter external network subnets:
```hcl
variable "pattern" {}
data "openstack_networking_network_v2" "network" {
name = "external-network"
}
data "openstack_networking_subnet_v2" "subnet" {
count     = length(data.openstack_networking_network_v2.network.subnets)
subnet_id = data.openstack_networking_network_v2.network.subnets[count.index]
}
output "subnet_ids" {
value = [for x in data.openstack_networking_subnet_v2.subnet : x.id if length(regexall(var.pattern, x.name)) > 0]
}
output "subnet_names" {
value = [for x in data.openstack_networking_subnet_v2.subnet : x.name if length(regexall(var.pattern, x.name)) > 0]
}
```
=> Networking: expose subnets in network data source

openstack/data_source_openstack_images_image_ids_v2.go, openstack/data_source_openstack_images_image_v2.go, openstack/data_source_openstack_networking_port_ids_v2.go, openstack/data_source_openstack_networking_subnet_ids_v2.go, openstack/data_source_openstack_networking_subnet_ids_v2_test.go, openstack/data_source_openstack_networking_subnet_v2.go, openstack/provider.go, website/docs/d/networking_port_ids_v2.html.markdown, website/docs/d/networking_subnet_ids_v2.html.markdown, website/openstack.erb
This is an efficient way (comparing to #1152) to filter out network subnet IDs by a certain criteria. See a #1150  for a reference.
P.S. Fixed a couple of tiny bugs and docs typos while worked on the PR. I also deprecated `dhcp_disabled` in `data.openstack_networking_subnet_v2`, because it was introduced before Terraform SDK started to support the `GetOkExists` method.
=> Networking: introduce openstack_networking_subnet_ids_v2 data source

.golangci.yml, openstack/provider_test.go, openstack/resource_openstack_db_configuration_v1_test.go, openstack/resource_openstack_db_database_v1_test.go, openstack/resource_openstack_db_instance_v1_test.go, openstack/resource_openstack_db_user_v1_test.go
For now ST1005 (capitalized errors) check is disabled as it is required to
change almost every error message. Will be done in different PR.
For #1063
=> Enable stylecheck linter

CHANGELOG.md, go.mod, go.sum
This pulls recently merged improvements from gophercloud/utils:
* `clouds.yml` handling (compatibility with Python counterpart) [#142](https://github.com/gophercloud/utils/pull/142) (this actually made it into v1.37.0)
* correct merging of per-region value overrides in clouds.yaml [#143](https://github.com/gophercloud/utils/pull/143)
=> updated gophercloud/utils dependency

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_loadbalancer_v2_test.go, website/docs/r/lb_loadbalancer_v2.html.markdown
Part of https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1090
This PR makes possible to define vip_port_id when creating a loadbalancer using octavia only. vip_port_id cannot be defined by user on neutron LBaaS
=> openstack_lb_loadbalancer_v2: vip_port_id can be set for octavia

openstack/data_source_openstack_identity_auth_scope_v3.go, openstack/identity_auth_scope_v3.go, openstack/identity_auth_scope_v3_test.go, website/docs/d/identity_auth_scope_v3.html.markdown
Keystone returns a service catalog along with the auth token.  That provides
useful information such as service endpoint URLs which may not otherwise be
available.  This change adds the service catalog to the
identity_auth_scope_v3 data source.
=> Add a service_catalog attribute to identity_auth_scope_v3 data

openstack/compute_servergroup_v2.go, openstack/compute_servergroup_v2_test.go
This should allow custom policies to be applied by using the more recent version of nova API which allow different policies then anti-affinity and affinity.
See https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1134 for more details
=> Only use old client micro-version for old policies

openstack/data_source_openstack_identity_auth_scope_v3.go, openstack/data_source_openstack_identity_project_v3.go, openstack/identity_auth_scope_v3.go, openstack/resource_openstack_identity_application_credential_v3.go, openstack/resource_openstack_identity_ec2_credential_v3.go
Do not use exported functions.
Return structured token details and info instead of using lots of
returning values from helpers.
openstack/identity_auth_scope_v3.go.
=> Refactor auth scope helpers

website/docs/r/compute_instance_v2.html.markdown
Related to: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1173
Update docs to inform users to only use names in security_groups
=> Docs: Use names in `security_groups` in openstack_compute_instance_v2

openstack/networking_v2_shared.go, openstack/networking_v2_shared_test.go, openstack/resource_openstack_networking_quota_v2.go, website/docs/r/networking_quota_v2.html.markdown
Close #1104 
Appends region to networking_quota_v2 resource ID. This allows to manage quotas across regions for the same project.
=> networking_quota_v2: Manage quota by region

openstack/resource_openstack_compute_quotaset_v2.go, openstack/resource_openstack_compute_quotaset_v2_test.go, website/docs/r/compute_quotaset_v2.html.markdown
Similar to https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1177  and #1180 this adds support for multi-region for compute_quotaset.
=> openstack_compute_quotaset_v2: Add multi-region support

openstack/resource_openstack_blockstorage_quotaset_v2.go, openstack/resource_openstack_blockstorage_quotaset_v2_test.go, website/docs/r/blockstorage_quotaset_v2.html.markdown
Close #979
Gophercloud added support for volume_type quota with: gophercloud/gophercloud#2109
This PR requires both #1180 and #1182
=> blockstorage_quotaset_v2: Add volume type quota support

openstack/resource_openstack_blockstorage_quotaset_v3.go, openstack/resource_openstack_blockstorage_quotaset_v3_test.go, website/docs/r/blockstorage_quotaset_v3.html.markdown
Related to: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/979
Gophercloud added support for volume_type quota with: https://github.com/gophercloud/gophercloud/pull/2109
This PR requires both #1180 and #1183
=> blockstorage_quotaset_v3: Add volume type quota support

.github/workflows/release.yml
Use latest Go version for builds.
It will also enable `darwin/arm64` binaries.
For #1192
=> Use Go 1.16

openstack/resource_openstack_sharedfilesystem_share_v2_test.go
Users cannot make share publicly visible by default anymore.
This commit changes current test to not set is_public to true
and adds a new test for admin users to test this functionality.
Close #1205 
From release notes of manila:
> The ability to create a public share (RBAC: “share:create_public_share”) and to update a share to become publicly visible (RBAC: “share:set_public_share”) are now restricted to administator users operating at system scope. Adjust your policy file overrides if you would like to retain the older behavior of allowing all users to create public shares or to update private ones to public. If you do that, be sure that your users are aware of the security implications of publicly accessible shares.
From checking the latest commits etc on manilla they are changing …
=> Update TestAccSFSV2Share to respect new default policies

openstack/resource_openstack_images_image_v2.go
Change https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1186 has incidentally broken `openstack_images_image_v2` resource for all Glance servers with API before 2.7.
OpenStack releases before Rocky don't have a "hidden" field in the image schema. Setting it to anything will result in an API crash. Since the default value is "false" anyways, it is safe just to omit this field if it is set to false, to save some backward compatibility.
Example of failure message:
```
Error: Error updating image: Bad request with: [PATCH https://imageservice.local:9292/v2/images/5f8b8949-573c-4b0f-aa9e-42b909611f01], error message: {"message": "Provided object does not match schema 'image': True is not of type 'string'\n\nFailed validating 'type' in …
```
=> openstack_images_image_v2: don't set "hidden" field by default

openstack/resource_openstack_networking_port_v2_test.go
Removing binding.host_id from the resource definition does not
change it to the default "". Update testAccNetworkingV2PortUpdatePortBinding3
checks to follow that
Relates to #1211
=> Fix TestAccNetworkingV2Port_portBinding_update test

openstack/import_openstack_dns_recordset_v2_test.go, openstack/resource_openstack_dns_recordset_v2.go, openstack/resource_openstack_dns_recordset_v2_test.go, website/docs/r/dns_recordset_v2.html.markdown
This change is similar to a498d03c3a50d9ac986010a34411655d15b4db9c.
If recordset is created in Designate, and even all the backends are down,
Designate will try to recover. If only one of the backends is down, the
recordset will be in ERROR state, but will be served by other backends.
In this case, waiting for ACTIVE state also doesn't make sense.
=> Allow to disable status check in resource_openstack_dns_recordset_v2

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_loadbalancer_v2.go, website/docs/r/lb_loadbalancer_v2.html.markdown
Add availability_zone attribute to loadbalancer_v2
Close #1090
=> lb_loadbalancer_v2: Add availability_zone

openstack/resource_openstack_db_instance_v1.go, website/docs/r/db_instance_v1.html.markdown
When creating a database instance with only a network to attach to, Trove will automatically create a port on that network and have an IP address assigned. However, this can only be see on the query API in the `ip` or `addresses` attributes, you cannot see the network port uuid. (`ip` is deprecated, but the only attribute GopherCloud supports).
Expose the assigned addresses as a new exported list `addresses` which is just a straight copy of the `ip` attribute on the query response.
Tested against Trove Victoria.
=> Expose database instance IP addresses

openstack/resource_openstack_vpnaas_endpoint_group_v2.go, openstack/resource_openstack_vpnaas_endpoint_group_v2_test.go, openstack/resource_openstack_vpnaas_ipsec_policy_v2_test.go
Hi! I'm trying to improve on merge request !1089.
After some to-and-fro to get the tests running locally (I don't mess with a devstack, I have a real cloud at hand; but my test user wasn't called `demo` of course), it seems that what I think is the relevant test `TestAccGroupV2_basic` passes.
I triggered a recheck of !1089 because the logs seem to have expired, but when I looked, that specific test seems to be skipped.
```
2021-05-14 15:09:42.193729 | ubuntu-bionic | === RUN   TestAccGroupV2_basic
2021-05-14 15:09:42.193739 | ubuntu-bionic |     TestAccGroupV2_basic: provider_test.go:163: This environment does not support VPN tests
2021-05-14 15:09:42.193749 | ubuntu-bionic | --- SKIP: TestAccGroupV2_basic (0.00s)
2021-05-14 15:09:42.193759 | ubuntu-bionic | === RUN …
```
=> VPNaaS endpoint group resource: use schema.TypeSet for endpoints (V2)

openstack/resource_openstack_compute_instance_v2.go
I ran into a provider panic while trying to unassign a server group from a server.  By deferring to the default behavior, the nil check is sufficient to effectively unassign a server group.
=> Add nil check to server group hint creation

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_quota_v2.go, website/docs/index.html.markdown, website/docs/r/lb_listener_v2.html.markdown, website/docs/r/lb_loadbalancer_v2.html.markdown, website/docs/r/lb_members_v2.html.markdown, website/docs/r/lb_quota_v2.html.markdown
Octavia does not use microversions. Instead the api has minor versions.
Change existing implementations that assumed that microversions are in-use.
Add small documentation in index explaining how to fetch supported minor versions
of an Openstack cloud.
For every octavia resource that was using "microversions":
- Remove the setting of client microversion and set inline comment with the
required minor version.
- Update docs with a note and highlighting the required minor version
Relates to: #1239
=> Remove Octavia microversions

go.mod, go.sum, openstack/resource_openstack_lb_pool_v2.go, website/docs/r/lb_pool_v2.html.markdown
Update gophercloud to include required changes.
Add SCTP and PROXYV2 to the list of allowed protocols for pool_v2.
Update docs with the required octavia minor version for these
protocols.
Requires: #1249 for the documentation link
Close: #1250
=> lb_pool_v2: Add support for SCTP and PROXYV2 prot

openstack/dns_zone_v2.go, openstack/identity_auth_scope_v3.go
This fix handles an empty project scope. When a token is unscoped, or domain scoped, the project ID will be set to an empty string.
Fixes #1281
=> Fix panic, when a token doesn't have a project scope

.github/workflows/golangci-lint.yml, .golangci.yml, openstack/dns_transfer_accept_v2.go, openstack/networking_portforwarding_v2.go, openstack/resource_openstack_blockstorage_volume_type_access_v3.go, openstack/resource_openstack_blockstorage_volume_type_v3.go, openstack/resource_openstack_dns_transfer_accept_v2.go, openstack/resource_openstack_dns_transfer_request_v2.go, openstack/resource_openstack_lb_quota_v2.go
Update version in CI job.
Add local prefixes in config, remove deprecated linters, comment all
linters that are currently failing or not tested yet.
=> Bump golangci-lint version to v1.42.1

openstack/resource_openstack_objectstorage_tempurl_v1.go
Tempurl URL shouldn't be visible in plaintext by default.
URL should be known only by those who received it explicit rather than everyone with ability to see terraform plan.
Tempurl might point to object with sensitive content.
`nonsensitive()` function can be used in case someone prefer display tempurl in plaintext in terraform plan/output.
=> Flag tempurl url attribute as sensitive

openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_dns_zone_v2.go, openstack/util.go
We had some issues with our cloud which buckled under a high load, which resulted in a bunch of 504 errors.
Provider didn't handle the errors during async operations with DNS zones and Compute instances, which resulted in mismatched states when cloud resources were actually created, but didn't go into ACTIVE state before an intermittent API error.
This change let's the provider keep refreshing the state through 502 and 504 errors, to prevent missing resources in state, that are already present on the cloud.
=> Retry reading DNS zone and Compute instance state after creation

go.mod, go.sum, openstack/data_source_openstack_compute_hypervisor_v2.go, openstack/data_source_openstack_compute_keypair_v2.go, openstack/resource_openstack_compute_keypair_v2.go, openstack/resource_openstack_compute_keypair_v2_test.go, openstack/resource_openstack_objectstorage_container_v1.go
Upgrade Gophercloud to [v0.23.0][1] and its `utils` library to the
latest version available.
This patch is supposed to pick up all the bugfixes introduced in the library since v0.17.1.
[1]: https://github.com/gophercloud/gophercloud/releases/tag/v0.23.0
=> Bump Gophercloud

openstack/resource_openstack_networking_quota_v2.go
this change is required to make networking_quota_v2 resource to work properly
this problem with the origin solution, is that it doesn't "honor" the omitempty setting of keys in the underlaying lib
.Get() defaults to 0 if there is no key, so even undefined keys were passed to openstack api with 0 value
with the .GetOk() approach it is possible to change each quota individually without affecting any other, as the underlaying lib and the api supports
=> fixing network quota resource

openstack/data_source_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/data_source_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/data_source_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go, openstack/data_source_openstack_networking_qos_policy_v2_test.go, openstack/data_source_openstack_networking_trunk_v2_test.go, openstack/import_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/import_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/import_openstack_networking_qos_policy_v2_test.go, openstack/resource_openstack_networking_network_v2_test.go, openstack/resource_openstack_networking_port_v2_test.go, openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/resource_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/resource_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go, openstack/resource_openstack_networking_qos_policy_v2_test.go, openstack/resource_openstack_networking_trunk_v2_test.go
Qos and Trunk related accecptance tests are failing currently on
Openlab. Skip them for the time being
Relates to: #1323
=> Skip trunk and qos acceptance tests

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_loadbalancer_v2_test.go, website/docs/r/lb_loadbalancer_v2.html.markdown
Add support for tags for openstack_lb_loadbalancer_v2
For #1300
=> Octavia: Add tags to loadbalancer

openstack/provider.go
The Neutron LBAAS is deprecated :
https://wiki.openstack.org/wiki/Neutron/LBaaS/Deprecation
It has been replaced by Octavia, so set Octavia to the default one
This can be confusing since the error returned by the provider is not
very clear even if you put the provider in TRACE ( it will try to
contact neutron for creation the loadbalancer )
=> Octavia by default as Neutron LBAAS is deprecated

go.mod, go.sum, openstack/import_openstack_blockstorage_qos_v3_test.go, openstack/provider.go, openstack/resource_openstack_blockstorage_qos_v3.go, openstack/resource_openstack_blockstorage_qos_v3_test.go, website/docs/r/blockstorage_qos_v3.html.markdown, website/openstack.erb
Adds new resource for blockstorage v3 qos.
Bump gophercloud to include necessary calls.
Relates to: #1212
=> Add openstack_blockstorage_qos_v3

openstack/resource_openstack_images_image_v2.go
On images allow setting these properties in-place: `min_disk_gb`, `min_ram_mb`, `protected`
Closes #1287
⚠ I'm not sure whether this is all I need to do to fix this. There maybe code and tests that need to be modified
=> image: set forcenew=false on min_disk_gb, min_ram_mb, protected

openstack/data_source_openstack_blockstorage_volume_v3.go, website/docs/d/blockstorage_volume_v3.html.markdown
Getting the host attribute of a volume works now
using the gophercloud library; let's collect it.
Closes https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1292.
=> Fetch volume os-vol-host-attr from OpenStack API

openstack/provider.go
- when TF_LOG is debug/trace
- enable this by default (person probably wants it)
Resolves: terraform-provider-openstack/terraform-provider-openstack#1203
=> Update: enable OS_DEBUG

openstack/compute_keypair_v2.go, openstack/import_openstack_compute_keypair_v2_test.go, openstack/resource_openstack_compute_keypair_v2.go, website/docs/r/compute_keypair_v2.html.markdown
=> Be able to specify user_id when creating keypair

openstack/resource_openstack_networking_subnet_v2.go
If an invalid CIDR is passed to the subnet resource, for instance
because of a leading space, the plugin will crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b9aa0]
goroutine 101 [running]:
net.networkNumberAndMask(0x20)
net/ip.go:498
net.(*IPNet).String(0xc00069ed38)
net/ip.go:548 +0x2b
github.com/terraform-provider-openstack/terraform-provider-openstack/openstack.resourceNetworkingSubnetV2Create({0x10858e8, 0xc000428ea0}, 0xc00061f6c0, {0xef1fa0, 0xc0006a6b40})
github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_networking_subnet_v2.go:274 +0x795
[…]
```
By handling the error and returning it, the crash is avoided and a
proper error message can …
=> Fix segfault on invalid CIDR

openstack/data_source_openstack_networking_quota_v2.go
According documentation the ```region``` parameter can be optional:
But I've got an error in this case:
```
data "openstack_networking_quota_v2" "quota" {
region     = "MyRegion"
project_id = "2e367a3d29f94fd988e6ec54e305ec9d"
}
```
=> fix: networking quota region option

openstack/data_source_openstack_images_image_v2.go
Currently when you fetch the image information using `openstack_images_image_v2`, the properties field is empty.
The goal of this PR is to resolve this issue.
=> Properties of image are not returned

.github/workflows/functional-blockstorage_v3.yml
Add new workflow for running functional tests
for blockstorage_v3 resources.
Requires: #1391
Seperate jobs will be added for blockstorage_v2 and v1 as they are deprecated and do not exist in the latest versions of Openstack
=> [GH-A] Add workflow for blockstorage_v3 

.github/workflows/functional-dns.yml
Add new workflow for running functional tests for
dns/designate.
Requires: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1391
=> [GH-A] Add workflow for dns/designate

.github/workflows/functional-keymanager.yml, openstack/import_openstack_keymanager_order_v1_test.go
Add new workflow for running functional tests for
keymanager/barbican.
Requires: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1391
=> [GH-A] Add workflow for keymanager/barbican

website/openstack.erb
Nit fix with missing links for docs.
Follow-up from: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1364
=> Add links to containerinfra_nodegroup docs

.github/workflows/functional-blockstorage_v2.yml, .github/workflows/functional-blockstorage_v3.yml, openstack/resource_openstack_blockstorage_quotaset_v2_test.go
Functional testing for blockstorage_v2 which was deprecated on Pike
and completely removed on Xena.
=> [GH-A] Add workflow for blockstorage_v2

.github/workflows/functional-networking.yml, openstack/data_source_openstack_fw_policy_v1_test.go, openstack/data_source_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/data_source_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/data_source_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go, openstack/data_source_openstack_networking_qos_policy_v2_test.go, openstack/data_source_openstack_networking_trunk_v2_test.go, openstack/import_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/import_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/import_openstack_networking_qos_policy_v2_test.go, openstack/resource_openstack_networking_network_v2_test.go, openstack/resource_openstack_networking_port_v2_test.go, openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2_test.go, openstack/resource_openstack_networking_qos_dscp_marking_rule_v2_test.go, openstack/resource_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go, openstack/resource_openstack_networking_qos_policy_v2_test.go, openstack/resource_openstack_networking_router_v2_test.go, openstack/resource_openstack_networking_trunk_v2_test.go
Add new workflow for networking/neutron.
Rename a couple of FWaaS tests to be excluded from the search.
"Un-skip" tests that were failing on OpenLab but should be
passing on GH-A.
Requires: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1391
Close #1323 ( the extensions are enabled again and tests are passing )
=> [GH-A] Add new workflow for networing

openstack/import_openstack_lb_members_v2_test.go, openstack/provider_test.go, openstack/resource_openstack_lb_members_v2_test.go
testAccPreCheckOctaviaBatchMembersEnv is no longer required
and can be removed from the ci checks.
=> Remove lb_members ci check

main.go, openstack/lb_v2_shared.go, openstack/resource_openstack_lb_members_v2.go, openstack/resource_openstack_lb_members_v2_test.go, website/docs/r/lb_members_v2.html.markdown
Added the missing arguments for monitor_address and monitor_port to the lb_members_v2 resource.
This should fix my issue #1360
=> Added monitor_port and monitor_address to lb_members_v2

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_member_v2_test.go, website/docs/r/lb_member_v2.html.markdown
Added missing argument for monitor_address and monitor_port to the lb_member_v2 resource. (different than lb_members_v2)
Replaced the pools library with the one from octavia loadbalancer instead of neutron.
Doesn't seem to break functionality from my test, but happy to review this more in depth to understand the implication of such change
=> Added monitor-address and monitor-port to openstack_lb_member_v2

openstack/import_openstack_networking_port_secgroup_associate_v2_test.go, openstack/resource_openstack_networking_port_secgroup_associate_v2.go, website/docs/r/networking_port_secgroup_associate_v2.html.markdown
Add test and documentation for importing a
openstack_networking_port_secgroup_associate_v2
resource.
Close #1353
=> Import openstack_networking_port_secgroup_associate_v2

openstack/data_source_openstack_compute_limits_v2.go, openstack/data_source_openstack_compute_limits_v2_test.go, openstack/provider.go, website/docs/d/compute_limits_v2.html.markdown, website/openstack.erb
This address my comment in #1289
`openstack` command:
```sh
$ o limits show --absolute --project 16c91b6234df4cebabbe704b4a6f2083
+--------------------------+-------+
| Name                     | Value |
+--------------------------+-------+
| maxServerMeta            |   128 |
| maxPersonality           |     5 |
| totalServerGroupsUsed    |     0 |
| maxImageMeta             |   128 |
| maxPersonalitySize       | 10240 |
| maxTotalKeypairs         |   100 |
| maxSecurityGroupRules    |    20 |
| maxServerGroups          |    10 |
| totalCoresUsed           |     8 |
| totalRAMUsed             | 16384 |
| totalInstancesUsed       |     3 |
| maxSecurityGroups        |    10 |
| totalFloatingIpsUsed     |     0 |
| maxTotalCores            |    20 |
| maxServerGroupMembers    |    10 |
| …
```
=> add compute limits as a data source

.github/workflows/functional-blockstorage_v2.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
Add concurrency on github worklows that will cancel
running jobs of the same workflow and github-reference.
We often re-push changes before the jobs finish due to
minor fixes, running jobs should be cancelled and new
ones triggered
=> Update github workflows with concurrency

openstack/data_source_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2.go, website/docs/d/compute_instance_v2.html.markdown, website/docs/r/compute_instance_v2.html.markdown
Add created/updated attribute to compute instance. This is useful for us
to detecte and change another resource whenever an instance has been
updated.
Signed-off-by: Arthur Outhenin-Chalandre <arthur.outhenin-chalandre@cern.ch>
=> Add created/updated to compute instance

.github/workflows/functional-sharedfilesystem.yml
Because `MANILA_INSTALL_TEMPEST_PLUGIN_SYSTEMWIDE` defaults to true in
manila's devstack plugin [1], we're getting tempest plugin. This is
problematic for us because:
- we don't want to spend extra time installing unneeded dependencies
- this makes it more likely to break as it has been happening for wallaby
[1] https://opendev.org/openstack/manila/src/commit/205d716/devstack/settings#L208
=> Do not install tempest in sharedfilesystems jobs

website/docs/r/containerinfra_nodegroup_v1.html.markdown
Field names were incorrect.
flavor -> flavor_id,
image -> image_id
=> Fix docs  for containerinfra_nodegroup_v1

openstack/resource_openstack_containerinfra_nodegroup_v1.go
Close #1427
This should allow users to set `role`. Unfortunately the api for nodegroup is not documented but it seems to be the case that setting `role` is allowed based on code and docs linked [here](https://github.com/gophercloud/gophercloud/issues/1767).
@ozerovandrei we currently cannot test this unfortunately due to #1413 but the change is rather small.
=> User can set role on containerinfra_nodegroup

.github/workflows/functional-vpnaas.yml
neutron-vpnaas recently removed stable/ussuri and stable/train branches.
We now need to use the ussuri-eol and train-eol tags instead when pulling
from the project.
=> Fix train and ussuri vpnaas jobs

website/docs/r/containerinfra_nodegroup_v1.html.markdown
Rename 'cluster' to 'node group' in description and add more details about ID used to import nodegroup.
=> Update openstack_containerinfra_nodegroup_v1 documentation.

openstack/resource_openstack_containerinfra_nodegroup_v1.go
Fix nodegroup recreation after import due missing 'docker_volume_size' parameter while reading 'openstack_containerinfra_nodegroup_v1' resource.
=> Set missing 'docker_volume_size' parameter while reading 'openstack_containerinfra_nodegroup_v1' resource

openstack/data_source_openstack_keymanager_container_v1_test.go, openstack/data_source_openstack_keymanager_secret_v1_test.go, openstack/import_openstack_keymanager_container_v1_test.go, openstack/import_openstack_keymanager_order_v1_test.go, openstack/import_openstack_keymanager_secret_v1_test.go, openstack/resource_openstack_keymanager_container_v1_test.go, openstack/resource_openstack_keymanager_order_v1_test.go, openstack/resource_openstack_keymanager_secret_v1_test.go
Barbican has changed his default policies. Need to update
the user used in ci tests.
Close #1433
=> Change ci user to admin for barbican tests

openstack/containerinfra_shared_v1.go, openstack/resource_openstack_containerinfra_cluster_v1.go, openstack/resource_openstack_containerinfra_nodegroup_v1.go
Close #1102 
This PR should allow users to update node_count of cluster resource.
=> Fix update of node_count field for containerinfra_cluster_v1 resource and {min,max}_node_count fields for containerinfra_nodegroup_v1 resource

openstack/containerinfra_shared_v1.go, openstack/resource_openstack_containerinfra_cluster_v1.go, openstack/resource_openstack_containerinfra_nodegroup_v1.go
Close #1327
This PR should fix issue when TF try to recreate the existing cluster every time even if there are no changes to the code using '--merge-labels option.
=> Fix skipping not overridden labels uisng '--merge-labels'

openstack/db_configuration_v1.go, openstack/resource_openstack_db_configuration_v1.go, website/docs/r/db_configuration_v1.html.markdown
Close #776 
Add parameter's value conversion to bool type and new parameter that allows store parameter's value as string.
=> Fix openstack_db_configuration_v1 type mismatch for bool and string type

GNUmakefile
Acceptance tests for imports where a data source is used are failing
in terraform >= 1.3.X. Pin tf version to 1.2.9 till a fix is introduced
upstream.
RelatesTo: #1449
=> Set terraform version on acceptance tests

.github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml, scripts/acceptancetest.sh
TF version was not set on the script that is used for the ci. Additionally, set trigger for workflows when ci related scripts
are updated. Related to: #1449
=> Set terraform version on acceptance tests scripts

go.mod, go.sum, openstack/data_source_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2_test.go, website/docs/d/networking_subnet_v2.html.markdown, website/docs/r/networking_subnet_v2.html.markdown
Bump gophercloud version to include support for this. Update both the subnet resource and the data source to support using service types.
close #1443
=> Add service types to subnet resource and data source

.github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
Openstack Zed was released recently. Update all workflows to test the Zed version as well. Moreover, decrease the tested versions from master + 6 latest to master + 4 latest. This gives a wide enough testing while at the same type simplifies ci and minimizes various deprecations.
=> Update ci to include Openstack Zed

.github/workflows/functional-blockstorage_v2.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml, .github/workflows/release.yml
Various actions need to be update to avoid deprecations due to using node12 => More info here:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
=> Update various github actions to avoid deprecations

openstack/containerinfra_shared_v1.go, openstack/containerinfra_shared_v1_test.go
This PR fixes errors while updating cluster template's labels.
Current data format (request body) send to Magnum API
```
[
{
"op": "replace",
"path": "/labels",
"value": "boot_volume_size=5"
}
]
```
causes error (respond body) like below
```
{
"errors": [{
"request_id": "",
"code": "client",
"status": 400,
"title": "Couldn't apply patch '[{'path': '/labels', 'op': 'replace', 'value': 'boot_volume_size=5",
"detail": "Couldn't apply patch '[{'path': '/labels', 'op': 'replace', 'value': 'boot_volume_size=5'}]'. Reason: invalid syntax (<unknown>, line 1)",
"links": []
}
]
}
```
Valid data format:
```
[
{
"op": "replace",
"path": "/labels",
"value": "{'boot_volume_size':'5'}"
}
]
```
=> Fix update of containerinfra cluster template's labels

website/docs/r/compute_instance_v2.html.markdown, website/docs/r/networking_network_v2.html.markdown
The upbound tool named "scrape" (used in the process of generating a crossplane provider from the terraform provider) was failing when trying to convert markdown to JSON
In the case of `website/docs/r/compute_instance_v2.html.markdown`, this was the error: 
```example.hcl:5,21-22: Invalid expression; Expected the start of an expression, but found an invalid expression token.```
In the case of `website/docs/r/networking_network_v2.html.markdown` the error was:
```example.hcl:32,5-6: Invalid argument name; Argument names must not be quoted.```
Hence the fixes.
=> Fixed markdown syntax

openstack/data_source_openstack_images_image_v2.go, openstack/data_source_openstack_images_image_v2_test.go, website/docs/d/images_image_v2.html.markdown
The current implementation of `data_source_openstack_images_image_v20` only allows for setting a single `tag` attribute while the API is able to accept a list of tags to filter on.
This change allows users to directly set the `tags` attribute to a list of tags in their data source block while maintaining backwards compatibility with the existing `tag` attribute. If both are provided, the singular `tag` is simply added to the `tags` attribute before being added to the `ListOpts`.
Examples
**Original Syntax**
```hcl
data "openstack_images_image_v2" "image_1" {
tag   = "cirros-tf_1"
}
```
**New Syntax with `tags` attribute**
```hcl
data "openstack_images_image_v2" "ubuntu" {
tags = ["cirros-tf_1"]
}
```
**New Syntax using both `tag` and `tags` attribute**
```hcl
data …
```
=> Facilitate providing a list of tags in data_source_openstack_images_image_v2

openstack/data_source_openstack_images_image_ids_v2.go, openstack/data_source_openstack_images_image_ids_v2_test.go, website/docs/d/images_image_ids_v2.html.markdown
Ports change from #1462 for `openstack_images_image_ids_v2`  
Fixes #1467
Allows filtering using a list a tags by setting the `tags` attribute, while maintaining backwards compatibility with `tag` attribute.
Original Syntax
```hcl
data "openstack_images_image_ids_v2" "image_1" {
tag   = "cirros-tf_1"
}
```
New Syntax with tags attribute
```hcl
data "openstack_images_image_ids_v2" "image_1" {
tags = ["cirros-tf_1"]
}
````
New Syntax using both tag and tags attribute
```hcl
data "openstack_images_image_ids_v2" "image_1" {
tag   = "cirros-tf_1"
tags = ["cirros-tf_1"]
}
```
=> Allow providing a list of tags in data_source_openstack_images_image_ids_v2

go.mod, go.sum, openstack/data_source_openstack_containerinfra_clustertemplate_v1.go, openstack/data_source_openstack_containerinfra_clustertemplate_v1_test.go, openstack/resource_openstack_containerinfra_clustertemplate_v1.go, openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go, website/docs/d/containerinfra_clustertemplate_v1.html.markdown, website/docs/r/containerinfra_clustertemplate_v1.html.markdown
=> Added field hidden to coantainerinfra_v1_clustertemplate

openstack/data_source_openstack_images_image_v2.go, openstack/data_source_openstack_images_image_v2_test.go, website/docs/d/images_image_v2.html.markdown
Noticed that `data_source_openstack_images_image_ids_v2` has `name_regex` to filter images, while `data_source_openstack_images_image_v2` doesn't. This PR adds it, and works in the same way.
**Before:**
Exact name matching only
```hcl
data "openstack_images_image_ids_v2" "images" {
name = "Ubuntu_16.04_cloudimage_amd64"
}
```
**After:**
Partial name matching possible
```hcl
data "openstack_images_image_ids_v2" "images" {
name_regex = "^Ubuntu_16\\.04.*_amd64$"
}
```
=> Add name_regex attribute to data_source_openstack_images_image_v2

.github/workflows/functional-blockstorage_v2.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
Update devstack-action to 0.10 that uses github mirrors instead of opendev that has introduced limits on pulling repos. Moreover update links to any plugin so that it's also pulled from github mirror and not opendev
Close #1496
=> Use github mirrors instead of opendev

CHANGELOG.md, openstack/images_image_v2.go, openstack/import_openstack_images_image_v2_test.go, openstack/resource_openstack_images_image_v2.go, openstack/resource_openstack_images_image_v2_test.go, website/docs/r/images_image_v2.html.markdown
Some image are compressed and only filling Content-Type header resulting if uploading a compressed image to openstack.
With this we automatically detects and uncompress images in this case.
Example:
```
$ curl -I "https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.bz2"
HTTP/2 200
server: nginx
date: Thu, 16 Feb 2023 15:54:03 GMT
content-type: application/x-bzip2
content-length: 371535602
etag: "rq4xkz657ape"
last-modified: Wed, 15 Feb 2023 18:48:35 GMT
accept-ranges: bytes
```
Resolves #1481
=> Add decompression flag to openstack_images_image_v2 resource

.github/workflows/functional-objectstorage.yml, go.mod, go.sum, openstack/migrate_resource_openstack_objectstorage_container_v1.go, openstack/migrate_resource_openstack_objectstorage_container_v1_test.go, openstack/resource_openstack_objectstorage_container_v1.go, openstack/resource_openstack_objectstorage_container_v1_test.go, website/docs/r/objectstorage_container_v1.html.markdown
=> Swift v1: add support for new object versioning

.golangci.yml
Just in case
Reference: https://golangci-lint.run/usage/configuration/
=> Use single quotes in linter go version

openstack/data_source_openstack_keymanager_secret_v1.go, openstack/keymanager_secret_v1.go, openstack/resource_openstack_keymanager_secret_v1.go, openstack/resource_openstack_keymanager_secret_v1_test.go, website/docs/r/keymanager_secret_v1.html.markdown
Fixes #1492 
Now payload state is stored in base64 format in case when it's not the text. In these cases it's responsibility of end user to detect the encoding/content-type and call https://developer.hashicorp.com/terraform/language/functions/base64decode
Payloads with whitespaces and newlines are also supported now, e.g. passwords that have whitespace at the end.
=> keymanager v1: fix payload retrieve for binary data

openstack/lb_v2_shared.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_listener_v2_test.go
This allows setting tags for listener when using octavia. 
The change is heavily "inspired" by the tag feature used in the loadbalancer resource and therefore uses the same approach.
=> Allow settings tags for lb_listener_v2

openstack/resource_openstack_compute_instance_v2.go
=> [compute v2]: prefer cinder V3 API over V2 on import

openstack/compute_servergroup_v2.go, openstack/resource_openstack_compute_servergroup_v2.go, openstack/resource_openstack_compute_servergroup_v2_test.go, website/docs/r/compute_servergroup_v2.html.markdown
Should resolve #1143. 
Addition of `policy` and `rules` fields, which replace the `policies` field since API microversion 2.64. Support for the fields has already been added to Gophercloud.
=> Add servergroup policy and rules field support

openstack/resource_openstack_compute_servergroup_v2.go
=> [compute v2]: handle unexpected nova server groups API response

openstack/db_configuration_v1.go, openstack/db_configuration_v1_test.go
As mentioned in https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1527 go test currently fails.
This is an attempt to nil check so that it does not panic.
Closes: #1527
=> Refactor to avoid panic

openstack/resource_openstack_compute_keypair_v2.go
Trying to fix https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/677
as it seems `terraform plan` is leaking full-body private_key
```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:
- resource "openstack_compute_keypair_v2" "keypair_1" {
- id          = "prod-prod-1-keypair_1" -> null
name        = "prod-prod-1-keypair_1"
- private_key = <<-EOT
-----BEGIN RSA PRIVATE KEY-----
<skip-skip-skip-skip>
-----END RSA PRIVATE KEY-----
EOT -> null
- public_key  = "ssh-rsa <skip-skip-skip-skip> Generated-by-Nova" -> null
}
```
=> Flag private-key attribute as sensitive

website/docs/r/containerinfra_cluster_v1.html.markdown
The documentation states that changing node_count will result in the recreation of the cluster which is not valid, this patch updates the docs to match the behaviour that it will not create a new cluster.
Related: #1485
=> docs(containerinfra): update node_count

GNUmakefile, scripts/acceptancetest.sh
This removes the version pin of terraform for acceptance tests. It was introduced due to an upstream issue which led to import acceptance tests failing.
Close #1449
=> Remove tf version pinning

openstack/resource_openstack_containerinfra_nodegroup_v1.go
If the cluster attached to a node group changed, that node group
cannot be "re-attached", it should just be fully rebuilt.
=> fix(containerinfra): replace nodegroup if cluster_id changes

.github/workflows/functional-blockstorage_v2.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, openstack/provider_test.go, openstack/resource_openstack_blockstorage_volume_v3_test.go, openstack/resource_openstack_networking_trunk_v2_test.go
SkipBelow and SkipAfter ci func were not working properly
as OS_BRANCH was not in the env vars. Make it available
to all acceptance ci jobs. Moreover skip cinder multi_attach
test after zed release as it is no longer possible to do
multi_attach on a volume level.
This has to be done on volume_type basis. Related [commit](https://github.com/openstack/cinder/commit/d5a45f875a0919660df250e35c614e65a51b7038)
Close #1500
=> Fix SkipBelow and SkipAfter ci check func

website/docs/r/compute_flavor_access_v2.html.markdown, website/docs/r/compute_floatingip_associate_v2.html.markdown, website/docs/r/compute_instance_v2.html.markdown, website/docs/r/dns_recordset_v2.html.markdown, website/docs/r/dns_transfer_accept_v2.html.markdown, website/docs/r/dns_transfer_request_v2.html.markdown, website/docs/r/dns_zone_v2.html.markdown, website/docs/r/identity_user_membership_v3.html.markdown, website/docs/r/networking_router_interface_v2.html.markdown, website/docs/r/objectstorage_container_v1.html.markdown, website/docs/r/sharedfilesystem_securityservice_v2.html.markdown, website/docs/r/sharedfilesystem_share_access_v2.html.markdown, website/docs/r/sharedfilesystem_share_v2.html.markdown, website/docs/r/sharedfilesystem_sharenetwork_v2.html.markdown
"<..>" are not visible when within code blocks. Remove any "<..>" from import examples on docs
Close #1543
=> DOCS: Fix import examples

openstack/data_source_openstack_identity_project_v3.go, openstack/data_source_openstack_identity_project_v3_test.go, website/docs/d/identity_project_v3.html.markdown
This enabled adding a project data source by defining the project_id
Close #1229
=> Add project_id to data_source_openstack_identity_project_v3

openstack/resource_openstack_dns_recordset_v2.go, openstack/resource_openstack_dns_recordset_v2_test.go
The record value(s) of a recordset resource were not being read
into the state during refresh which allows configuration drift to
go undetected.
Fixes: #1564
=> include record values during openstack_dns_recordset_v2 update

openstack/compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2.go, website/docs/r/compute_instance_v2.html.markdown
Please see #1057 for detailed description.
It is not currently possible to use multiattach volumes with the `block_device` block of compute instances, as it requires compute microversion `>=2.60`. This is a major show stopper for my use case, where I need to attach such a volume to an instance *before* it boots.
~~The provider *already* uses microversion `2.67` when the `volume_type` parameter is set in the `block_device` block. Rather than adding more arbitrary checks for these edge cases, I propose we stick to a KISS philosophy by removing this check altogether, and simply pin to this "BlockDevice" microversion any time the `block_device` block is used.~~
As per a maintainer's suggestion below, I have added a `multiattach` flag to the `block_device` block, which sets the compute …
=> [compute v2] Add multiattach flag to instance block_device (#1057)

go.mod, go.sum, openstack/import_openstack_identity_inherit_role_assignment_v3_test.go, openstack/provider.go, openstack/resource_openstack_identity_inherit_role_assignment_v3.go, openstack/resource_openstack_identity_inherit_role_assignment_v3_test.go, website/docs/r/identity_inherit_role_assignment_v3.html.markdown, website/openstack.erb
This creates new identity resource for inherited roles using the OS-INHERIT keystone API. Chose to create a new resource instead of adding this functionality to existing role assignment to:
- keep the resources clean and easy
- this is a seperate api, thus i prefer a new resource to manage it
- adding it to existing assignment would require updating the resource id and could impact users
Close #1372
=> Create new identity_inherit_role_assignment_v3 resource

openstack/data_source_openstack_containerinfra_cluster_v1.go, openstack/data_source_openstack_containerinfra_cluster_v1_test.go, website/docs/d/containerinfra_cluster_v1.html.markdown
Hello,
We needed the kubeconfig attribute in order to parameter our kubernetes provider, so we implemented it.
I hope we did not miss anything, we are using it right now and it  :copyright: works on my machine :copyright: 
fix #1442
=> [containerinfra_cluster_v1] add kubeconfig to data source

openstack/resource_openstack_orchestration_stack_v1.go
Wait for UPDATE_COMPLETE in resourceOrchestrationStackV1Update. This change fixes the issue where provider does not honor  terraform parallelism option and just pushes all the stack updates at the same time causing overload.
Following test have passed: TestAccOrchestrationV1Stack_update, TestAccOrchestrationV1Stack_basic
=> Wait for Orchestration Stack to update

go.mod, go.sum, openstack/images_image_v2.go, openstack/resource_openstack_images_image_v2.go
=> [glance v2]: add support for xz image decompression

openstack/resource_openstack_images_image_v2.go, openstack/resource_openstack_keymanager_container_v1.go
This is a minor change to explicitly use the `ExtractErr()` call to fetch errors.
=> Explicitly use ExtractErr() call instead of accessing res.Err

openstack/fw_group_v2.go, openstack/import_openstack_fw_group_v2_test.go, openstack/provider.go, openstack/resource_openstack_fw_group_v2.go, openstack/resource_openstack_fw_group_v2_test.go, openstack/resource_openstack_fw_policy_v2.go, openstack/resource_openstack_fw_rule_v2.go, website/docs/r/fw_group_v2.html.markdown, website/docs/r/fw_policy_v2.html.markdown, website/openstack.erb
Add resourceFWGroupV2 CRUD
Add resourceFWGroupV2 tests
Add resourceFWGroupV2 docs
Add import_openstack_fw_group_v2_test
Enable openstack_fw_group_v2 in provider.go
Close part of #115
=> [FWaaS_V2]: Add FW Group V2 resource

openstack/data_source_openstack_fw_group_v2.go, openstack/data_source_openstack_fw_group_v2_test.go, openstack/provider.go, website/docs/d/fw_group_v2.html.markdown, website/openstack.erb
Add dataSourceFWGroupV2 with tests
Add docs
Enable openstack_fw_group_v2 in provider.go
Close #115
=> [FWaaS_V2] Add FW Group V2 datasource

openstack/data_source_openstack_blockstorage_snapshot_v2.go, openstack/data_source_openstack_blockstorage_volume_v2.go, openstack/data_source_openstack_fw_policy_v1.go, openstack/resource_openstack_blockstorage_quotaset_v2.go, openstack/resource_openstack_blockstorage_volume_attach_v2.go, openstack/resource_openstack_blockstorage_volume_v1.go, openstack/resource_openstack_blockstorage_volume_v2.go, openstack/resource_openstack_fw_firewall_v1.go, openstack/resource_openstack_fw_policy_v1.go, openstack/resource_openstack_fw_rule_v1.go, openstack/resource_openstack_lb_member_v1.go, openstack/resource_openstack_lb_monitor_v1.go, openstack/resource_openstack_lb_pool_v1.go, openstack/resource_openstack_lb_vip_v1.go
Various resources have been documented as deprecated. Additionally add a deprecation warning for the user.
The related resources have been deprecated on openstack side for many releases now. We do not have any deprecation policy in place and there is no big harm keeping the code (if it doesn't block newer features etc which typically it doesn't). Nonetheless we do not have any ci coverage for these resources for years and it is good to warn the user that these are deprecated.
=> Add deprecation warning to various resources

docs/resources/compute_interface_attach_v2.md, docs/resources/compute_volume_attach_v2.md
See #1585 (50b9dacd9d5b1178b9932786d188e0ba940cd072) for background.
These splat uses were ommitted from the original patch because they're slightly more complicated and easier to just think about separately.
=> Modernize splat syntax-related examples

openstack/containerinfra_shared_v1.go, openstack/resource_openstack_containerinfra_cluster_v1.go
This should hopefully stop the cluster from being recreated and instead it will trigger an upgrade if the `cluster_template_id` is changed.
=> fix(magnum): enable upgrades with cluster_template_id changes

openstack/resource_openstack_networking_network_v2.go
`Segmentation_id` on openstack_networking_network_v2:
1. is statically defined by the user: in this case any changes on it should trigger a recreation of the network.
2. is not defined by the user but neutron has an available pool: in this case, neutron picks a segmentation_id from the pool and allocates it for this network. Thus the value is computed by neutron. 
Because use-case 1 AND 2 are valid (depending on the cloud configuration) we cannot use something like [DiffSuppressFunc](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#diffsuppressfunc). Setting it as `computed` should work in both cases. 
Unfortunately i dont think we can easily test this in the ci.
Close #1560
=> Set segments.segmentation_id as computed on networks

.github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-fwaas_v2.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
Openstack Bobcat was released 04/10. Add it to the ci jobs and remove Xena to cover the 4 latest Openstack releases on the ci
=> Add bobcat to ci jobs and remove xena

openstack/data_source_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2.go
The images API available in the Nova API has been deprecated and is currently only a proxy call. This migrates the provider over towards using the Glance API directly.
=> Upgrade to use the Glance API instead of Nova for images

.github/workflows/functional-blockstorage_v2.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-fwaas_v2.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
Currently workflows are triggered also on docs updates. Update workflows to trigger them only when a resource is actually updated or go.mod changed
=> Update ci triggers to exclude docs

docs/resources/networking_port_v2.md
Add note on openstack_networking_port_v2 docs to
notify users on how to ensure a port gets an IP
by adding a depedency to a subnet resource.
Moreover update the example usage to have an example like this.
Relates to: #1606
=> Update port docs for subnet depedency

docs/resources/blockstorage_volume_v3.md, openstack/resource_openstack_blockstorage_volume_v3.go, openstack/resource_openstack_blockstorage_volume_v3_test.go
Multiattach volumes has been deprecated since Queens and completely removed on Bobcat. Add deprecation notice on the argument and set the tests to skip
=> Add deprecation notice on multiattach volumes

docs/resources/networking_port_v2.md, openstack/resource_openstack_networking_port_v2_test.go
Binding:vnic_type can only be updated on unbound ports. Fix ci tests to not try and update it when the port is bound. Update docs as well to add info on the limitation of the update operation
This is based on api [docs](https://docs.openstack.org/api-ref/network/v2/index.html#update-port) and the logs from the failing ci:
> 2023-12-01T01:47:55.1437727Z   | Error: Error updating OpenStack Neutron Port: Expected HTTP response code [200 201] when accessing [PUT http://10.1.0.99:9696/networking/v2.0/ports/986c02ce-7133-4f36-b450-2596f058fef3], but got 409 instead
2023-12-01T01:47:55.1440317Z   | {"NeutronError": {"type": "PortInUse", "message": "Unable to complete operation on port 986c02ce-7133-4f36-b450-2596f058fef3 for network f8cb73ba-11bd-4a72-8b31-2aac3d19fe1c. Port already has an …
=> Fix ci tests for binding:vnic_type on port resource

docs/resources/networking_secgroup_rule_v2.md
When you supply the full port-range 1:65535 neutron does something "clever" and sets port_range_min and port_range_max to None. So when the provider goes back to read out the port-range it comes out 0:0 instead of the expected 1:65535, and the rule gets replaced.
Every.
Single.
Time.
The solution of setting min and max to 0 is staring you right in the face. But documenting this strange exception would be beneficial to denser minds such as mine.
=> Document the secgroup_rule port-range exception

docs/resources/compute_floatingip_associate_v2.md, docs/resources/compute_floatingip_v2.md, docs/resources/compute_secgroup_v2.md, openstack/resource_openstack_compute_floatingip_associate_v2.go, openstack/resource_openstack_compute_floatingip_associate_v2_test.go, openstack/resource_openstack_compute_floatingip_v2.go, openstack/resource_openstack_compute_floatingip_v2_test.go, openstack/resource_openstack_compute_secgroup_v2.go, openstack/resource_openstack_compute_secgroup_v2_test.go
Mark compute_floatingip_associate_v2, compute_floatingip_v2, compute_secgroup_v2 as deprecated. Add a deprecation message to point to the related neutron resources to be used instead. Move their doc pages into the `Deprecated` subcategory.
=> Deprecate various nova resources

docs/resources/db_instance_v1.md, go.mod, go.sum, openstack/resource_openstack_db_instance_v1.go, openstack/resource_openstack_db_instance_v1_test.go
Reverting the additon of availability_zone to db_instance_v1.
This has been faulty as it was not written on the state.
Explained in the discussion here: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1647
=> Revert availability zone on db_instance_v1

docs/data-sources/blockstorage_volume_v3.md, openstack/data_source_openstack_blockstorage_volume_v3.go, openstack/data_source_openstack_blockstorage_volume_v3_test.go, openstack/resource_openstack_blockstorage_volume_v3_test.go
Hello,
I am currently reworking the terraform setup for the openstack cloud at my work. While figuring out how to best handle long-term volumes, like databases that should ideally not be deleted recreated if something changes, I noticed a discrepancy between the _**resource** openstack_blockstorage_volume_v3_ and the _**data source** openstack_blockstorage_volume_v3_:
The result of creating a volume via terraform has the attribute "attachment", which exposes the instance and the location on which the Volume is mounted (e.g. /dev/vdb on Linux) See [documentation here.](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/blockstorage_volume_v3#attributes-reference)
However, when creating the volume manually outside of terraform, and using the …
=> data_source_blockstorage_volume_v3: Add Attachment Information

docs/resources/blockstorage_volume_v3.md, openstack/blockstorage_volume_v3.go, openstack/provider_test.go, openstack/resource_openstack_blockstorage_volume_v3.go, openstack/resource_openstack_blockstorage_volume_v3_test.go
Add support for volumes to be created from a backup_id. Moreover add a `conflictsWith` for the different type of sources that a volume can be created from.
Based on #1637  and work from @ZdenekPesek.
Close #1637 
Close #1636
=> Add backup_id to openstack_blockstorage_volume_v3

openstack/provider.go, openstack/resource_openstack_lb_l7policy_v2.go, openstack/resource_openstack_lb_l7rule_v2.go, openstack/resource_openstack_lb_listener_v2.go, openstack/resource_openstack_lb_loadbalancer_v2.go, openstack/resource_openstack_lb_member_v2.go, openstack/resource_openstack_lb_monitor_v2.go, openstack/resource_openstack_lb_pool_v2.go
Add a deprecation message to all lb resources that support neutron-lbaas. Moreover, add a deprecation message to the `use_octavia` flag of the provider.
The `members` and `quota` resource has not been included as they work only for octavia
Relates to #1638
=> Add deprecation warning for neutron-lbaas

CHANGELOG.md, openstack/provider.go
Clarify provider deprecation message for option `use_octavia`. Add info on how various users will be affected. Specifically:
- users not using LB => ignore message
- users using octavia => will have to update provider config if `use_octavia` is defined
- users using neutron-lbaas => will have to upgrade/migrate to octavia Lastly, upgrade CHANGELOG.md to cut patch release
Close #1664
=> Update 'use_octavia' deprecation message

docs/resources/images_image_v2.md, openstack/resource_openstack_images_image_v2.go
Remove deprecated update_at in favor of updated_at.
Part of #1660
=> Remove deprecated update_at from images_image_v2

openstack/data_source_openstack_networking_subnet_v2.go
dhcp_disabled has been deprecated in favor of dhcp_enabled. Remove it from the provider
Part of #1660
=> Remove dhcp_disabled from data_source_openstack_networking_subnet_v2

docs/data-sources/images_image_ids_v2.md, docs/data-sources/images_image_v2.md, openstack/data_source_openstack_images_image_ids_v2.go, openstack/data_source_openstack_images_image_ids_v2_test.go, openstack/data_source_openstack_images_image_v2.go, openstack/images_image_v2.go, openstack/images_image_v2_test.go
Glance data sources allowed sorting in 2 different ways. Sort or sort_key + sort_dir. Sort can fully replace the sort_key + sort_dir combination and is capable of providing multiple sorting criteria. sort_key and sort_dir are marked as deprecated on the provider. Update glance data sources to use solely `sort` and remove support for the deprecated (in the provider) sort_key + sort_dir
Part of #1660
=> Remove deprecated sort_key and sort_dir from glance data sources

docs/data-sources/networking_floatingip_v2.md
Hi! 
openstack_networking_floatingip_v2 pool argument is not pool's/network's name
Gophercloud expects network's UUID
https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/42ad5bae86f4f12a9d319098b8d866f5d8727814/openstack/data_source_openstack_networking_floatingip_v2.go#L105
https://pkg.go.dev/github.com/gophercloud/gophercloud@v1.9.0/openstack/networking/v2/extensions/layer3/floatingips#ListOpts.FloatingNetworkID
Thank you
=> Fix networking_floatingip_v2 pool argument reference

docs/resources/lb_quota_v2.md, openstack/resource_openstack_lb_quota_v2.go
Remove note from docs as neutron-lbaas support will be dropped. Moreover update the client of the resource to only use octavia.
Part of #1638
=> Update lb_quota to drop neutron-lbaas

docs/resources/lb_members_v2.md, openstack/resource_openstack_lb_members_v2.go
lb_members_v2 did not support neutron-lbaas but it used various libraries and functions that used it. Update it to use octavia-only libraries/functions.
Part of: #1638 
Requires #1655 (will rebase after it is merged )
=> Remove neutron-lbaas from lb_members_v2

docs/resources/networking_subnet_v2.md, openstack/networking_subnet_v2.go, openstack/resource_openstack_networking_port_v2_test.go, openstack/resource_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2_test.go, openstack/resource_openstack_networking_tags_v2_test.go
Deprecated allocation_pools is removed in favor of allocation_pool
=> Remove allocation_pools from networking_subnet_v2

docs/resources/networking_subnet_v2.md, openstack/networking_subnet_v2.go, openstack/networking_subnet_v2_test.go, openstack/resource_openstack_networking_subnet_v2.go
Remove host_route from networking_subnet_v2 in favor of openstack_networking_subnet_route_v2
=> Remove host_route from networking_subnet_v2

.github/workflows/functional-loadbalancer.yml, docs/index.md, openstack/data_source_openstack_lb_flavor_v2_test.go, openstack/import_openstack_lb_members_v2_test.go, openstack/lb_v2_shared.go, openstack/provider.go, openstack/provider_test.go, openstack/resource_openstack_lb_listener_v2_test.go, openstack/resource_openstack_lb_loadbalancer_v2_test.go, openstack/resource_openstack_lb_member_v2_test.go, openstack/resource_openstack_lb_members_v2_test.go, openstack/resource_openstack_lb_monitor_v2_test.go, openstack/resource_openstack_lb_pool_v2_test.go, openstack/resource_openstack_lb_quota_v2.go
Remove deprecation message and `use_octavia` option from client. Update docs and ci tests.
Part of #1638
=> Deprecate support for neutron lbaas

.github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-fwaas_v2.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
Zed has reached EOM status and is no longer maintained. CI jobs are already failing. Remove zed coverage from ci
=> Remove zed ci jobs as it has reached EOM status

docs/resources/compute_instance_v2.md, docs/resources/compute_servergroup_v2.md
docs/resources/compute_instance_v2.md: Add reference to servergroups resource docs for instance resource attribute
docs/resources/compute_servergroup_v2.md: Add reference to instance resource attribute in overview
=> Add references between compute_servergroup and compute_instance docs

docs/resources/compute_volume_attach_v2.md, openstack/compute_instance_v2.go, openstack/resource_openstack_compute_volume_attach_v2.go, openstack/resource_openstack_compute_volume_attach_v2_test.go
The API is 
https://docs.openstack.org/api-ref/compute/#attach-a-volume-to-an-instance
and the opts in gophercloud is 
https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/volumeattach/requests.go#L34
=> Add volume attach tag with nova microversion 2.49

openstack/resource_openstack_containerinfra_cluster_v1.go
Since  1.10 Magnum allow cluster creation with worker node count set to 0. This one  set the correct microversion to allow node_count=0 on cluster update.
=> Allow Magnum node_count=0 for cluster update

docs/resources/lb_l7policy_v2.md, openstack/resource_openstack_lb_l7policy_v2.go, openstack/resource_openstack_lb_l7policy_v2_test.go
Add support for redirect_prefix and redirect_http_code attributes to openstack_lb_l7_policy_v2.
Close https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1347
=> Add redirect_prefix and redirect_http_code to l7policy

go.mod, main.go, openstack/provider_test.go
Update module name to v2 to match GitHub versioning
Fixes #1727
=> Use Go standard module naming

docs/resources/lb_l7rule_v2.md, openstack/resource_openstack_lb_l7rule_v2.go
Add support for types "SSL_CONN_HAS_CERT", "SSL_VERIFY_RESULT", "SSL_DN_FIELD" on resource openstack_lb_l7rule_v2
=> Add support for more types for lb_rule_v2

openstack/resource_openstack_identity_endpoint_v3.go, openstack/resource_openstack_identity_endpoint_v3_test.go
The `url` parameter in resource_openstack_identity_endpoint_v3 may contain non-url encoded strings such as `%(tenant_id)s`. 
Ref: https://docs.openstack.org/ocata/admin-guide/networking-auth.html
This means that url validation may prevent normal configurations.
* Delete URL validation func
* Add % string to test case
=> Fix: Delete URL validation from identity_endpoint parameters

docs/data-sources/networking_subnet_ids_v2.md, docs/data-sources/networking_subnet_v2.md, docs/resources/networking_subnet_v2.md, go.mod, go.sum, openstack/data_source_openstack_networking_subnet_ids_v2.go, openstack/data_source_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2.go
Add `dns_publish_fixed_ip` argument to the `openstack_networking_subnet_v2` resource and `openstack_networking_subnet_v2`, `openstack_networking_subnet_ids_v2` data sources.
Resolves #1730
=> [networking]: add dns_publish_fixed_ip to subnet argument

docs/data-sources/images_image_ids_v2.md, docs/data-sources/images_image_v2.md, openstack/data_source_openstack_images_image_ids_v2.go, openstack/data_source_openstack_images_image_v2.go
Add `container_format` and `disk_format` filters to the `openstack_images_image_v2` data source
Add `container_format` , `disk_format` and `hidden` filters to the `openstack_images_image_ids_v2` data source
=> [glance]: add disk and container formats filter to image data sources

openstack/util.go, openstack/util_test.go
This PR enforces bool type for key value `value_specs`  which correspond to `"true"` or `"false"` strings.
Resolves #1730
=> [networking]: enforce bool type for bool "value_specs"

.goreleaser.yml, openstack/provider.go
Resolves #604
Depends on #1759 
This change will build a user-agent header like:
`
User-Agent: HashiCorp Terraform/1.4.4 (+https://www.terraform.io) Terraform Plugin SDK/2.30.0 Terraform Provider OpenStack/2.0.0 gophercloud/v1.13.0
`
=> [core]: add provider version to user-agent

.github/workflows/functional-bgpvpn.yml, openstack/resource_openstack_bgpvpn_network_associate_v2_test.go, openstack/resource_openstack_bgpvpn_port_associate_v2.go, openstack/resource_openstack_bgpvpn_port_associate_v2_test.go, openstack/resource_openstack_bgpvpn_router_associate_v2.go, openstack/resource_openstack_bgpvpn_router_associate_v2_test.go, openstack/resource_openstack_bgpvpn_v2_test.go
Without the `GetOkExists` port or router associations cannot be created without the advertisements.
Depends on #1759
ref #1188
https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1738#discussion_r1683010644
https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1738#discussion_r1683026442
=> [bgpvpn]: use getOkExists helper to detect bool arguments

docs/data-sources/networking_secgroup_v2.md, docs/resources/networking_secgroup_v2.md, openstack/data_source_openstack_networking_secgroup_v2.go, openstack/data_source_openstack_networking_secgroup_v2_test.go, openstack/resource_openstack_networking_secgroup_v2.go, openstack/resource_openstack_networking_secgroup_v2_test.go
Resolves #1735 
Depends on #1759
@nikParasyr this is a good example of why we need to use `GetOkExists`. If you use just `GetOk`, then tests will fail for both resources and data sources.
ref #1188
=> [neutron]: add stateful argument to security groups

docs/guides/upgrade-guide-version-2.md
Module version was updated to v2 in the v2.1.0 release. Add a note on the upgrade note to clarify this for the downstream users.
Related to: #1727 #1729
=> Add note to update guide for module version

docs/resources/dns_zone_v2.md
Importing a dns_zone_v2 resource with a project_id requires using ":" as a separator. The docs refactor in e1a17df3c9eccc8bde0cefc378f5d9de72cf61df mistakenly replaced the ":" with a "/". This commit reverts that mistake.
=> Fix syntax for importing dns_zone with project_id

docs/resources/dns_recordset_v2.md, openstack/resource_openstack_dns_recordset_v2.go
The openstack API requires the zone ID in the API endpoint to operatate recordsets.
The project ID may be required as well because the special nature of the Designate authentication, to set the X-Auth-Sudo-Tenant-ID header.
=> dns_recordset: fix zone ID and project ID handling for import workflows

docs/data-sources/identity_project_ids_v3.md, openstack/data_source_openstack_identity_projects_v3.go, openstack/data_source_openstack_identity_projects_v3_test.go, openstack/provider.go
Allowing to get list of projects, it's useful when you have to apply certain role assignments to certain group of projects
=> add openstack_identity_project_ids_v3 datasource

docs/resources/compute_instance_v2.md
**Description:**
This pull request fixes an issue with the `resource` and `floating_ip` name in the `openstack_networking_floatingip_associate_v2` resource in the Terraform OpenStack provider `compute_instance_v2` documentation. The original configuration had the `resource name` and `floating_ip name` incorrectly swapped, which caused issues when associating the floating IP to the correct port.
=> fix: correct resource and floating_ip names in floating IP association

.github/workflows/functional-bgpvpn.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-containerinfra.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-fwaas_v2.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml
OpenStack 2024.2 (Dalmatian) has been released recently (2024-10-02).
This PR enables the build for OpenStack Dalmatian to the GitHub Actions workflows.
=> [GH-A] Add dalmatian jobs to ci

.github/workflows/golangci-lint.yml, .golangci.yml
Changelog: https://github.com/golangci/golangci-lint/compare/v1.54.2...v1.61.0
=> [GH-A] Bump golangci-lint version to v1.61

.goreleaser.yml, terraform-registry-manifest.json
Goal of this PR is to add the Terraform Registry manifest file and include it in the goreleaser configuration.
> While not strictly necessary for publishing protocol version 5 providers as the Terraform Registry currently defaults to that version when a manifest file is not found in the release assets, this change prepares future projects for the ability to configure an existing manifest file rather than need to discover this configuration later on.
See
* https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/terraform-registry-manifest.json
* https://github.com/hashicorp/terraform-provider-scaffolding/commit/44f39a790c003f49bbf75a2a7f91d64e6e0bf022
=> Add Terraform Registry manifest file and include in goreleaser configuration

.github/workflows/functional-bgpvpn.yml, .github/workflows/functional-blockstorage_v3.yml, .github/workflows/functional-compute.yml, .github/workflows/functional-containerinfra.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-fwaas_v2.yml, .github/workflows/functional-identity.yml, .github/workflows/functional-images.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-networking.yml, .github/workflows/functional-objectstorage.yml, .github/workflows/functional-orchestration.yml, .github/workflows/functional-sharedfilesystem.yml, .github/workflows/functional-vpnaas.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml, .golangci.yml
I noticed that 2 GitHub Actions workflows were still using Go 1.20 for builds.
To address this, I propose updating the workflows to leverage the `go-version-file` property of the `actions/setup-go@v5` action. This property allows the action to automatically determine the Go version to use based on the version specified in the `go.mod` file.
This approach is recommended in the [Terraform Provider Scaffolding guide](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml#L33).
Additionally, we can apply a similar improvement for golangci-lint by removing the  `.run.go` property. This will ensure that golangci-lint uses the Go version specified in the `go.mod` file, further aligning the versions across the project.
=> Use Go version from the go.mod file

openstack/data_source_openstack_compute_hypervisor_v2.go, openstack/data_source_openstack_compute_hypervisor_v2_test.go
this should a allow to test `openstack_compute_hypervisor_v2` data source with devstack, when there is only one hypervizor available.
=> [compute] mark hostname argument optional in hypervisor data source

docs/resources/compute_instance_v2.md, openstack/compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2.go, openstack/resource_openstack_compute_instance_v2_test.go
Issue: #1745
This pull request adds the ability to specify `hypervisor_hostname` during Compute Instance creation in order to support OpenStack Nova API microversion >2.74. 
change :
- Added `hypervisor_hostname` to the resource schema.
- Introduced an acceptance test to verify that the `hypervisor_hostname` parameter is correctly processed.
Ad-hoc Test Results:
In our local OpenStack (DevStack) environment, we confirmed that:
- The `hypervisor_hostname` is correctly included in the API request during Compute Instance creation.
- There are no adverse effects on existing functionalities (e.g., instance creation and updates).
=>  Add `hypervisor_hostname` Option to Compute Instance

docs/resources/blockstorage_quotaset_v3.md, openstack/resource_openstack_blockstorage_quotaset_v3.go
This is a copy of #1316 for the blockstorage quotaset, as the issue is also present there (right now quotas are set to 0 if not set. This is documented, but not intuitive behavior). The fix seems straightforward.
There are 4 quota resources for which this behavior is different:
- `resource_openstack_blockstorage_quotaset_v3`: Fixed with this PR
- `resource_openstack_compute_quotaset_v2`: Fixed with #1304, however the [docs](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/docs/resources/compute_quotaset_v2.md?plain=1#L19) have not been updated for that
- `openstack_networking_quota_v2`: Fixed with #1316, however the [docs](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/docs/resources/networking_quota_v2.md?plain= …
=> Fix all-in quota creation for resource_openstack_blockstorage_quotaset_v3

openstack/resource_openstack_networking_router_interface_v2.go
This should fix `TestAccNetworkingV2RouterInterface_v6_subnet` test, when multiple router interfaces are created in parallel causing `PortNotFound`
=> [neutron] lock routerID on parallel router interfaces creation

openstack/provider_test.go
Resolves #1847 
fixes issues with service type aliases in devstack environment with the following catalog:
```
$ openstack catalog list
+--------------------+--------------------+----------------------------------------------------------------------------+
| Name               | Type               | Endpoints                                                                  |
+--------------------+--------------------+----------------------------------------------------------------------------+
| manila             | share              | RegionOne                                                                  |
|                    |                    |   public: http://10.180.142.47/share/v1/f8ec9151c3eb4ed488668bf05f3784af   |
|                    |                    | …
```
=> [manila] [tests] enforce sharev2 manila client service type

.github/workflows/functional-containerinfra.yml, .github/workflows/functional-dns.yml, .github/workflows/functional-keymanager.yml, .github/workflows/functional-loadbalancer.yml, .github/workflows/functional-sharedfilesystem.yml
This hack is used for services, which haven't yet migrated to uwsgi module path.
see also https://bugs.launchpad.net/devstack/+bug/2109604
=> tests: fix devstack functional tests

docs/resources/vpnaas_ike_policy_v2.md, docs/resources/vpnaas_ipsec_policy_v2.md, openstack/resource_openstack_vpnaas_ike_policy_v2.go, openstack/resource_openstack_vpnaas_ipsec_policy_v2.go
For VPNaaS IKE policies and IPSEC policies several choices for encryption algorithms, auth algorithms and PFS modes have been added.
Encryption algorithms: add AES CCM mode and AES GCM mode variants for 128/192/256 bit keys and 8/12/16 octet ICVs. Add AES CTR modes for 128/192/256 bit keys.
Auth algorithms: add aes-xcbc and aes-cmac.
PFS: add Diffie Hellman groups 15 to 31.
Requires updating gophercloud to v2.7.0.
Closes: #1850
=> vpnaas: add support for more ciphers (auth, encryption, pfs modes)

openstack/import_openstack_blockstorage_volume_v3_test.go, openstack/resource_openstack_blockstorage_volume_v3.go
This should fix the problem with image_id that was not imported into the state by adding it in the importing process. But this comes with two catches:
- The first one happens when image_id and at other id is present at the same time because of OpenStack keeping ``ImageMetadata`` when using a snapshot or another volume as base, therefore making a conflict who the two ids. To make sure that they are not conflicting each other, image_id is only set if the other ids are not present.
- As of today, OpenStack are accepting an image name on image_id field as there are resolving it internally[1]. But in this scenario, as the import function imports the ID and not the name in ``image_id`` field, Terraform will try to force-recreate the volume when applying. For a workaround, user should be using …
=> fix(openstack_blockstorage_volume_v3) : Allow image_id to be imported when other ids are not present

docs/data-sources/loadbalancer_flavor_v2.md, openstack/data_source_openstack_lb_flavor_v2.go, openstack/data_source_openstack_loadbalancer_flavor_v2.go, openstack/data_source_openstack_loadbalancer_flavor_v2_test.go, openstack/provider.go
loadbalancer_flavor_v2 data source should be deprecated in favor of lb_flavor_v2. Add deprecation message to loadbalancer_flavor_v2. Create lb_flavor_v2 data source re-using existing code.
Partially implements: #1796
@kayrus didnt add a guide as this is a data source so there is no need to import really
=> Deprecate loadbalancer_flavor_v2 data source

docs/data-sources/networking_subnet_ids_v2.md, docs/data-sources/networking_subnet_v2.md, docs/resources/networking_subnet_v2.md, openstack/data_source_openstack_networking_subnet_ids_v2.go, openstack/data_source_openstack_networking_subnet_v2.go, openstack/resource_openstack_networking_subnet_v2.go
Part of the #1812 
This PR doesn't include tests because gophercloud doesn't yet support network segments. But setting the subnet's `segment_id` should be possible, if you know the corresponding ID.
=> networking: add segment_id argument for subnets
