terraform-provider-openstack/terraform-provider-openstack

openstack/resource_openstack_lb_pool_v1.go

This one has been deprecated for like 3 releases now.
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccLBV1Pool -timeout 120m
=== RUN   TestAccLBV1Pool_importBasic
--- PASS: TestAccLBV1Pool_importBasic (47.05s)
=== RUN   TestAccLBV1Pool_basic
--- PASS: TestAccLBV1Pool_basic (48.83s)
=== RUN   TestAccLBV1Pool_fullstack
--- PASS: TestAccLBV1Pool_fullstack (151.26s)
=== RUN   TestAccLBV1Pool_timeout
--- PASS: TestAccLBV1Pool_timeout (47.48s)
=== RUN   TestAccLBV1Pool_updateMonitor
--- PASS: TestAccLBV1Pool_updateMonitor (51.25s)
PASS
ok      github.com/terraform-providers/terraform-provider-openstack/openstack   345.896s
```

LBaaS v1: Remove members from pool

---

openstack/import_openstack_blockstorage_volume_v1_test.go
openstack/import_openstack_dns_recordset_v2_test.go
openstack/import_openstack_dns_zone_v2_test.go
openstack/import_openstack_lb_member_v1_test.go
openstack/import_openstack_lb_monitor_v1_test.go
openstack/import_openstack_lb_pool_v1_test.go
openstack/import_openstack_lb_vip_v1_test.go
openstack/provider_test.go
openstack/resource_openstack_blockstorage_volume_v1_test.go
openstack/resource_openstack_compute_instance_v2_test.go
openstack/resource_openstack_dns_recordset_v2_test.go
openstack/resource_openstack_dns_zone_v2_test.go
openstack/resource_openstack_lb_member_v1_test.go
openstack/resource_openstack_lb_monitor_v1_test.go
openstack/resource_openstack_lb_pool_v1_test.go
openstack/resource_openstack_lb_vip_v1_test.go
test-infra/standard/aws/main.tf
test-infra/standard/aws/packer/packstack-standard.json
test-infra/standard/files/deploy.sh
test-infra/standard/files/packstack-answers.txt
test-infra/standard/files/rc.local

This commit contains the initial changes required to get CI testing up and running. There might be some minor changes after this.

Initial Changes for CI Testing

---

openstack/data_source_openstack_images_image_v2.go
openstack/data_source_openstack_images_image_v2_test.go
openstack/provider_test.go
openstack/resource_openstack_fw_firewall_v1.go
openstack/resource_openstack_fw_firewall_v1_test.go
openstack/resource_openstack_fw_rule_v1.go
openstack/resource_openstack_networking_network_v2_test.go
openstack/resource_openstack_objectstorage_container_v1_test.go

This PR has several small commits which fix errors found in the CI environment.

Acceptance test fixes

---

website/docs/r/compute_volume_attach_v2.html.markdown

Compute v2: Adding documentation on attaching multiple volumes to an instance

---

openstack/resource_openstack_networking_secgroup_v2.go

Update security group description rather than name.

---

openstack/config.go
openstack/import_openstack_identity_project_v3_test.go
openstack/provider.go
openstack/resource_openstack_identity_project_v3.go
openstack/resource_openstack_identity_project_v3_test.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/projects/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/projects/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/projects/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/vendor.json
website/docs/r/identity_project_v3.html.markdown
website/openstack.erb

This commit adds initial support for OpenStack Identity resources.
It also adds the openstack_identity_project_v3 resource.

New Resource: openstack_identity_project_v3

---

openstack/import_openstack_identity_user_v3_test.go
openstack/provider.go
openstack/resource_openstack_identity_user_v3.go
openstack/resource_openstack_identity_user_v3_test.go
vendor/github.com/gophercloud/gophercloud/internal/pkg.go
vendor/github.com/gophercloud/gophercloud/internal/util.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/urls.go
website/docs/r/identity_user_v3.html.markdown
website/openstack.erb

New Resource: openstack_identity_user_v3

---

openstack/resource_openstack_lb_loadbalancer_v2.go

Lower default timeouts for LBaaS operations

---

website/docs/r/lb_listener_v2.html.markdown

LBaaS v2: TLS and SNI doc update

---

openstack/provider.go
openstack/resource_openstack_compute_flavor_v2.go
openstack/resource_openstack_compute_flavor_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/urls.go
vendor/vendor.json
website/docs/r/compute_flavor_v2.html.markdown
website/openstack.erb

Add openstack_compute_flavor_v2 resource

---

openstack/lb_v2_shared.go

Running against an OpenStack Liberty system, in the Neutron lbaasv2 API, pools contain the listener id, but not the load balancer id. Apparently, this only changed when the lbaasv2 API moved into the Octavia project.
This was no problem in tf 0.9.x as the openstack provider did not check the load balancer state at all after pool creation.
We executed the pool tests against a Liberty system and they ran green with this fix and red without.
Fixes #77.
Signed-off-by: David Ansari <david.ansari@sap.com>
Signed-off-by: Tom Kiemes <tom.kiemes@sap.com>

Find load balancer for pool via listener

---

website/docs/r/networking_port_v2.html.markdown

Clarify the expected behavior for `ip_address`

---

openstack/resource_openstack_networking_router_v2.go

Fixes unexpected change of region in openstack_networking_router_v2

---

openstack/import_openstack_networking_router_v2_test.go
openstack/resource_openstack_networking_router_v2.go
website/docs/r/networking_router_v2.html.markdown

Networking v2: Router import support

---

openstack/import_openstack_networking_router_interface_v2_test.go
openstack/resource_openstack_networking_router_interface_v2.go
website/docs/r/networking_router_interface_v2.html.markdown

Networking v2: Router Interface import support

---

openstack/compute_instance_v2_networking.go

A previous patch which fixed detection of IPv4/IPv6 NICs created
a regression bug where instances with multiple NICs on the same
network would not be correctly detected.
This fixes the bug by correlating IPv4 and IPv6 addresses by MAC
address.

Compute v2: Fix for Instance NICs

---

openstack/data_source_openstack_images_image_v2.go
openstack/data_source_openstack_images_image_v2_test.go
openstack/resource_openstack_images_image_v2.go
openstack/resource_openstack_images_image_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
vendor/vendor.json

Images v2: Properties

---

openstack/resource_openstack_lb_loadbalancer_v2.go
openstack/resource_openstack_networking_port_v2.go
openstack/resource_openstack_networking_port_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
vendor/vendor.json
website/docs/r/networking_port_v2.html.markdown

@fatmcgav This fixes a bug I recently found in Gophercloud which explains some oddities we've seen with ports and allowed address pairs. Let me know if these changes check out with your cloud.
For #24

Port fixes

---

openstack/data_source_openstack_networking_subnet_v2.go
openstack/data_source_openstack_networking_subnet_v2_test.go
openstack/provider.go
website/docs/d/networking_subnet_v2.html.markdown
website/openstack.erb

This commit adds the `openstack_networking_subnet_v2` data source
which is able to query for a subnet based on given parameters.
Fixes #129 
/cc @mcanevet

Networking v2: Add Subnet Data Source

---

vendor/github.com/gophercloud/gophercloud/STYLEGUIDE.md
vendor/github.com/gophercloud/gophercloud/auth_options.go
vendor/github.com/gophercloud/gophercloud/doc.go
vendor/github.com/gophercloud/gophercloud/endpoint_search.go
vendor/github.com/gophercloud/gophercloud/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
vendor/github.com/gophercloud/gophercloud/openstack/client.go
vendor/github.com/gophercloud/gophercloud/openstack/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/github.com/gophercloud/gophercloud/openstack/utils/choose_version.go
vendor/github.com/gophercloud/gophercloud/params.go
vendor/github.com/gophercloud/gophercloud/results.go
vendor/github.com/gophercloud/gophercloud/service_client.go
vendor/vendor.json

This commit updates gophercloud to handle some authentication
changes in the latest version of OpenStack.

vendor: Updating gophercloud

---

openstack/data_source_openstack_dns_zone_v2.go
openstack/data_source_openstack_dns_zone_v2_test.go
openstack/provider.go
website/docs/d/dns_zone_v2.html.markdown
website/openstack.erb

dns zone v2 data source

---

openstack/config.go
openstack/lb_v2_shared.go
openstack/provider.go
openstack/resource_openstack_lb_listener_v2.go
openstack/resource_openstack_lb_loadbalancer_v2.go
openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_monitor_v2.go
openstack/resource_openstack_lb_pool_v2.go
vendor/github.com/gophercloud/gophercloud/openstack/client.go
vendor/vendor.json
website/docs/index.html.markdown
website/docs/r/lb_monitor_v2.html.markdown

add option to use octavia service for lb operations

---

CHANGELOG.md
openstack/provider.go
openstack/resource_openstack_objectstorage_object_v1.go
openstack/resource_openstack_objectstorage_object_v1_test.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/results.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/results.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/urls.go
vendor/vendor.json
website/docs/r/objectstorage_object_v1.html.markdown
website/openstack.erb

Add resource openstack_objectstorage_object_v1

---

openstack/config.go
openstack/provider.go
vendor/github.com/gophercloud/utils/LICENSE
vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
vendor/gopkg.in/yaml.v2/LICENSE
vendor/gopkg.in/yaml.v2/LICENSE.libyaml
vendor/gopkg.in/yaml.v2/README.md
vendor/gopkg.in/yaml.v2/apic.go
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/emitterc.go
vendor/gopkg.in/yaml.v2/encode.go
vendor/gopkg.in/yaml.v2/parserc.go
vendor/gopkg.in/yaml.v2/readerc.go
vendor/gopkg.in/yaml.v2/resolve.go
vendor/gopkg.in/yaml.v2/scannerc.go
vendor/gopkg.in/yaml.v2/sorter.go
vendor/gopkg.in/yaml.v2/writerc.go
vendor/gopkg.in/yaml.v2/yaml.go
vendor/gopkg.in/yaml.v2/yamlh.go
vendor/gopkg.in/yaml.v2/yamlprivateh.go
vendor/vendor.json
website/docs/index.html.markdown

For #122 
@mcanevet Thank you for your patience with this. Please let me know what you think and if you see room for improvement.

Support for clouds.yaml

---

openstack/config.go
openstack/provider.go
openstack/provider_test.go
openstack/resource_openstack_db_instance.go
openstack/resource_openstack_db_instance_test.go
openstack/resource_openstack_db_instance_v1.go
openstack/resource_openstack_db_instance_v1_test.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/databases/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/databases/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/databases/results.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/databases/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/datastores/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/datastores/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/datastores/results.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/datastores/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/instances/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/instances/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/instances/results.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/instances/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/users/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/users/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/users/results.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/users/urls.go
vendor/vendor.json
website/docs/r/db_instance_v1.html.markdown

This PR adds openstack_db_instance resource and addresses https://github.com/terraform-providers/terraform-provider-openstack/issues/141
Acceptance tests require two extra vars to be set:
`
OS_DATASTORE_VERSION=
OS_DATASTORE_TYPE=
`

openstack_db_instance resource

---

website/docs/r/compute_instance_v2.html.markdown

Docs: Add note about ports and instances

---

openstack/resource_openstack_db_instance_v1.go
openstack/resource_openstack_db_instance_v1_test.go
website/docs/r/db_instance_v1.html.markdown

This PR adds support for database and user paramaters in openstack_db_instance resource and addresses https://github.com/terraform-providers/terraform-provider-openstack/issues/141

openstack_db_instance_v1 support for database and user

---

openstack/resource_openstack_lb_listener_v2.go
openstack/resource_openstack_lb_loadbalancer_v2.go
openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_monitor_v2.go
openstack/resource_openstack_lb_pool_v2.go

For #171 
There are 3 places in `resource_openstack_lb_loadbalancer_v2.go` where the client was changed to use the Neutron client (corresponding with the `ports` calls).
Additionally, `networkingClient` was renamed to `lbClient` when used for LB calls.

use neutron client for port requests in lb v2 loadbalancer calls

---

openstack/resource_openstack_compute_flavor_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/urls.go
vendor/vendor.json

Compute v2: Flavor is_public Fix

---

website/docs/r/compute_floatingip_v2.html.markdown
website/docs/r/compute_secgroup_v2.html.markdown

Docs: Add notes about deprecated resources

---

openstack/data_source_openstack_networking_subnet_v2.go
openstack/data_source_openstack_networking_subnet_v2_test.go

datasource openstack_networking_subnet_v2: fix #198

datasource openstack_networking_subnet_v2: fix #198

---

openstack/data_source_openstack_networking_network_v2.go
openstack/data_source_openstack_networking_secgroup_v2.go

Networking v2: Fix unhandled error check

---

openstack/resource_openstack_networking_floatingip_v2.go

This PR adds error handler when waiting for floating ip ready.

Handle errors of waiting for floating ip ready

---

openstack/resource_openstack_db_instance_v1.go
openstack/resource_openstack_db_instance_v1_test.go

@eugenetaranov When you have some time, can you look this over and test it? Functionality should be the same.
I had to remove the Import support, though, because it's not currently working and there wasn't an import test included initially.

DBv1: instance cleanup

---

openstack/import_openstack_db_database_v1_test.go
openstack/provider.go
openstack/resource_openstack_db_database_v1.go
openstack/resource_openstack_db_database_v1_test.go
website/docs/r/db_database_v1.html.markdown
website/openstack.erb

This PR adds openstack_db_database_v1 resource and addresses https://github.com/terraform-providers/terraform-provider-openstack/issues/141

openstack_db_database_v1 resource

---

website/docs/d/networking_subnet_v2.html.markdown
website/docs/r/networking_subnet_v2.html.markdown

Adding docs for the arguments added in #193

Docs: Subnet IPv6 Arguments

---

openstack/resource_openstack_db_instance_v1.go
openstack/resource_openstack_db_instance_v1_test.go
website/docs/r/db_instance_v1.html.markdown

This PR adds configuration to db instance addressing https://github.com/terraform-providers/terraform-provider-openstack/issues/141

Openstack db configuration instance

---

.zuul.yaml
openstack/import_openstack_fw_firewall_v1_test.go
openstack/import_openstack_fw_policy_v1_test.go
openstack/import_openstack_fw_rule_v1_test.go
openstack/provider_test.go
openstack/resource_openstack_fw_firewall_v1_test.go
openstack/resource_openstack_fw_policy_v1_test.go
openstack/resource_openstack_fw_rule_v1_test.go
openstack/resource_openstack_lb_listener_v2_test.go
openstack/resource_openstack_lb_loadbalancer_v2_test.go
openstack/resource_openstack_lb_member_v2_test.go
openstack/resource_openstack_lb_monitor_v2_test.go
openstack/resource_openstack_lb_pool_v2_test.go

Add OS_LB_ENVIRONMENT and OS_FW_ENVIRONMENT options to decide related
load balance and firewall acc tests are executed or not.
Fixes #227

Add OS_LB_ENVIRONMENT and OS_FW_ENVIRONMENT for Acc test

---

website/docs/r/compute_instance_v2.html.markdown

Compute v2: Clarify use of security groups in instances

---

openstack/data_source_openstack_networking_network_v2.go
openstack/data_source_openstack_networking_subnet_v2.go

Removed default values on tenant_id

---

openstack/data_source_openstack_networking_subnetpool_v2.go
openstack/data_source_openstack_networking_subnetpool_v2_test.go
openstack/import_openstack_networking_subnetpool_v2_test.go
openstack/provider.go
openstack/resource_openstack_networking_subnetpool_v2.go
openstack/resource_openstack_networking_subnetpool_v2_test.go
openstack/types.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/urls.go
vendor/vendor.json
website/docs/d/networking_subnetpool_v2.html.markdown
website/docs/r/networking_subnetpool_v2.html.markdown
website/openstack.erb

Add the support for Neutron subnetpools:
- add the resourceNetworkingSubnetPoolV2
- add the dataSourceNetworkingSubnetPoolV2
- add acceptance tests and a documentation
For: #242

Networking v2: Add subnetpools support

---

openstack/data_source_openstack_networking_subnet_v2.go
openstack/data_source_openstack_networking_subnet_v2_test.go
openstack/resource_openstack_networking_subnet_v2.go
openstack/resource_openstack_networking_subnet_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
vendor/vendor.json
website/docs/d/networking_subnet_v2.html.markdown
website/docs/r/networking_subnet_v2.html.markdown

Add subnetpool field to the subnet resource and data source.
For: #242 
This PR depends on #243 PR.

Networking V2: add subnetpool field to the subnet

---

openstack/resource_openstack_objectstorage_container_v1.go

Detect objectstorage_container removal

---

openstack/resource_openstack_fw_rule_v1.go
openstack/resource_openstack_fw_rule_v1_test.go

Amends #223 
@niuzhenguo Github is showing "unknown repository" for your PR so I've opened a new PR with some fixes. This patch seems to satisfy both of our use cases.
Can you test this and let me know if it works for you?

Use HasChange for openstack_fw_rule Update

---

website/docs/r/compute_volume_attach_v2.html.markdown

This commit makes a note about the openstack_compute_volume_attach_v2
resource when attaching multiple volumes and ensuring the
volumes are attached in the correct order.
Fixes #8

Compute v2: Update Volume Attach Documentation

---

openstack/provider.go
website/docs/index.html.markdown

Add support for OS_TOKEN

---

openstack/resource_openstack_compute_instance_v2.go

This commit suppresses availability zone diffs when the user
specifies an availability zone in the format of `az:host:node`
and Nova/Compute responds with only `az`.
Fixes #288

Compute v2: Suppress Availability Zone Diff

---

openstack/resource_openstack_images_image_v2.go

Support the OVA Container Format for image uploading.

Support ova image container format

---

openstack/import_openstack_images_image_v2_test.go
openstack/resource_openstack_images_image_v2.go
openstack/resource_openstack_images_image_v2_test.go
website/docs/r/images_image_v2.html.markdown

Create new parameter for checking the image checksum

---

openstack/data_source_openstack_compute_keypair_v2.go
openstack/data_source_openstack_compute_keypair_v2_test.go
openstack/provider.go
website/docs/d/compute_keypair_v2.html.markdown
website/openstack.erb

Fixes #306.
- Adds doc.
- Adds acceptance test.

Add data source for compute keypair.

---

vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
vendor/vendor.json

For: https://github.com/terraform-providers/terraform-provider-openstack/issues/311#issuecomment-386636516

vendor: Updating gophercloud/utils for identity api version fix

---

website/docs/r/networking_subnetpool_v2.html.markdown

For https://github.com/terraform-providers/terraform-provider-openstack/pull/243#issuecomment-376563210

Docs: Add subnetpool example

---

vendor/github.com/gophercloud/gophercloud/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
vendor/github.com/gophercloud/gophercloud/openstack/client.go
vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
vendor/github.com/gophercloud/gophercloud/openstack/utils/base_endpoint.go
vendor/github.com/gophercloud/gophercloud/params.go
vendor/github.com/gophercloud/gophercloud/results.go
vendor/github.com/gophercloud/gophercloud/service_client.go
vendor/vendor.json

vendor: Updating Gophercloud for Identity endpoint fix

---

openstack/import_openstack_vpnaas_ike_policy_v2_test.go
openstack/provider.go
openstack/resource_openstack_vpn_ike_policy_v2.go
openstack/resource_openstack_vpn_ike_policy_v2_test.go
openstack/types.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/ikepolicies/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/ikepolicies/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/ikepolicies/urls.go
vendor/vendor.json
website/docs/r/vpnaas_ike_policy_v2.html.markdown
website/docs/r/vpnaas_ipsec_policy_v2.html.markdown
website/openstack.erb

Part 3 out of 5 of a series that addresses #2

Vpnaas: IKE Policy resource

---

openstack/import_openstack_vpnaas_endpoint_group_v2_test.go
openstack/provider.go
openstack/resource_openstack_vpnaas_endpoint_group_v2.go
openstack/resource_openstack_vpnaas_endpoint_group_v2_test.go
openstack/types.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/endpointgroups/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/endpointgroups/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/endpointgroups/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/endpointgroups/urls.go
vendor/vendor.json
website/docs/r/vpnaas_endpoint_group_v2.html.markdown
website/docs/r/vpnaas_ipsec_policy_v2.html.markdown
website/openstack.erb

Part 4 out of 5 of a series that addresses #2 
@jtopjian I also put some minor doc fixes for the IPSec policy resource in here.

Vpnaas: Endpoint group resource

---

openstack/config.go
openstack/provider.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go
vendor/vendor.json

Add support to modify SSL settings via clouds.yaml

---

openstack/import_openstack_vpnaas_site_connection_v2_test.go
openstack/provider.go
openstack/resource_openstack_vpnaas_service_v2.go
openstack/resource_openstack_vpnaas_site_connection.go
openstack/resource_openstack_vpnaas_site_connection_test.go
openstack/types.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/siteconnections/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/siteconnections/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/siteconnections/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vpnaas/siteconnections/urls.go
vendor/vendor.json
website/docs/r/vpnaas_site_connection_v2.html.markdown
website/openstack.erb

Part 5 out of 5 of a series that addresses #2 
@jtopjian This has the same problem as #300 and https://github.com/gophercloud/gophercloud/pull/784 so I left out the "update" acceptance test. Let me know if this is not acceptable or you have a better idea :)
This is ready for review!

Vpnaas: IPsec site connection resource

---

openstack/resource_openstack_fw_rule_v1_test.go

FWaaS v1: fixing rule acceptance tests

---

openstack/resource_openstack_compute_floatingip_associate_v2_test.go

This should fix that pesky test failure. :smile:

Acc Tests: Fix Floating IP associate test

---

website/docs/r/networking_subnet_v2.html.markdown

As mentioned in https://github.com/terraform-providers/terraform-provider-openstack/pull/294#issuecomment-392710506

Docs: Fixing CIDR documentation in subnet resource

---

openstack/resource_openstack_images_image_v2.go

New versions of OpenStack are automatically adding a property
of os_hidden with a boolean value. This is conflicting with
Terraform's TypeMap which expects all values to be a string.
This commit fixes the issue by filtering out non-string
properties.

Image Service v2: Changes to Image Properties

---

openstack/data_source_openstack_identity_group_v3.go
openstack/data_source_openstack_identity_group_v3_test.go
openstack/provider.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/groups/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/groups/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/groups/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/groups/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/groups/urls.go
vendor/vendor.json
website/docs/d/identity_group_v3.html.markdown
website/openstack.erb

This commit adds a datasource for Groups.

Add identity group data source

---

openstack/data_source_openstack_networking_network_v2.go

Fix typo in error message from dataSourceNetworkingNetworkV2Read

---

openstack/resource_openstack_images_image_v2.go
openstack/resource_openstack_images_image_v2_test.go
vendor/github.com/gophercloud/gophercloud/README.md
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
vendor/vendor.json
website/docs/r/images_image_v2.html.markdown

This commit enables full addition, modification, and removal
of properties during an image update.
In addition, the "direct_url" property will automatically be
added to the list of all properties if it is detected.
For #289 
For #301

Image Service v2: Support Updating Properties

---

openstack/resource_openstack_networking_secgroup_rule_v2.go
vendor/github.com/gophercloud/gophercloud/openstack/client.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/secgroups/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
vendor/github.com/gophercloud/gophercloud/openstack/db/v1/configurations/results.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/results.go
vendor/github.com/gophercloud/gophercloud/provider_client.go
vendor/vendor.json
website/docs/r/networking_secgroup_rule_v2.html.markdown

Add description field to openstack_networking_secgroup_rule_v2

---

openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_member_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
vendor/github.com/gophercloud/gophercloud/params.go
vendor/vendor.json

 LBaaS v2: Allow member weights of 0

---

openstack/provider.go
openstack/resource_openstack_networking_trunk_v2.go
openstack/resource_openstack_networking_trunk_v2_test.go
openstack/util.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
vendor/vendor.json
website/docs/r/networking_trunk_v2.html.markdown
website/openstack.erb

This patch support for the OpenStack networking trunk extension.
For #345 
Signed-off-by: Antoni Segura Puimedon <celebdor@gmail.com>

Network resource - Trunk

---

openstack/resource_openstack_compute_floatingip_v2.go

Internal: compute v2 floatingip cleanup

---

openstack/compute_flavor_v2.go
openstack/compute_flavor_v2_test.go
openstack/data_source_openstack_compute_flavor_v2.go
openstack/data_source_openstack_compute_flavor_v2_test.go
openstack/import_openstack_compute_flavor_v2_test.go
openstack/resource_openstack_compute_flavor_v2.go
openstack/resource_openstack_compute_flavor_v2_test.go

Internal: compute v2 flavor cleanup

---

openstack/compute_keypair_v2.go
openstack/compute_keypair_v2_test.go
openstack/data_source_openstack_compute_keypair_v2.go
openstack/resource_openstack_compute_keypair_v2.go
openstack/types.go

Internal: compute v2 keypair cleanup

---

openstack/resource_openstack_compute_flavor_v2.go
openstack/resource_openstack_compute_keypair_v2.go

Internal: small fixes from previous cleanup

---

openstack/networking_port_v2.go
openstack/networking_port_v2_test.go
openstack/resource_openstack_networking_port_v2.go
openstack/resource_openstack_networking_port_v2_test.go
website/docs/r/networking_port_v2.html.markdown

Network v2: Rename extra_dhcp_opts to extra_dhcp_option

---

openstack/data_source_openstack_compute_flavor_v2.go
openstack/data_source_openstack_compute_flavor_v2_test.go
website/docs/d/compute_flavor_v2.html.markdown

Compute v2: Adding extra_specs to flavor data source

---

openstack/compute_servergroup_v2.go
openstack/compute_servergroup_v2_test.go
openstack/resource_openstack_compute_servergroup_v2.go
openstack/resource_openstack_compute_servergroup_v2_test.go
openstack/types.go

Internal: compute v2 servergroup cleanup

---

openstack/data_source_openstack_containerinfra_cluster_v1.go
openstack/data_source_openstack_containerinfra_cluster_v1_test.go
openstack/provider.go
openstack/resource_openstack_containerinfra_cluster_v1_test.go
website/docs/d/containerinfra_cluster_v1.html.markdown
website/openstack.erb

Add OpenStack ContainerInfraV1 Cluster datasource with tests.
For #402

ContainerInfraV1: add Cluster datasource

---

openstack/resource_openstack_lb_loadbalancer_v2.go
openstack/resource_openstack_lb_pool_v1.go
openstack/resource_openstack_networking_floatingip_v2.go
openstack/resource_openstack_networking_router_v2.go
openstack/resource_openstack_networking_subnet_v2.go
openstack/resource_openstack_networking_subnetpool_v2.go

Don't update resources, when there is an empty update struct

---

openstack/data_source_openstack_networking_secgroup_v2.go
openstack/data_source_openstack_networking_secgroup_v2_test.go
website/docs/d/networking_secgroup_v2.html.markdown

Networking V2: add description to the secgroup data source

---

openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_network_v2_test.go
website/docs/r/networking_network_v2.html.markdown

Networking V2: add description to the network resource

---

openstack/data_source_openstack_networking_subnet_v2.go
openstack/data_source_openstack_networking_subnet_v2_test.go
website/docs/d/networking_subnet_v2.html.markdown

Networking V2: add description to the subnet data source

---

openstack/data_source_openstack_networking_router_v2.go
openstack/data_source_openstack_networking_router_v2_test.go
website/docs/d/networking_router_v2.html.markdown

Networking V2: add description to the router data source

---

openstack/data_source_openstack_networking_network_v2.go
openstack/data_source_openstack_networking_network_v2_test.go
website/docs/d/networking_network_v2.html.markdown

Networking V2: add description to the network data source

---

openstack/data_source_openstack_networking_floatingip_v2.go
openstack/data_source_openstack_networking_floatingip_v2_test.go
website/docs/d/networking_floatingip_v2.html.markdown

Networking V2: Add description fields to the floatingip resource

---

openstack/resource_openstack_lb_listener_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
vendor/vendor.json

Followup for #516 
Resolves #507

LBaaSv2: bump vendor for empty "default_pool_id" update logic

---

openstack/provider.go

fix 493 - explicitly set default bool attributes

---

openstack/blockstorage_volume_attach_v2.go
openstack/blockstorage_volume_attach_v2_test.go
openstack/blockstorage_volume_attach_v3.go
openstack/blockstorage_volume_attach_v3_test.go
openstack/resource_openstack_blockstorage_volume_attach_v2.go
openstack/resource_openstack_blockstorage_volume_attach_v2_test.go
openstack/resource_openstack_blockstorage_volume_attach_v3.go
openstack/resource_openstack_blockstorage_volume_attach_v3_test.go

Internal: block storage volume attach cleanup

---

openstack/import_openstack_lb_listener_v2_test.go
openstack/import_openstack_lb_loadbalancer_v2_test.go
openstack/import_openstack_lb_member_v2_test.go
openstack/import_openstack_lb_monitor_v2_test.go
openstack/import_openstack_lb_pool_v2_test.go
openstack/resource_openstack_lb_listener_v2.go
openstack/resource_openstack_lb_loadbalancer_v2.go
openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_monitor_v2.go
openstack/resource_openstack_lb_pool_v2.go
website/docs/r/lb_listener_v2.html.markdown
website/docs/r/lb_loadbalancer_v2.html.markdown
website/docs/r/lb_member_v2.html.markdown
website/docs/r/lb_monitor_v2.html.markdown
website/docs/r/lb_pool_v2.html.markdown

LBaaSv2: Add resource import feature

---

openstack/containerinfra_shared_v1.go
openstack/containerinfra_shared_v1_test.go
openstack/data_source_openstack_containerinfra_cluster_v1.go
openstack/data_source_openstack_containerinfra_clustertemplate_v1.go
openstack/resource_openstack_containerinfra_cluster_v1.go
openstack/resource_openstack_containerinfra_clustertemplate_v1.go
openstack/util.go

For #456 
@ozerovandrei I opted to use a shared file for these resources rather than use a separate file for reach resource.
I'm having trouble building a cluster, but I'm pretty sure that's the environment and not these changes.

Internal: Container Infra cleanup

---

openstack/import_openstack_lb_l7policy_v2_test.go
openstack/lb_v2_shared.go
openstack/provider.go
openstack/resource_openstack_lb_l7policy_v2.go
openstack/resource_openstack_lb_l7policy_v2_test.go
website/docs/r/lb_l7policy_v2.html.markdown
website/openstack.erb

I was not able to reopen #520
This is its replacement and a part of #503

LbaaS: Add l7policy resource

---

openstack/import_openstack_lb_l7rule_v2_test.go
openstack/lb_v2_shared.go
openstack/provider.go
openstack/resource_openstack_lb_l7rule_v2.go
openstack/resource_openstack_lb_l7rule_v2_test.go
website/docs/r/lb_l7rule_v2.html.markdown
website/openstack.erb

￼￼Part of #503
Depends on https://github.com/gophercloud/gophercloud/pull/1354.

LBaaS: Add l7rule  resource

---

openstack/provider_test.go
openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_network_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vlantransparent/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vlantransparent/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vlantransparent/results.go
vendor/vendor.json
website/docs/r/networking_network_v2.html.markdown

Add the "transparent_vlan" attribute into networking_network_v2 resource.
For #430

NetworkingV2: add transparent_vlan network resource attribute 

---

openstack/blockstorage_volume_v1.go
openstack/blockstorage_volume_v1_test.go
openstack/blockstorage_volume_v2.go
openstack/blockstorage_volume_v2_test.go
openstack/blockstorage_volume_v3.go
openstack/blockstorage_volume_v3_test.go
openstack/resource_openstack_blockstorage_volume_attach_v2.go
openstack/resource_openstack_blockstorage_volume_attach_v3.go
openstack/resource_openstack_blockstorage_volume_v1.go
openstack/resource_openstack_blockstorage_volume_v2.go
openstack/resource_openstack_blockstorage_volume_v3.go
openstack/util.go
openstack/util_test.go

Internal: Block Storage volumes cleanup

---

openstack/lb_v2_shared.go

Part of the #546
Let's see the test results

LBaaSv2: Prioritize loadbalancer's status in favour of subelements

---

openstack/data_source_openstack_sharedfilesystem_sharenetwork_v2.go
openstack/data_source_openstack_sharedfilesystem_sharenetwork_v2_test.go
openstack/import_openstack_sharedfilesystem_sharenetwork_v2_test.go
openstack/provider.go
openstack/resource_openstack_sharedfilesystem_sharenetwork_v2.go
openstack/resource_openstack_sharedfilesystem_sharenetwork_v2_test.go
website/docs/d/sharedfilesystem_sharenetwork_v2.html.markdown
website/docs/r/sharedfilesystem_sharenetwork_v2.html.markdown
website/openstack.erb

Manila: add share network data source

---

openstack/resource_openstack_sharedfilesystem_share_v2.go

Manila: fix pending state for deleted share

---

openstack/resource_openstack_objectstorage_object_v1_test.go

Object storage: fix etag tests race condition

---

openstack/data_source_openstack_networking_floatingip_v2.go
openstack/data_source_openstack_networking_floatingip_v2_test.go
openstack/networking_floatingip_v2.go
openstack/networking_network_v2.go
openstack/resource_openstack_networking_floatingip_v2.go
openstack/resource_openstack_networking_floatingip_v2_test.go

Move Networking V2 networks and floating IPs helpers functions outside
of resource_openstack_networking_floatingip_v2.go.
Update debug and error messages.
For #456

Internal: Floating IP cleanup

---

openstack/data_source_openstack_sharedfilesystem_snapshot_v2.go
openstack/data_source_openstack_sharedfilesystem_snapshot_v2_test.go
openstack/provider.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/results.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/urls.go
vendor/vendor.json
website/docs/d/sharedfilesystem_snapshot_v2.html.markdown
website/openstack.erb

Manila: add share snapshot data source

---

openstack/resource_openstack_sharedfilesystem_securityservice_v2.go
openstack/resource_openstack_sharedfilesystem_share_access_v2.go
openstack/resource_openstack_sharedfilesystem_share_v2.go
openstack/resource_openstack_sharedfilesystem_sharenetwork_v2.go

Manila: add CheckDeleted into the Delete functions

---

openstack/data_source_openstack_compute_flavor_v2.go
openstack/data_source_openstack_compute_flavor_v2_test.go
website/docs/d/compute_flavor_v2.html.markdown

Compute v2: add flavor_id to flavor data source

---

openstack/resource_openstack_lb_l7policy_v2.go
openstack/resource_openstack_lb_l7rule_v2.go
openstack/resource_openstack_lb_listener_v2.go
openstack/resource_openstack_lb_loadbalancer_v2.go
openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_monitor_v2.go
openstack/resource_openstack_lb_pool_v2.go

LBaaSv2: add CheckDeleted into the Delete functions

---

README.md
website/docs/d/images_image_v2.html.markdown
website/docs/index.html.markdown
website/docs/r/compute_instance_v2.html.markdown
website/docs/r/images_image_v2.html.markdown

Relates to a new go version requirements #570

Fix links and go version requirement

---

openstack/networking_router_interface_v2.go
openstack/resource_openstack_networking_router_interface_v2.go

Cleanup error and debug messages.
Use resourceNetworkingRouterInterfaceV2StateRefreshFunc() for state
checking.

Internal: Networking V2 Router interface cleanup

---

openstack/data_source_openstack_images_image_v2.go
website/docs/d/images_image_v2.html.markdown

Internal: fix schema set for the image data source

---

openstack/data_source_openstack_networking_subnetpool_v2.go

Internal: fix schema set for the subnetpool data source

---

openstack/resource_openstack_compute_floatingip_associate_v2_test.go
openstack/resource_openstack_networking_floatingip_associate_v2.go
openstack/resource_openstack_networking_floatingip_v2.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
vendor/vendor.json

Resolves #605 
Will run tests first, then will push the fix

Networking V2: fix fip disassociating on description update

---

openstack/data_source_openstack_identity_group_v3.go

Internal: identity group cleanup

---

openstack/data_source_openstack_identity_endpoint_v3.go

Internal: identity endpoint cleanup

---

openstack/data_source_openstack_networking_port_ids_v2.go
openstack/data_source_openstack_networking_port_v2.go
openstack/data_source_openstack_networking_port_v2_test.go
website/docs/d/networking_port_ids_v2.html.markdown
website/docs/d/networking_port_v2.html.markdown

Networking V2: Fix port data sources

---

openstack/resource_openstack_networking_trunk_v2.go
openstack/resource_openstack_networking_trunk_v2_test.go
website/docs/r/networking_trunk_v2.html.markdown

This resource was forgotten in #511

Networking V2: add description to the trunk resource

---

openstack/data_source_openstack_fw_policy_v1.go
openstack/data_source_openstack_networking_floatingip_v2.go
openstack/data_source_openstack_networking_floatingip_v2_test.go
openstack/data_source_openstack_networking_network_v2.go
openstack/data_source_openstack_networking_network_v2_test.go
openstack/data_source_openstack_networking_port_ids_v2.go
openstack/data_source_openstack_networking_port_v2.go
openstack/data_source_openstack_networking_router_v2.go
openstack/data_source_openstack_networking_router_v2_test.go
openstack/data_source_openstack_networking_secgroup_v2.go
openstack/data_source_openstack_networking_secgroup_v2_test.go
openstack/data_source_openstack_networking_subnet_v2.go
openstack/data_source_openstack_networking_subnet_v2_test.go
openstack/data_source_openstack_networking_subnetpool_v2.go
openstack/data_source_openstack_networking_subnetpool_v2_test.go
website/docs/d/networking_floatingip_v2.html.markdown
website/docs/d/networking_network_v2.html.markdown
website/docs/d/networking_router_v2.html.markdown
website/docs/d/networking_secgroup_v2.html.markdown
website/docs/d/networking_subnet_v2.html.markdown
website/docs/d/networking_subnetpool_v2.html.markdown

Networking V2: Add tags into the data sources

---

openstack/data_source_openstack_identity_auth_scope_v3.go
openstack/identity_auth_scope_v3.go
openstack/identity_auth_scope_v3_test.go

Internal: identity auth scope cleanup

---

openstack/data_source_openstack_identity_role_v3.go
openstack/identity_role_assignment_v3.go
openstack/identity_role_assignment_v3_test.go
openstack/resource_openstack_identity_role_assignment_v3.go
openstack/resource_openstack_identity_role_assignment_v3_test.go
openstack/resource_openstack_identity_role_v3.go

Internal: identity roles cleanup

---

openstack/data_source_openstack_networking_subnetpool_v2.go
openstack/networking_subnetpool_v2.go
openstack/resource_openstack_networking_subnetpool_v2.go

Provide a single resource.StateRefreshFunc for the subnetpool resource.
Update debug messages for the subnetpool resource.
Use expandToStringSlice() for the subnetpool "prefixes" argument.

Internal: Networking V2 Subnetpool cleanup

---

openstack/data_source_openstack_identity_user_v3.go
openstack/identity_user_v3.go
openstack/identity_user_v3_test.go
openstack/resource_openstack_identity_user_v3.go

Internal: identity user cleanup

---

openstack/networking_network_v2.go

Networking v2: Fix 409 bug with network refresh

---

openstack/resource_openstack_sharedfilesystem_share_access_v2.go
openstack/resource_openstack_sharedfilesystem_share_v2.go
website/docs/r/compute_instance_v2.html.markdown
website/docs/r/sharedfilesystem_share_access_v2.html.markdown
website/docs/r/sharedfilesystem_share_v2.html.markdown

Manila: recreate share and its access resources, when the region is changed

---

openstack/data_source_openstack_containerinfra_clustertemplate_v1_test.go
openstack/data_source_openstack_images_image_v2_test.go
openstack/resource_openstack_blockstorage_volume_v1_test.go
openstack/resource_openstack_blockstorage_volume_v2_test.go
openstack/resource_openstack_blockstorage_volume_v3_test.go
openstack/resource_openstack_compute_flavor_v2_test.go
openstack/resource_openstack_containerinfra_cluster_v1_test.go
openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go
openstack/resource_openstack_images_image_v2_test.go
openstack/resource_openstack_lb_vip_v1_test.go
openstack/resource_openstack_objectstorage_container_v1_test.go
website/docs/d/images_image_v2.html.markdown
website/docs/r/compute_flavor_v2.html.markdown
website/docs/r/compute_instance_v2.html.markdown
website/docs/r/containerinfra_clustertemplate_v1.html.markdown
website/docs/r/images_image_v2.html.markdown
website/docs/r/objectstorage_container_v1.html.markdown

This commit updates the example code and documentation to reflect how
arguments/attributes of TypeMap should now be declared.
For #548

Provider: Terraform v0.12 TypeMap Fixes

---

openstack/data_source_openstack_networking_port_ids_v2.go
openstack/data_source_openstack_networking_port_v2.go
openstack/data_source_openstack_networking_port_v2_test.go
openstack/networking_port_v2.go
openstack/resource_openstack_networking_port_v2.go
openstack/resource_openstack_networking_port_v2_test.go

Network V2: Fix port data source all_fixed_ips attribute

---

openstack/data_source_openstack_sharedfilesystem_sharenetwork_v2_test.go
openstack/resource_openstack_networking_floatingip_v2.go
openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_port_secgroup_associate_v2.go
openstack/resource_openstack_networking_port_v2.go
openstack/resource_openstack_networking_router_v2.go
openstack/resource_openstack_networking_secgroup_v2.go
openstack/resource_openstack_networking_subnet_v2.go
openstack/resource_openstack_networking_subnetpool_v2.go
openstack/resource_openstack_networking_trunk_v2.go
openstack/util.go
website/docs/r/networking_floatingip_v2.html.markdown
website/docs/r/networking_network_v2.html.markdown
website/docs/r/networking_port_v2.html.markdown
website/docs/r/networking_router_v2.html.markdown
website/docs/r/networking_secgroup_v2.html.markdown
website/docs/r/networking_subnet_v2.html.markdown
website/docs/r/networking_subnetpool_v2.html.markdown
website/docs/r/networking_trunk_v2.html.markdown

Networking V2: Don't conflict with the tags, being set ad-hoc

---

openstack/resource_openstack_compute_volume_attach_v2.go

This commit will retry volume attachments when the returned error is of
code 400 and multiattach is being requested. This is to help in
situations when multiple attachments are happening in parallel.
Fixes #497 
@jamesmmccarthy Would you be able to test this and see if this resolves the issue you've run into?

Compute v2: Retry multiattach volume attachments

---

website/docs/r/compute_instance_v2.html.markdown

Docs: Add section on Instances and Networks

---

openstack/compute_floatingip_associate_v2.go
openstack/resource_openstack_compute_floatingip_associate_v2.go

Internal: openstack_compute_floatingip_associate_v2 cleanup

---

openstack/resource_openstack_networking_port_v2.go

Networking v2: Revert validation of fixed_ip ip_address

---

openstack/types.go

For cases when API returns an array

Debug: Allow JSON array unmarshalling in debug mode

---

openstack/data_source_openstack_networking_port_v2_test.go
openstack/resource_openstack_identity_user_v3_test.go
openstack/resource_openstack_networking_network_v2_test.go

Acc Tests: Fixing test fixtures

---

openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_network_v2_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/results.go
vendor/modules.txt
website/docs/r/networking_network_v2.html.markdown

For #22 
Part 1/2
The vendor commit looks a little weird with the syscall stuff. I'll ask about that.

Networking v2: Network Port Security

---

website/docs/r/compute_instance_v2.html.markdown

Docs: Fix incorrect floating IP reference

---

openstack/resource_openstack_networking_port_v2.go
openstack/resource_openstack_networking_port_v2_test.go
website/docs/r/networking_port_v2.html.markdown

For #22 
Depends on #681 
Part 2/2

Networking v2: Port Port Security

---

openstack/data_source_openstack_networking_port_v2.go

Networking V2: Handle multiple dhcp options in port data source

---

openstack/data_source_openstack_networking_trunk_v2.go
openstack/data_source_openstack_networking_trunk_v2_test.go
openstack/provider.go
openstack/util.go
website/docs/d/networking_trunk_v2.html.markdown
website/openstack.erb

Networking V2: Add trunk data source

---

examples/multiple-vm-with-floating-ip/Readme.md
examples/multiple-vm-with-floating-ip/main.tf
examples/multiple-vm-with-floating-ip/openrc.sample
examples/multiple-vm-with-floating-ip/variables.tf

This is an example how to spawn multiple openstack vm and automatically adding coresponding floating ips.

add multi-vm with corresponding floating ip example

---

openstack/data_source_openstack_networking_network_v2.go
openstack/networking_network_v2.go
openstack/resource_openstack_networking_network_v2.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
vendor/modules.txt
website/docs/d/networking_network_v2.html.markdown
website/docs/r/networking_network_v2.html.markdown

Networking V2: Add MTU support for the network resources

---

openstack/data_source_openstack_networking_floatingip_v2.go
openstack/data_source_openstack_networking_network_v2.go
openstack/data_source_openstack_networking_port_ids_v2.go
openstack/data_source_openstack_networking_port_v2.go
openstack/networking_floatingip_v2.go
openstack/networking_network_v2.go
openstack/networking_port_v2.go
openstack/resource_openstack_networking_floatingip_v2.go
openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_port_v2.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/dns/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/dns/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/dns/results.go
vendor/modules.txt
website/docs/d/networking_floatingip_v2.html.markdown
website/docs/d/networking_network_v2.html.markdown
website/docs/d/networking_port_v2.html.markdown
website/docs/r/networking_floatingip_v2.html.markdown
website/docs/r/networking_network_v2.html.markdown
website/docs/r/networking_port_v2.html.markdown

Networking V2: Add DNS support for the port, floating IP, network

---

go.mod
go.sum
openstack/resource_openstack_sharedfilesystem_share_access_v2.go
openstack/resource_openstack_sharedfilesystem_share_access_v2_test.go
openstack/util.go
openstack/util_test.go
vendor/github.com/gophercloud/gophercloud/.zuul.yaml
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/results.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/urls.go
vendor/modules.txt
website/docs/r/sharedfilesystem_share_access_v2.html.markdown

This commit adds "cephx" as a valid access_type. This commit also adds
the access_key computed attribute.
For #714

SharedFilesystem v2: Add cephx and access_key

---

openstack/db_configuration_v1.go
openstack/db_configuration_v1_test.go
openstack/db_database_v1.go
openstack/db_instance_v1.go
openstack/db_instance_v1_test.go
openstack/db_user_v1.go
openstack/db_user_v1_test.go
openstack/resource_openstack_db_configuration_v1.go
openstack/resource_openstack_db_database_v1.go
openstack/resource_openstack_db_instance_v1.go
openstack/resource_openstack_db_user_v1.go

Internal: Cleanup database resources

---

go.mod
go.sum
openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_subnet_v2.go
vendor/github.com/gophercloud/gophercloud/.zuul.yaml
vendor/github.com/gophercloud/gophercloud/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
vendor/github.com/mitchellh/go-homedir/go.mod
vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/modules.txt

This PR updates gophercloud/gophercloud and gophercloud/utils, and fixes a couple of option struct members that changed to pointers

vendor: update gophercloud/*

---

openstack/data_source_openstack_networking_addressscope_v2.go
openstack/data_source_openstack_networking_addressscope_v2_test.go
openstack/provider.go
website/docs/d/networking_addressscope_v2.html.markdown
website/openstack.erb

Add dataSourceNetworkingAddressScopeV2 with tests and documentation.
For #364

Networking V2: add AddressScope datasource

---

openstack/networking_router_route_v2.go
openstack/networking_router_route_v2_test.go
openstack/resource_openstack_networking_router_route_v2.go
openstack/resource_openstack_networking_router_route_v2_test.go

Cleanup messages and variables definition for the
openstack_networking_router_route_v2 resource.
For #456

Internal: Networking V2 Router Route cleanup

---

openstack/resource_openstack_networking_subnet_v2_test.go

Acc Tests: Add test for clearing a subnet's dns_nameservers

---

openstack/resource_openstack_networking_subnet_v2_test.go

Changes allocation_pools to allocation_pool

Acc Tests: Fix allocation_pool

---

openstack/resource_openstack_networking_port_v2_test.go

Acc Tests: Fix port binding syntax for v0.12

---

openstack/types.go

This commit fixes an issue where the request body was being
copied into a new variable regardless of the content type.
This caused out of memory issues when the request was large
amounts of data.
For https://github.com/gophercloud/gophercloud/issues/1568

Fix Debug Memory Issue

---

openstack/types.go

This PR adds an ability to mask identity v2 credentials.

Mask identity v2 auth credentials

---

website/docs/r/networking_subnet_v2.html.markdown

Docs: Fix docs for subnet allocation pool

---

go.mod
go.sum
openstack/import_openstack_networking_qos_policy_v2_test.go
openstack/networking_qos_policy_v2.go
openstack/provider.go
openstack/resource_openstack_networking_qos_policy_v2.go
openstack/resource_openstack_networking_qos_policy_v2_test.go
openstack/types.go
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/urls.go
vendor/modules.txt
website/docs/r/networking_qos_policy_v2.html.markdown
website/openstack.erb

Implement "openstack_networking_qos_policy_v2" resource with acceptance
tests and website documentation.
For #760

Networking V2: add QoS Policy resource

---

website/docs/r/networking_qos_policy_v2.html.markdown

Small fix of the website sidebar.

Website: fix networking_qos_policy_v2 resource doc

---

openstack/import_openstack_compute_instance_v2_test.go

Gofmt cleanup after the compute resource import

---

openstack/resource_openstack_networking_subnet_v2.go

Check type assertion for the dns_nameservers in subnet

---

openstack/import_openstack_identity_service_v3_test.go
openstack/provider.go
openstack/resource_openstack_identity_service_v3.go
openstack/resource_openstack_identity_service_v3_test.go
website/docs/r/identity_service_v3.html.markdown
website/openstack.erb

Identity V3: Add identity service resource

---

go.mod
go.sum
openstack/resource_openstack_sharedfilesystem_share_v2.go
openstack/resource_openstack_sharedfilesystem_share_v2_test.go
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/results.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/urls.go
vendor/modules.txt
website/docs/r/sharedfilesystem_share_v2.html.markdown

Manila V2: Allow modification of the share metadata

---

openstack/lb_v2_shared.go
openstack/resource_openstack_lb_pool_v2.go

LBaaS V2: Add flatten func for the lb pool

---

openstack/data_source_openstack_keymanager_secret_v1.go
openstack/data_source_openstack_keymanager_secret_v1_test.go
openstack/provider.go
website/docs/d/keymanager_secret_v1.html.markdown
website/openstack.erb

Key manager v1: add secret data source

---

openstack/data_source_openstack_identity_service_v3.go
openstack/data_source_openstack_identity_service_v3_test.go
openstack/provider.go
website/docs/d/identity_service_v3.html.markdown
website/openstack.erb

Identity V3: Add service data source

---

go.mod
go.sum
openstack/import_openstack_blockstorage_quotaset_v2_test.go
openstack/provider.go
openstack/resource_openstack_blockstorage_quotaset_v2.go
openstack/resource_openstack_blockstorage_quotaset_v2_test.go
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/results.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/urls.go
vendor/modules.txt
website/docs/r/blockstorage_quotaset_v2.html.markdown
website/openstack.erb

Implement the "openstack_blockstorage_quotaset_v2" resource.
For #657

BlockStorage V2: add Quotaset resource

---

openstack/import_openstack_identity_endpoint_v3_test.go
openstack/provider.go
openstack/resource_openstack_identity_endpoint_v3.go
openstack/resource_openstack_identity_endpoint_v3_test.go
website/docs/r/identity_endpoint_v3.html.markdown
website/openstack.erb

Identity V3: Add identity endpoint resource

---

openstack/import_openstack_blockstorage_quotaset_v3_test.go
openstack/provider.go
openstack/resource_openstack_blockstorage_quotaset_v3.go
openstack/resource_openstack_blockstorage_quotaset_v3_test.go
website/docs/r/blockstorage_quotaset_v3.html.markdown
website/openstack.erb

Add the openstack_blockstorage_quotaset_v3 resource with needed tests
and the website documentation.
For #657

Blockstorage V3: add quotaset resource

---

openstack/lb_v2_shared.go

Resolves #838 
Terraform expects that the neutron lbaas extension returns the LB status tree, but in some cases it doesn't. When the statuses cannot be retrieved, terraform just tries to fetch the remote resources by ID. There are two kinds of resources, which cannot be be retrieved by an ID, because neutron API requests the resource parent:
* member (expects parent pool ID)
* l7rule (expects parent l7policy ID)
These resource were considered as deleted by default. Now they'll be retrieved from the parent resource.

LBaaS V2: Don't fallback to 'DELETE' status, when statuses are not available

---

openstack/resource_openstack_networking_floatingip_v2.go
openstack/resource_openstack_networking_network_v2.go

Networking V2: Mark dns attributes as computed

---

openstack/identity_role_assignment_v3.go

Identity V3: fix role assignment list

---

openstack/data_source_openstack_keymanager_container_v1.go
openstack/data_source_openstack_keymanager_container_v1_test.go
openstack/data_source_openstack_keymanager_secret_v1.go
openstack/data_source_openstack_keymanager_secret_v1_test.go
openstack/provider.go
openstack/resource_openstack_keymanager_container_v1.go
website/docs/d/keymanager_container_v1.html.markdown
website/openstack.erb

Key manager V1: Add containers data source

---

openstack/data_source_openstack_identity_auth_scope_v3.go

Identity V3: Fix panic within the domain scope

---

openstack/identity_role_assignment_v3.go

Identity V3: Fix not found logic detection for the role assignments

---

openstack/resource_openstack_compute_flavor_v2.go

Compute V2: Read flavor's ephemeral option

---

go.mod
go.sum
openstack/data_source_openstack_identity_auth_scope_v3.go
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/modules.txt
website/docs/d/identity_auth_scope_v3.html.markdown

Identity V3: Show domain scope info

---

openstack/config.go
openstack/provider.go
website/docs/index.html.markdown

Identity: authenticate against identity only, when it is needed

---

openstack/data_source_openstack_identity_group_v3.go
openstack/data_source_openstack_identity_user_v3.go
website/docs/d/identity_group_v3.html.markdown
website/docs/d/identity_user_v3.html.markdown

Identity V3: Add description support to the user and group data sources

---

openstack/resource_openstack_compute_instance_v2.go

Compute V2: Handle empty scheduler_hints lists

---

openstack/lb_v2_shared.go

Lbaas v2: Properly handle 404 error on status checks

---

openstack/resource_openstack_lb_listener_v2.go
openstack/resource_openstack_lb_listener_v2_test.go
openstack/resource_openstack_lb_monitor_v2.go
openstack/resource_openstack_lb_monitor_v2_test.go
openstack/resource_openstack_lb_pool_v2.go
openstack/resource_openstack_lb_pool_v2_test.go
website/docs/r/lb_listener_v2.html.markdown
website/docs/r/lb_monitor_v2.html.markdown
website/docs/r/lb_pool_v2.html.markdown

LBaaSv2: Add UDP protocol support

---

openstack/resource_openstack_sharedfilesystem_share_access_v2.go
openstack/sharedfilesystem_share_access_v2.go
openstack/sharedfilesystem_shared_v2.go

Cleanup openstack_share_access_v2 resource.
For #456

Shared filesystem V2: cleanup share access

---

openstack/config.go
openstack/provider.go
website/docs/index.html.markdown

Auth: add "allow_reauth" configuration option

---

.zuul.yaml

f-user-agent branch needs to update the zuul configuration

Remove mitaka check job as ubuntu-trusty is EOL(f-user-agent)

---

openstack/compute_instance_v2.go
openstack/resource_openstack_compute_instance_v2.go
website/docs/r/compute_instance_v2.html.markdown

For https://github.com/terraform-providers/terraform-provider-openstack/issues/736

implement support for volume_type in block_device of openstack_compute_instance_v2

---

openstack/import_openstack_compute_instance_v2_test.go
openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_compute_instance_v2_test.go
website/docs/r/compute_instance_v2.html.markdown

fixes #858 detach port before deleting the instance

detach ports before deleting instance

---

website/docs/r/objectstorage_container_v1.html.markdown

Adds some examples of how the ACLs should be used, to make it clearer what's going on.

Add ACL examples

---

openstack/import_openstack_lb_members_v2_test.go
openstack/lb_v2_shared.go
openstack/provider.go
openstack/provider_test.go
openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_member_v2_test.go
openstack/resource_openstack_lb_members_v2.go
openstack/resource_openstack_lb_members_v2_test.go
website/docs/r/lb_member_v2.html.markdown
website/docs/r/lb_members_v2.html.markdown
website/openstack.erb

LBaaS v2: Add batch members update resource

---

openstack/resource_openstack_compute_instance_v2.go
website/docs/r/compute_instance_v2.html.markdown

Resolves #658
could not reopen #666

Compute v2: Introduce an availability_zone_hints parameter

---

openstack/keymanager_secret_v1.go

Keymanager V1: Print error log in keyManagerSecretV1GetPayload func

---

examples/attach-format-mount-volume/README.md
examples/attach-format-mount-volume/main.tf
examples/attach-format-mount-volume/openrc.sample
examples/attach-format-mount-volume/outputs.tf
examples/attach-format-mount-volume/variables.tf
examples/attach-format-mount-volume/volumes.tf
examples/multiple-vm-with-floating-ip/Readme.md
examples/multiple-vm-with-floating-ip/main.tf
examples/multiple-vm-with-floating-ip/outputs.tf
examples/multiple-vm-with-floating-ip/variables.tf
website/docs/r/compute_volume_attach_v2.html.markdown

- Fixed invalid and reserved names
- Added attach, format, and mount volume example

Fixed names and added volume example

---

openstack/networking_subnet_route_v2.go
openstack/networking_subnet_route_v2_test.go
openstack/resource_openstack_networking_subnet_route_v2.go
openstack/resource_openstack_networking_subnet_route_v2_test.go

Add helpers into openstack/networking_subnet_route_v2.go.
Refactor networking_subnet_route_v2 resource code with tests.
For #456

Networking V2: cleanup subnet route resource

---

openstack/lb_v2_shared.go

Fix go vet "composite literal uses unkeyed fields"

---

website/docs/r/networking_port_v2.html.markdown

Cleanup resource docs and upda networking_port_v2 block usage.
Fixes #1008

Docs: cleanup Networking Port V2 docs

---

openstack/data_source_openstack_compute_flavor_v2.go
website/docs/d/compute_flavor_v2.html.markdown

Compute V2: Allow to filter flavors by visibility in data source

---

go.mod
go.sum
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
vendor/github.com/gophercloud/gophercloud/provider_client.go
vendor/modules.txt

Upgrage Gophercloud to v0.12.0

---

openstack/import_openstack_identity_group_v3_test.go
openstack/provider.go
openstack/resource_openstack_identity_group_v3.go
openstack/resource_openstack_identity_group_v3_test.go
website/docs/r/identity_group_v3.html.markdown
website/openstack.erb

This PR allows to create openstack_identity_group_v3 resource, referring to #895

feat: add openstack_identity_group_v3 resource

---

go.sum
openstack/import_openstack_identity_ec2_credential_v3_test.go
openstack/provider.go
openstack/resource_openstack_identity_ec2_credential_v3.go
openstack/resource_openstack_identity_ec2_credential_v3_test.go
vendor/github.com/gophercloud/gophercloud/go.mod
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/urls.go
vendor/modules.txt
website/docs/r/identity_ec2_credential_v3.html.markdown

* allows creating EC2 credentials for S3-compatible Swift/RadosGW endpoints

Add identity_ec2_credential resource

---

openstack/resource_openstack_keymanager_container_v1.go
openstack/resource_openstack_keymanager_container_v1_test.go

Keymanager V1: fix ACL set for the "certificate" container type

---

website/openstack.erb

@ozerovandrei another fix for ec2 docs

Add a link to ec2 cred doc

---

.goreleaser.yml

Add Goreleaser configuration

---

website/docs/r/blockstorage_quotaset_v2.html.markdown
website/docs/r/blockstorage_quotaset_v3.html.markdown
website/docs/r/compute_quotaset_v2.html.markdown
website/docs/r/networking_quota_v2.html.markdown

Add note describing consequences of not specifying the optional quota arguments into following docs:
- openstack_blockstorage_quotaset_v2
- openstack_blockstorage_quotaset_v3
- openstack_compute_quotaset_v2

Update blockstorage and compute quotasets docs

---

.github/workflows/golangci-lint.yml

Run golangci-lint on main push

---

openstack/resource_openstack_compute_aggregate_v2.go

Aggregate V2: make "zone" optional

---

.github/workflows/release.yml
README.md
go.mod

Use Go 1.15

---

README.md

Update link to website docs to use main branch.

Use main branch in readme docs link

---

.golangci.yml

Enable linters that are already ok

---

openstack/networking_router_v2.go
openstack/resource_openstack_networking_router_v2.go
openstack/resource_openstack_networking_router_v2_test.go
website/docs/r/networking_router_v2.html.markdown

Networking: retry external subnets on router creation, when a subnet is exhausted

---

openstack/networking_port_v2.go

Fixes #1116
@lperrin-obs please try this fix in your environment and let me know if it helps to avoid unnecessary update

Networking: fix port's null profile binding update

---

openstack/networking_v2_shared.go
openstack/resource_openstack_networking_floatingip_v2.go
openstack/resource_openstack_networking_floatingip_v2_test.go
openstack/resource_openstack_networking_router_v2.go
openstack/resource_openstack_networking_router_v2_test.go
openstack/types.go
website/docs/r/networking_floatingip_v2.html.markdown

Networking: add a list of FIP subnets to a floating IP resource

---

.golangci.yml
openstack/data_source_openstack_identity_project_v3.go
openstack/networking_network_v2.go

Enable govet and maligned linters

---

openstack/networking_v2_shared.go

testing a fix for https://github.com/theopenlab/openlab/issues/683

networking v2: test scenario for neutron 400 ExternalIpAddressExhausted response code

---

openstack/import_openstack_lb_quota_v2_test.go
openstack/lb_v2_shared.go
openstack/lb_v2_shared_test.go
openstack/provider.go
openstack/resource_openstack_lb_quota_v2.go
openstack/resource_openstack_lb_quota_v2_test.go
website/docs/r/lb_quota_v2.html.markdown
website/openstack.erb

Close #1168 
Adds support for octavia quota.
In my understanding this cannot be implemented for neutron LBaaS

Add resource openstack_lb_quota_v2

---

go.mod
go.sum

Use the current latest Gophercloud libs.

Update Gophercloud dependencies

---

openstack/resource_openstack_blockstorage_quotaset_v2.go
openstack/resource_openstack_blockstorage_quotaset_v2_test.go
website/docs/r/blockstorage_quotaset_v2.html.markdown

Similar to #1177 and #1180 this adds support for blockstorage_quota_v2

blockstorage_quotaset_v2: Add multi-region support

---

openstack/resource_openstack_blockstorage_quotaset_v3.go
openstack/resource_openstack_blockstorage_quotaset_v3_test.go
website/docs/r/blockstorage_quotaset_v3.html.markdown

Similar to #1177 and #1180 this adds support for blockstorage_quota_v3

blockstorage_quotaset_v3: Add multi-region support

---

.golangci.yml
openstack/compute_instance_v2.go
openstack/data_source_openstack_networking_port_ids_v2.go
openstack/data_source_openstack_networking_router_v2.go
openstack/data_source_openstack_sharedfilesystem_availability_zones_v2.go
openstack/data_source_openstack_sharedfilesystem_share_v2.go
openstack/db_instance_v1.go
openstack/db_user_v1.go
openstack/identity_application_credential_v3.go
openstack/identity_user_v3.go
openstack/keymanager_container_v1.go
openstack/resource_openstack_orchestration_stack_v1.go
openstack/resource_openstack_sharedfilesystem_share_v2.go

Enable prealloc linter

---

.github/workflows/golangci-lint.yml
.golangci.yml
openstack/data_source_openstack_dns_zone_v2.go
openstack/data_source_openstack_sharedfilesystem_snapshot_v2_test.go
openstack/images_image_v2.go
openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_identity_endpoint_v3_test.go
openstack/resource_openstack_identity_role_assignment_v3.go
openstack/resource_openstack_lb_member_v1.go
openstack/resource_openstack_lb_vip_v1.go
openstack/resource_openstack_networking_port_secgroup_associate_v2_test.go

Enable errcheck linter

---

openstack/resource_openstack_compute_instance_v2.go

Resolves #1195 
cc @ozerovandrei

Compute v2: use image client to resolve image names

---

go.mod
go.sum
openstack/blockstorage_volume_type_v3.go
openstack/blockstorage_volume_type_v3_test.go
openstack/import_openstack_blockstorage_volume_type_v3_test.go
openstack/provider.go
openstack/resource_openstack_blockstorage_volume_type_v3.go
openstack/resource_openstack_blockstorage_volume_type_v3_test.go
website/docs/r/blockstorage_volume_type_v3.html.markdown
website/openstack.erb

Add new resource volume_type. Update gophercloud to
required functionality for volume_type extra_specs.
For: #1201

Add new resource blockstorage_volume_type_v3

---

openstack/blockstorage_quotaset.go
openstack/blockstorage_quotaset_test.go
openstack/resource_openstack_blockstorage_quotaset_v2.go
openstack/resource_openstack_blockstorage_quotaset_v2_test.go
openstack/resource_openstack_blockstorage_quotaset_v3.go
openstack/resource_openstack_blockstorage_quotaset_v3_test.go

Explicit convert volume_type_quota values to int.
Update tests to add volume type creation and volume_type_quota
updates.
For: #1193
Requires: #1204

blockstorage_quotaset_v2/3: Convert volume_type_quota to int 

---

openstack/data_source_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go

Fix TestAccNetworkingV2QoSMinimumBandwidthRuleDataSource_basic test

---

openstack/resource_openstack_blockstorage_quotaset_v2_test.go

Fix TestAccBlockStorageV2Quotaset_importBasic test

---

openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2_test.go

Update the test to change direction
Relates to #1211

Fix TestAccNetworkingV2QoSBandwidthLimitRule_basic test

---

openstack/resource_openstack_blockstorage_quotaset_v3_test.go

Fix TestAccBlockStorageV3Quotaset_importBasic test

---

openstack/resource_openstack_networking_port_v2.go

networking_port: Update when qos_policy_id is changed

---

openstack/resource_openstack_identity_project_v3_test.go

Add helper function to test tags and length of tags
Relates to #1211

Fix TestAccIdentityV3Project_basic test

---

go.mod
go.sum
openstack/import_openstack_blockstorage_volume_type_access_v3_test.go
openstack/provider.go
openstack/resource_openstack_blockstorage_volume_type_access_v3.go
openstack/resource_openstack_blockstorage_volume_type_access_v3_test.go
website/docs/r/blockstorage_volume_type_access_v3.html.markdown
website/openstack.erb

Add new resource blockstorage_volume_type_access_v3

---

openstack/lb_v2_shared.go
openstack/resource_openstack_lb_members_v2.go
openstack/resource_openstack_lb_members_v2_test.go
website/docs/r/lb_members_v2.html.markdown

Relates to: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1074
Add backup argument for members

openstack_lb_members_v2: Add backup attribute

---

go.mod
go.sum
openstack/lb_v2_shared.go
openstack/resource_openstack_lb_listener_v2.go
website/docs/r/lb_listener_v2.html.markdown

For #1236
Adds support for SCTP protocol for octavia listeners

openstack_lb_listener_v2: Add protocol SCTP

---

website/docs/r/compute_instance_v2.html.markdown

There was a quote missing. Additionally reformatted some lines for better readability.

Added missing quote sign

---

.zuul.yaml
.zuul/playbooks/terraform-provider-openstack-acceptance-test-admin/run.yaml
.zuul/playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml
.zuul/playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml
.zuul/playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
.zuul/playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
.zuul/playbooks/terraform-provider-openstack-acceptance-test/run.yaml
.zuul/playbooks/terraform-provider-openstack-unittest/run.yaml
openstack/data_source_openstack_blockstorage_snapshot_v2_test.go
openstack/data_source_openstack_blockstorage_volume_v2_test.go
openstack/import_openstack_blockstorage_quotaset_v2_test.go
openstack/import_openstack_blockstorage_volume_v2_test.go
openstack/provider_test.go
openstack/resource_openstack_blockstorage_quotaset_v2_test.go
openstack/resource_openstack_blockstorage_volume_attach_v2_test.go
openstack/resource_openstack_blockstorage_volume_v2_test.go
openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_compute_instance_v2_test.go
openstack/resource_openstack_compute_volume_attach_v2_test.go

For #1253 
Copy the zuul job configurations from openlab to allow
easier/faster updates.

Add ci configuration for openlab zuul

---

openstack/resource_openstack_networking_subnet_v2.go

This check catches terraform state mismatch with Openstack subnet in case of input error
Consider the following example:
```
resource "openstack_networking_subnet_v2" "subnet" {
name             = "subnet"
network_id    = openstack_networking_network_v2.network.id
cidr                = "192.168.1.0/20"
ip_version      = 4
tenant_id       = openstack_identity_project_v3.project.id
}
```
Terraform plans subnet with a `cidr` attribute value of `192.168.1.0/20`. This adress is a part of the `192.168.0.0/20` subnet, so Openstack Neutron automatically assumes it to be `192.168.0.0/20`, which is a valid CIDR. Subnet creates successfully.
The problem is, that terraform will store the information for the `networking_subnet_v2` resource with `cidr` attribute value set to `192.168.1.0/20`, but every …

Check CIDR value in resource_openstack_networking_subnet_v2

---

CHANGELOG.md
openstack/resource_openstack_lb_monitor_v2.go
website/docs/index.html.markdown

Update all issue links to new location

---

openstack/dns_zone_v2.go
openstack/resource_openstack_dns_recordset_v2.go
openstack/resource_openstack_dns_recordset_v2_test.go
website/docs/r/dns_recordset_v2.html.markdown

Add the capability to change recordset project ID for openstack_dns_recordset_v2

Add SUDO_PROJECT_ID for openstack_dns_recordset_v2

---

openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_compute_instance_v2_test.go

feat: support change power state to shelved_offloaded

---

go.mod
go.sum

Run go mod tidy with 1.16 version.

Run go mod tidy to cleanup deps

---

openstack/import_openstack_images_image_access_accept_v2_test.go
openstack/resource_openstack_images_image_access_accept_v2_test.go
openstack/resource_openstack_images_image_access_v2_test.go

Add a workaround for 403 status codes.
For #1283

Require admin permissions for image access tests

---

openstack/resource_openstack_compute_quotaset_v2.go

Fixes the issue https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/973

Prevent not specified quota values are being set to 0

---

openstack/data_source_openstack_networking_network_v2.go
openstack/resource_openstack_networking_network_v2.go
website/docs/d/networking_network_v2.html.markdown
website/docs/r/networking_network_v2.html.markdown

* `physical_network` - The physical network where this network is implemented.
* `segmentation_id` - An isolated segment on the physical network.
* `network_type` - The type of physical network.

r/d/networking_network_v2: add providerext attributes

---

openstack/data_source_openstack_blockstorage_quotaset_v3.go
openstack/data_source_openstack_blockstorage_quotaset_v3_test.go
openstack/provider.go
website/docs/d/blockstorage_quotaset_v3.html.markdown
website/openstack.erb

New data source: openstack_blockstorage_quotaset_v3

---

openstack/data_source_openstack_networking_quota_v2.go
openstack/data_source_openstack_networking_quota_v2_test.go
openstack/provider.go
website/docs/d/networking_quota_v2.html.markdown
website/openstack.erb

Add new datasource: openstack_networking_quota_v2

---

README.md

Update links, remove outdated info and logo.

Remove outdated info from `README.md`

---

openstack/import_openstack_blockstorage_qos_association_v3_test.go
openstack/provider.go
openstack/resource_openstack_blockstorage_qos_association_v3.go
openstack/resource_openstack_blockstorage_qos_association_v3_test.go
website/docs/r/blockstorage_qos_association_v3.html.markdown
website/openstack.erb

Add new blockstorage_v3 resource for associating a qos
with a volume type.
Fix #1212

Add openstack_blockstorage_qos_association_v3

---

openstack/resource_openstack_networking_network_v2.go

Fixes https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1328

Set `Optional` to network providerext attributes

---

website/docs/r/lb_members_v2.html.markdown

Fix duplicate word in lb_members_v2

docs: Fix duplicated word

---

website/docs/index.html.markdown

Signed-off-by: Tim Beermann <beermann@osism.tech>

added missing environment variables to documentation

---

openstack/resource_openstack_lb_pool_v2.go

Fix PROXYV2 lb pool proto validation

---

openstack/containerinfra_shared_v1.go

https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1308

resolve issue 1308 - Plugin crashes on openstack_containerinfra_cluster_v1

---

.github/workflows/golangci-lint.yml

Use v3 action and v1.46.1 version.

Update golangci-lint action and version

---

openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_compute_instance_v2_test.go
website/docs/r/compute_instance_v2.html.markdown

Signed-off-by: Arthur Outhenin-Chalandre <arthur.outhenin-chalandre@cern.ch>

Add compute instance rebuild support

---

.github/workflows/functional-sharedfilesystem.yml
openstack/provider_test.go

Add new workflow for running functional tests for
sharedfilesystems/manilla.
Requires: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1391

[GH-A] Add workflow for sharedfilesystem

---

.github/workflows/functional-orchestration.yml

[GH-A] Add workflow for orchestration

---

.github/workflows/functional-vpnaas.yml
openstack/resource_openstack_vpnaas_endpoint_group_v2_test.go
openstack/resource_openstack_vpnaas_ike_policy_v2_test.go
openstack/resource_openstack_vpnaas_ipsec_policy_v2_test.go
openstack/resource_openstack_vpnaas_service_v2_test.go
openstack/resource_openstack_vpnaas_site_connection_test.go

[GH-A] Add workflow for vpnaas

---

openstack/resource_openstack_compute_instance_v2.go

Correctly handle missing flavors in openstack_compute_instance_v2

---

openstack/resource_openstack_objectstorage_container_v1.go
openstack/resource_openstack_objectstorage_container_v1_test.go
website/docs/r/objectstorage_container_v1.html.markdown

Add storage_policy to objectstorage_container_v1

---

examples/app-with-networking/datasources.tf
examples/app-with-networking/main.tf
examples/app-with-networking/outputs.tf
examples/attach-format-mount-volume/main.tf
examples/attach-format-mount-volume/outputs.tf
examples/attach-format-mount-volume/volumes.tf
examples/multiple-vm-with-floating-ip/main.tf
examples/multiple-vm-with-floating-ip/outputs.tf

Just accidently run fmt under the repo and saw there are changes

Nit: Fix formatting of examples

---

openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_member_v2_test.go
website/docs/r/lb_member_v2.html.markdown

Add backup to openstack_lb_member_v2

---

website/docs/index.html.markdown

Update version in example usage

---

openstack/containerinfra_shared_v1.go
openstack/data_source_openstack_containerinfra_cluster_v1_test.go
openstack/data_source_openstack_containerinfra_clustertemplate_v1_test.go
openstack/data_source_openstack_containerinfra_nodegroup_v1_test.go
openstack/import_openstack_containerinfra_cluster_v1_test.go
openstack/import_openstack_containerinfra_clustertemplate_v1_test.go
openstack/import_openstack_containerinfra_nodegroup_v1_test.go
openstack/provider_test.go
openstack/resource_openstack_containerinfra_cluster_v1.go
openstack/resource_openstack_containerinfra_cluster_v1_test.go
openstack/resource_openstack_containerinfra_clustertemplate_v1.go
openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go
openstack/resource_openstack_containerinfra_nodegroup_v1_test.go

Few updates for containerinfra tests.
Test 'TestAccContainerInfraV1ClusterTemplate_basic' need fix from PR #1455

Update containerinfra tests

---

website/docs/r/db_user_v1.html.markdown

Simple update of docs to match the resource.
Close #1464

Fix db_user_v1 documentation

---

website/docs/r/identity_ec2_credential_v3.html.markdown

ec2 credentials: add openstack cloud admin note for user_id and project_id fields

---

website/docs/r/dns_zone_v2.html.markdown

Fix docs for dns_zone_v2

---

openstack/resource_openstack_lb_listener_v2.go
website/docs/r/lb_listener_v2.html.markdown

Add Prometheus protocol to listener on Octavia

---

CHANGELOG.md

Update changelog with the latest changes.
Requires #1498 
Close #1484
@ozerovandrei i think after #1498 is merged we can merge this one as well and make a new release

Prepare for new release

---

.github/workflows/release.yml

https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410

Fix release parameters passing

---

go.mod
go.sum
openstack/data_source_openstack_networking_network_v2.go
openstack/import_openstack_networking_network_v2_test.go
openstack/networking_network_v2.go
openstack/resource_openstack_networking_network_v2.go
openstack/resource_openstack_networking_network_v2_test.go
website/docs/d/networking_network_v2.html.markdown
website/docs/r/networking_network_v2.html.markdown

[network v2]: Add support for network segments update and import

---

openstack/import_openstack_networking_router_interface_v2_test.go
openstack/networking_router_interface_v2.go
openstack/resource_openstack_networking_router_interface_v2.go
openstack/resource_openstack_networking_router_interface_v2_test.go
website/docs/r/networking_router_interface_v2.html.markdown

[network v2]: force router extra routes removal for router interface

---

openstack/orchestration_stack_v1.go
openstack/resource_openstack_orchestration_stack_v1.go

[orchestration v1]: fix template type assertion panic

---

openstack/data_source_openstack_identity_auth_scope_v3.go
openstack/data_source_openstack_identity_auth_scope_v3_test.go
website/docs/d/identity_auth_scope_v3.html.markdown

[identity v3]: add an ability to export the auth scope token ID

---

website/docs/r/objectstorage_container_v1.html.markdown

[swift v1]: update docs for a new versioning method

---

openstack/resource_openstack_images_image_v2.go

[glance v2]: remove default value for "decompress" attribute

---

main.go
openstack/provider.go
openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_objectstorage_container_v1.go
scripts/changelog-links.sh
website/docs/index.html.markdown

Noticed a couple of minor typos

Various minor fixes discovered

---

openstack/data_source_openstack_networking_trunk_v2.go
openstack/internal/pathorcontents/read.go
openstack/provider_test.go
openstack/resource_openstack_compute_aggregate_v2.go
openstack/resource_openstack_objectstorage_tempurl_v1_test.go

Revert system scope due to panic

---

.github/workflows/functional-blockstorage_v2.yml
.github/workflows/functional-blockstorage_v3.yml
.github/workflows/functional-compute.yml
.github/workflows/functional-dns.yml
.github/workflows/functional-identity.yml
.github/workflows/functional-images.yml
.github/workflows/functional-keymanager.yml
.github/workflows/functional-loadbalancer.yml
.github/workflows/functional-networking.yml
.github/workflows/functional-objectstorage.yml
.github/workflows/functional-orchestration.yml
.github/workflows/functional-sharedfilesystem.yml
.github/workflows/functional-vpnaas.yml
openstack/import_openstack_lb_members_v2_test.go
openstack/import_openstack_lb_quota_v2_test.go
openstack/provider_test.go
openstack/resource_openstack_lb_members_v2_test.go
openstack/resource_openstack_lb_quota_v2_test.go

Update CI for Antelope/2023.1 release.

Multiple ci changes for Antelope/2023.1

---

README.md
website/docs/index.html.markdown

Update provider version on docs and set note on release docs to update it before new releases.
Close #1288

Update provider version on docs

---

openstack/data_source_openstack_compute_keypair_v2.go
openstack/data_source_openstack_compute_keypair_v2_test.go
website/docs/d/compute_keypair_v2.html.markdown

Add user_id to data_source_openstack_compute_keypair_v2

---

openstack/resource_openstack_vpnaas_ipsec_policy_v2.go
website/docs/r/vpnaas_ipsec_policy_v2.html.markdown

Add various validators to ensure input data from user is valid for VPNaaS. Update docs.
Close #1176

Add validators to openstack_vpnaas_ipsec_policy_v2

---

openstack/import_openstack_identity_role_assignment_v3_test.go
website/docs/r/identity_role_assignment_v3.html.markdown

Add missing test and documentation for
openstack_identity_role_assignment_v3

Add import test for role_assignment

---

openstack/resource_openstack_sharedfilesystem_share_access_v2.go
openstack/sharedfilesystem_share_access_v2.go
openstack/sharedfilesystem_shared_v2.go
website/docs/r/sharedfilesystem_share_access_v2.html.markdown

[manila v2]: introduce a new share access rules read method

---

website/docs/r/compute_instance_v2.html.markdown

The PR #1259 introduce the power state ``shelved_offloaded``. This PR just update the doc about it.

add shelved_offloaded in list of power state available

---

docs/resources/compute_instance_v2.md
docs/resources/compute_volume_attach_v2.md

Docs: Update references to deprecated resources

---

openstack/resource_openstack_lb_pool_v2.go

This pull request fixies the issue [#1627](https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1627).

Return an error when both loadbalancer_id and listener_id are empty.

---

openstack/lb_v2_octavia.go
openstack/resource_openstack_lb_l7policy_v2.go
openstack/resource_openstack_lb_l7policy_v2_test.go

Part of: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1638

Remove support of neutron-lbaas from lb_l7policy

---

docs/data-sources/lb_flavor_v2.md
openstack/data_source_openstack_lb_flavor_v2.go
openstack/data_source_openstack_lb_flavor_v2_test.go
openstack/provider.go
openstack/provider_test.go
scripts/stackenv.sh

In-place of #1651
Close https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1530

Add data source for Octavia flavors

---

.github/workflows/functional-blockstorage_v2.yml
.github/workflows/functional-blockstorage_v3.yml
.github/workflows/functional-compute.yml
.github/workflows/functional-dns.yml
.github/workflows/functional-fwaas_v2.yml
.github/workflows/functional-identity.yml
.github/workflows/functional-images.yml
.github/workflows/functional-keymanager.yml
.github/workflows/functional-loadbalancer.yml
.github/workflows/functional-networking.yml
.github/workflows/functional-objectstorage.yml
.github/workflows/functional-orchestration.yml
.github/workflows/functional-sharedfilesystem.yml
.github/workflows/functional-vpnaas.yml

https://docs.openstack.org/project-team-guide/stable-branches.html#unmaintained
Drop yoga related jobs and bump devstack action

Drop yoga related jobs and bump devstack action

---

openstack/resource_openstack_compute_instance_v2.go

Remove `volume` from compute_instance_v2

---

openstack/resource_openstack_compute_instance_v2.go

Remove floating_ip from compute_instance_v2

---

openstack/resource_openstack_objectstorage_container_v1.go

Remove versioning_legacy from objectstorage_container_v1

---

CHANGELOG.md
docs/guides/upgrade-guide-version-2.md

Update the changelog with all the changes since the last release. Add guide for upgrading to v2 with more details and required steps

Update changelog and add guide for v2 upgrade

---

docs/resources/lb_loadbalancer_v2.md
openstack/resource_openstack_lb_loadbalancer_v2.go

Add support for setting and updating vip_qos_policy_id for the openstack_lb_loadbalancer_v2 resource

Add vip_qos_policy_id for loadbalancer_v2

---

docs/resources/lb_listener_v2.md
openstack/resource_openstack_lb_loadbalancer_v2_test.go
openstack/resource_openstack_lb_pool_v2.go
openstack/resource_openstack_lb_pool_v2_test.go

Update resource resource_openstack_lb_pool_v2
to support setting tags

Add support for tags on lb_pool_v2

---

docs/resources/lb_member_v2.md
openstack/resource_openstack_lb_member_v2.go
openstack/resource_openstack_lb_member_v2_test.go

Update resource resource_openstack_lb_member_v2
to support setting tags

Add support for tags on lb_member_v2

---

docs/resources/lb_monitor_v2.md
openstack/resource_openstack_lb_monitor_v2.go

Add various validations to resource openstack_lb_monitor_v2

Add validations to lb_monitor_v2

---

openstack/resource_openstack_containerinfra_nodegroup_v1.go

This PR fixes error with wrong client microversion (1.9 instead of 1.10) while resizing additional nodegorup to 0.
Fixes #1736

Fix microversion while resizing resource_openstack_containerinfra_nodegroup_v1 to 0

---

.github/workflows/functional-blockstorage_v3.yml
.github/workflows/functional-compute.yml
.github/workflows/functional-dns.yml
.github/workflows/functional-identity.yml
.github/workflows/functional-images.yml
.github/workflows/functional-keymanager.yml
.github/workflows/functional-loadbalancer.yml
.github/workflows/functional-networking.yml
.github/workflows/functional-objectstorage.yml
.github/workflows/functional-orchestration.yml
.github/workflows/functional-sharedfilesystem.yml
.github/workflows/functional-vpnaas.yml
docs/index.md

Fix failing functional tests. Some new neutron policies were added to the port_binding update.
Also fixed some typos and trailing whitespaces.

[test]: fix functional-networking tests and typos

---

openstack/resource_openstack_compute_instance_v2.go

if an instance takes too much time to spawn, terraform throws an error "Error waiting for instance (...) to become ready: context deadline exceeded"
Then, if `terraform apply` is run while the instance is still building, the whole command fails with "Invalid power_state for instance [...]: BUILD"
This PR aims at solving this by supporting the "build" power_state when reading the instance.
1. The `terraform apply` fails with `context deadline exceeded`
2. The instance is tainted due to this error and must be manually untainted
3. When `terraform apply` is run again while the instance is building, the following diff is shown :
```
~ resource "openstack_compute_instance_v2" "worker" {
id                  = "..."
name                = "mydocker-terraform-test-pdg"
~ power_state         = …
```

[compute v2] Support "build" status

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.golangci.yml
.goreleaser.yml

Bump github action dependencies

tests: bump github action dependencies

---

docs/resources/compute_interface_attach_v2.md

Fix typo in the openstack_compute_interface_attach_v2 docs example

---

docs/resources/images_image_v2.md
openstack/resource_openstack_images_image_v2.go

According to https://github.com/openstack/glance/blob/master/doc/source/user/formats.rst
Resolves #1633

[glance]: add new image formats

---

docs/resources/images_image_v2.md
go.mod
go.sum
openstack/images_image_v2.go
openstack/resource_openstack_images_image_v2_test.go

[glance]: decompress "application/octet-stream" streams based on file extension

---

openstack/resource_openstack_networking_portforwarding_v2.go
openstack/resource_openstack_networking_portforwarding_v2_test.go

[networking]: fix portforwarding panic and manage description

---

docs/data-sources/blockstorage_quotaset_v3.md
docs/data-sources/compute_quotaset_v2.md
docs/data-sources/lb_flavor_v2.md
docs/data-sources/networking_qos_policy_v2.md
docs/data-sources/networking_quota_v2.md
docs/data-sources/networking_subnetpool_v2.md
docs/resources/networking_network_v2.md
docs/resources/networking_router_v2.md
docs/resources/objectstorage_container_v1.md
docs/resources/vpnaas_endpoint_group_v2.md
docs/resources/vpnaas_site_connection_v2.md

Fix double whitespaces in docs.

[docs]: fix double whitespaces in docs

---

.github/workflows/functional-bgpvpn.yml
docs/index.md
docs/resources/bgpvpn_network_associate_v2.md
docs/resources/bgpvpn_port_associate_v2.md
docs/resources/bgpvpn_router_associate_v2.md
docs/resources/bgpvpn_v2.md
docs/resources/networking_rbac_policy_v2.md
openstack/bgpvpn_associate_port_v2.go
openstack/import_openstack_bgpvpn_network_associate_v2_test.go
openstack/import_openstack_bgpvpn_port_associate_v2_test.go
openstack/import_openstack_bgpvpn_router_associate_v2_test.go
openstack/import_openstack_bgpvpn_v2_test.go
openstack/provider.go
openstack/provider_test.go
openstack/resource_openstack_bgpvpn_network_associate_v2.go
openstack/resource_openstack_bgpvpn_network_associate_v2_test.go
openstack/resource_openstack_bgpvpn_port_associate_v2.go
openstack/resource_openstack_bgpvpn_port_associate_v2_test.go
openstack/resource_openstack_bgpvpn_router_associate_v2.go
openstack/resource_openstack_bgpvpn_router_associate_v2_test.go
openstack/resource_openstack_bgpvpn_v2.go
openstack/resource_openstack_bgpvpn_v2_test.go
openstack/resource_openstack_networking_rbac_policy_v2.go
openstack/util.go

[networking]: add BGP VPN resources

---

.github/workflows/functional-containerinfra.yml
openstack/data_source_openstack_containerinfra_cluster_v1_test.go
openstack/data_source_openstack_containerinfra_nodegroup_v1_test.go
openstack/import_openstack_containerinfra_cluster_v1_test.go
openstack/import_openstack_containerinfra_nodegroup_v1_test.go
openstack/resource_openstack_containerinfra_cluster_v1_test.go
openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go
openstack/resource_openstack_containerinfra_nodegroup_v1_test.go
scripts/stackenv.sh

[GH-A] Add workflow for containerinfra

---

docs/resources/objectstorage_tempurl_v1.md
openstack/resource_openstack_objectstorage_tempurl_v1.go

swift: add key and digest arguments to tempurl resource

---

openstack/resource_openstack_identity_project_v3.go
openstack/resource_openstack_identity_project_v3_test.go

If identity_project_v3 is domain, then disable it before deletion.
Close: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1549

Disable identity_project_v3 before deletion

---

docs/resources/lb_monitor_v2.md
go.mod
go.sum
openstack/resource_openstack_lb_monitor_v2.go

octavia: add domain_name and http_version to monitor resource arguments

---

docs/resources/objectstorage_account_v1.md
openstack/import_openstack_objectstorage_account_v1_test.go
openstack/provider.go
openstack/resource_openstack_objectstorage_account_v1.go
openstack/resource_openstack_objectstorage_account_v1_test.go

Resolves #1718 
Needs to be in sync with https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1536

swift: add openstack_objectstorage_account_v1 resource

---

go.mod
go.sum

Bump dependencies for the #1785 in order to avoid excessive tests

Bump go.mod dependencies

---

openstack/resource_openstack_bgpvpn_network_associate_v2.go
openstack/resource_openstack_bgpvpn_port_associate_v2.go
openstack/resource_openstack_bgpvpn_router_associate_v2.go
openstack/resource_openstack_bgpvpn_v2.go
openstack/resource_openstack_blockstorage_qos_v3.go
openstack/resource_openstack_compute_aggregate_v2.go
openstack/resource_openstack_compute_instance_v2.go
openstack/resource_openstack_db_configuration_v1.go
openstack/resource_openstack_db_database_v1.go
openstack/resource_openstack_db_user_v1.go
openstack/resource_openstack_fw_group_v2.go
openstack/resource_openstack_fw_rule_v2.go
openstack/resource_openstack_identity_endpoint_v3.go
openstack/resource_openstack_identity_service_v3.go
openstack/resource_openstack_images_image_access_accept_v2.go
openstack/resource_openstack_images_image_access_v2.go
openstack/resource_openstack_images_image_v2.go
openstack/resource_openstack_keymanager_secret_v1.go
openstack/resource_openstack_lb_flavorprofile_v2.go
openstack/resource_openstack_orchestration_stack_v1.go
openstack/resource_openstack_sharedfilesystem_share_v2.go

Ensure that resource was already deleted on deletion action

correctly handle already deleted resources on deletion

---

docs/resources/objectstorage_container_v1.md
openstack/objectstorage_container_v1.go
openstack/resource_openstack_objectstorage_container_v1.go

[swift] add storage class argument to a container resource

---

.github/workflows/functional-bgpvpn.yml
.github/workflows/functional-blockstorage_v3.yml
.github/workflows/functional-compute.yml
.github/workflows/functional-containerinfra.yml
.github/workflows/functional-dns.yml
.github/workflows/functional-fwaas_v2.yml
.github/workflows/functional-identity.yml
.github/workflows/functional-images.yml
.github/workflows/functional-keymanager.yml
.github/workflows/functional-loadbalancer.yml
.github/workflows/functional-networking.yml
.github/workflows/functional-objectstorage.yml
.github/workflows/functional-orchestration.yml
.github/workflows/functional-sharedfilesystem.yml
.github/workflows/functional-vpnaas.yml

Dalmatian jobs have been added.
We generally support 3 latest releases + master => remove antelope ci jobs

Remove antelope ci jobs

---

openstack/data_source_openstack_networking_subnet_v2.go
openstack/data_source_openstack_networking_subnet_v2_test.go
openstack/networking_subnet_v2.go

fixes https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1823

fix: flatten subnet.HostRoutes into slice of maps

---

openstack/resource_openstack_lb_l7rule_v2.go
openstack/resource_openstack_lb_l7rule_v2_test.go

[lbaas] fix l7 rule admin_state_up change

---

go.mod
go.sum

lbaas: fix loadbalancer http_version argument type

---

openstack/data_source_openstack_identity_user_v3.go

identity: properly handle enabled argument in user data source

---

docs/resources/dns_zone_v2.md
openstack/resource_openstack_dns_zone_v2.go

dns: use slash for openstack_dnz_zone_v2 import argument

---

docs/data-sources/lb_flavor_v2.md
docs/data-sources/lb_flavorprofile_v2.md
openstack/data_source_openstack_lb_flavorprofile_v2.go
openstack/data_source_openstack_lb_flavorprofile_v2_test.go
openstack/provider.go

Add lb_flavorprofile_v2 data source

---

openstack/images_image_v2.go

glance: support binary/octet-stream on image decompress

---

docs/data-sources/compute_servergroup_v2.md
openstack/data_source_openstack_compute_servergroup_v2.go
openstack/data_source_openstack_compute_servergroup_v2_test.go
openstack/provider.go

resolves https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1775

add openstack_compute_servergroup_v2 datasource

---

openstack/resource_openstack_lb_quota_v2.go
openstack/resource_openstack_networking_quota_v2.go

skip quota set for undefined arguments

---

.github/workflows/functional-bgpvpn.yml
.github/workflows/functional-blockstorage_v3.yml
.github/workflows/functional-compute.yml
.github/workflows/functional-containerinfra.yml
.github/workflows/functional-dns.yml
.github/workflows/functional-fwaas_v2.yml
.github/workflows/functional-identity.yml
.github/workflows/functional-images.yml
.github/workflows/functional-keymanager.yml
.github/workflows/functional-loadbalancer.yml
.github/workflows/functional-networking.yml
.github/workflows/functional-objectstorage.yml
.github/workflows/functional-orchestration.yml
.github/workflows/functional-sharedfilesystem.yml
.github/workflows/functional-vpnaas.yml
.github/workflows/functional-workflow.yml
openstack/data_source_openstack_compute_aggregate_v2_test.go
openstack/data_source_openstack_compute_availability_zones_v2_test.go
openstack/data_source_openstack_networking_subnet_ids_v2_test.go
openstack/import_openstack_vpnaas_endpoint_group_v2_test.go
openstack/import_openstack_vpnaas_ike_policy_v2_test.go
openstack/import_openstack_vpnaas_ipsecpolicy_v2_test.go
openstack/import_openstack_vpnaas_service_v2_test.go
openstack/import_openstack_vpnaas_site_connection_v2_test.go
openstack/util_test.go
scripts/unittest.sh

tests: enable missed functional tests

---

openstack/data_source_openstack_networking_subnet_ids_v2.go

networking: fix panic regression in subnet ids data source

---

openstack/provider_test.go
openstack/resource_openstack_images_image_v2_test.go

tests: enable skipped glance tests

---

.github/workflows/functional-objectstorage.yml
openstack/import_openstack_objectstorage_account_v1_test.go
openstack/import_openstack_objectstorage_container_v1_test.go
openstack/provider_test.go
openstack/resource_openstack_objectstorage_account_v1_test.go
openstack/resource_openstack_objectstorage_container_v1_test.go
openstack/resource_openstack_objectstorage_object_v1_test.go
openstack/resource_openstack_objectstorage_tempurl_v1_test.go

tests: enable skipped swift tests

---

docs/resources/networking_bgp_peer_v2.md
docs/resources/networking_bgp_speaker_v2.md
openstack/import_openstack_networking_bgp_peer_v2_test.go
openstack/import_openstack_networking_bgp_speaker_v2_test.go
openstack/networking_bgp_v2.go
openstack/provider.go
openstack/resource_openstack_networking_bgp_peer_v2.go
openstack/resource_openstack_networking_bgp_peer_v2_test.go
openstack/resource_openstack_networking_bgp_speaker_v2.go
openstack/resource_openstack_networking_bgp_speaker_v2_test.go

networking: add bgp speaker and peer resources

---

scripts/acceptancetest.sh
scripts/unittest.sh

tests: fix tests regexp pattern

---

openstack/data_source_openstack_compute_instance_v2.go

Flavors may be deleted as part of their lifecycle. Such a case makes the data openstack_compute_instance_v2 crash on 404 when doing tofu plan.
This commit uses the code from https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1362

fix(data/compute_instance_v2): Do not crash on 404 when flavor is not found

---

openstack/resource_openstack_compute_flavor_access_v2.go

Fixes https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1811

Handle when tenant/project already has access to flavor

---

go.mod
go.sum
openstack/resource_openstack_blockstorage_volume_type_v3_test.go
openstack/resource_openstack_sharedfilesystem_securityservice_v2_test.go

utils: fix custom endpoint locator

---

openstack/resource_openstack_containerinfra_cluster_v1.go

containerinfra: correctly handle cluster status during deletion

---

docs/resources/taas_tap_mirror_v2.md
openstack/import_openstack_taas_tap_mirror_v2_test.go
openstack/provider.go
openstack/provider_test.go
openstack/resource_openstack_taas_tap_mirror_v2.go
openstack/resource_openstack_taas_tap_mirror_v2_test.go
scripts/unittest.sh

Closes https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1947

Add TaaS TapMirror resource
